### ISSUE TITLE
Ajuster zoom recherche carte

### ISSUE THREAD

**Issue by florimondmanca** [MTES-MCT/dialog#1001]
## Comportement attendu

Quand je recherche une adresse sur la carte, le niveau de zoom est suffisant pour identifier cette adresse sur la carte

## Comportement réel

Le zoom est trop large

De plus il n'y a pas de pointeur (marqueur)

## Pour reproduire

* Recherche "8 Avenue de la République" sur https://dialog.beta.gouv.fr/carte

## Contexte supplémentaire

Signalé par @johanricher 

## Pistes de résolution

* Ajuster la logique de choix de zoom en fonction du type de lieu (adresse, rue, ville, etc)
* Afficher un marqueur sur le lieu ?

**Comment by johanricher** [comment]
Actuellement on peut paramétrer un niveau de zoom spécifique pour les résultats de recherche d'une rue (e.g . "Avenue de la République, 33000 Bordeaux" -> zoom 17), est-ce qu'on peut faire de même pour les résultat d'une adresse (e.g. "30 Avenue de la République, 33000 Bordeaux" -> zoom 18) ?
