### ISSUE TITLE
Mettre à jour l'en-tête

### ISSUE THREAD

**Issue by johanricher** [MTES-MCT/dialog#1017]
# Description

En parallèle de la mise à jour de la page d'accueil et de la barre de navigation :
* #763 
* #858 

On souhaite mettre à jour l'en-tête du site :

* Ajouter un logo 
* Modifier le titre : `Dialog` au lieu de `DiaLog`
* Supprimer la mention "Bêta"
* Supprimer le bouton "Arrêtés de circulation" (remplacé par un bouton dans la barre de navigation en mode "connecté" cf. #858)
* Modifier le bouton "Se connecter" : suivre DSFR ["bouton primaire"](https://www.systeme-de-design.gouv.fr/composants-et-modeles/composants/bouton)
* Modifier le bouton "Créer un compte" : suivre DSFR  ["bouton secondaire"](https://www.systeme-de-design.gouv.fr/composants-et-modeles/composants/bouton)

# UI

![image](https://github.com/user-attachments/assets/d9433b82-5103-4d25-91e7-e5f1ddd8371e)

[Maquette de référence](https://www.figma.com/design/YuT6Uh4wxe90U8LaPLlDzO/Dialog?node-id=6871-31840&t=lStTZaulGm8NCmhI-4)

**Comment by mmarchois** [comment]
Si je supprime le bouton "Arrêtés de circulation" du header, nous allons avoir un problème de navigation lorsque nous sommes dans la liste des restrictions.
![Image](https://github.com/user-attachments/assets/471208e5-0b88-475b-93d5-e2dfbe665f14)

**Comment by florimondmanca** [comment]
> Modifier le titre : Dialog au lieu de DiaLog

Je pensais que `DiaLog` était l'écriture "officielle" ?

Sur le LinkedIn on utilise bien `DiaLog` par ex https://www.linkedin.com/company/dialog.beta.gouv/posts/?feedView=all

**Comment by johanricher** [comment]
> Si je supprime le bouton "Arrêtés de circulation" du header, nous allons avoir un problème de navigation lorsque nous sommes dans la liste des restrictions.

Oui à faire en parallèle de #858 

> Je pensais que DiaLog était l'écriture "officielle" ?

Moi aussi mais comme c'est dans la maquette j'imagine que ça a été exploré ? A confirmer par @aureliebaton

**Comment by aureliebaton** [comment]
> > Modifier le titre : Dialog au lieu de DiaLog
> 
> Je pensais que `DiaLog` était l'écriture "officielle" ?
> 
> Sur le LinkedIn on utilise bien `DiaLog` par ex https://www.linkedin.com/company/dialog.beta.gouv/posts/?feedView=all

Oui, effectivement, j'avoue un doute mais gardons DiaLog avec le L majuscule alors

**Comment by aureliebaton** [comment]
> > Si je supprime le bouton "Arrêtés de circulation" du header, nous allons avoir un problème de navigation lorsque nous sommes dans la liste des restrictions.
> 
> Oui à faire en parallèle de #858
> 
Ca fait partie des points qu'on doit revoir ensemble ce matin. L'idée était que dans la vu non-connectée, lorsqu'on aura le listing des restrictions on aura plus "besoin" du tableau des arrêtés qui est plutôt pour la vue connectée. A re-discuter ensemble
