### ISSUE TITLE
L'autocomplete des localisations ne fonctionne pas à la Réunion

### ISSUE THREAD

**Issue by MathieuFV** [MTES-MCT/dialog#1030]
## Comportement attendu

On trouve des voies à la Réunion à l'aide des champs de saisie.

## Comportement réel

On peut trouver les communes (l'autocomplete propose des noms et codes INSEE) mais aucune voie ne s'affiche dans le champ libellé de voie.

## Pour reproduire

Tester de saisir une rue, par exemple Auguste de Villèle à Saint-Benoit (974).

## Contexte supplémentaire

Il semblerait qu'on n'ait effectivement pas les DROM-COM dans notre instance de la BDTOPO...

Quand je demande les code Insee dans l'ordre anti-alphabétique, le plus loin est 95590 (Frouville dans le Val d'Oise)

```sql
$ select distinct code_insee from voie_nommee order by code_insee desc limit 10;
 code_insee 
------------
 95690
 95682
 95680
 95678
 95676
 95675
 95660
 95658
 95656
 95652
(10 rows)
```

## Pistes de résolution

pour traiter ce ticket il faudrait

1. Télécharger les fichiers DROM-COM (97x) du dernier millésime https://geoservices.ign.fr/bdtopo#telechargementtransportter
2. Lancer l'import sur un dossier ne contenant que ces fichiers (pas le fichier métropole), cf la doc https://github.com/MTES-MCT/dialog/blob/9d285dae910fa64ef6db226b78dd410ac8300c46/docs/tools/bdtopo.md

**Comment by johanricher** [comment]
Je confirme que la BD TOPO couvre l'ensemble des DROM et COM comme La Réunion, et on retrouve bien la rue Auguste de Villèle dans le fichier "VOIE_NOMMEE".

![image](https://github.com/user-attachments/assets/5a10ab92-7543-499c-a3ed-ca3921f74be1)

A vérifier si on a intégré l'intégralité de la [BD TOPO](https://geoservices.ign.fr/bdtopo) ou si c'est le problème se situe à un autre niveau.

Par ailleurs je constate à cette occasion que la BD TOPO a été mise à jour en septembre 2024. @florimondmanca de quand date notre dernier import ? [Cette page](https://github.com/MTES-MCT/dialog/blob/main/docs/adr/008_bdtopo.md) ne le précise pas mais c'est peut-être documenté autre part ?

**Comment by florimondmanca** [comment]
Il semblerait qu'on n'ait effectivement pas les DROM-COM dans notre instance de la BDTOPO...

Quand je demande les code Insee dans l'ordre anti-alphabétique, le plus loin est 95590 (Frouville dans le Val d'Oise)

```sql
$ select distinct code_insee from voie_nommee order by code_insee desc limit 10;
 code_insee 
------------
 95690
 95682
 95680
 95678
 95676
 95675
 95660
 95658
 95656
 95652
(10 rows)
```

De mémoire, le dernier import date d'un ajout de champ à notre BDTOPO où @mmarchois avait refait un import entier

Mais peut-être n'avait-il téléchargé que le fichier métropole

Note pour le dev, pour traiter ce ticket il faudrait

1. Télécharger les fichiers DROM-COM (97x) du dernier millésime https://geoservices.ign.fr/bdtopo#telechargementtransportter
2. Lancer l'import sur un dossier ne contenant que ces fichiers (pas le fichier métropole), cf la doc https://github.com/MTES-MCT/dialog/blob/9d285dae910fa64ef6db226b78dd410ac8300c46/docs/tools/bdtopo.md

**Comment by florimondmanca** [comment]
Je suis en train d'importer la BD TOPO Thème transport de mars 2024 pour les lieux hors france métropolitaine

Par contre, à partir de l'édition juin 2024, le paquet `troncon_de_route` ne contient plus la colonne `identifiant_voie_1_gauche`, il était déprécié et on doit utiliser `identifiant_voie_ban_gauche` à la place.

Mais ce qui me compose question, c'est que la classe `voie_nommee` ne contient pas pour autant d'identifiant BAN. Il n'y a toujours que `id_pseudo_fpb` qui est encore sensé contenir `identifiant_voie_1_gauche/droite` (d'après la dernière version de la doc de la BDTOPO).

cc@mmarchois Il faudra qu'on s'y penche... Je vais créer un ticket dédié

**Comment by florimondmanca** [comment]
J'ai pu importer les paquets "DROM COM" de la BD TOPO, l'exemple cité fonctionne ainsi que les autres DROM COM (Guadeloupe, Martinique, etc). Je clos mais si un problème persiste on peut revenir dessus !
