### ISSUE TITLE
Calcul de PK/PR sur la RD 1120 en Corrèze

### ISSUE THREAD

**Issue by johanricher** [MTES-MCT/dialog#1032]
## Description

Investigation en cours.

Avant toute chose, on cherche à connaitre comment cette implémentation géocode les PR : service IGN de géocodage de PR avec abscisse ([UI](https://demo-dscr.ign.fr/demonstration/geocode/), [API](https://demo-dscr.ign.fr/api/))

**Comment by johanricher** [comment]
Le contact est en congés jusqu'au 4/11.

**Comment by florimondmanca** [comment]
Suite à la réponse de notre contact à l'IGN

J'ai stocké les documentations qu'il nous a transmises sur le kDrive partagé

Dans la doc  api-v1-pr-geocode.pdf, on trouve bien un avertissement sur le sens de numérisation ( :wink: qui a été corrigé récemment), et on voit aussi une différence importante

De notre côté, on calcule le PR+abs en utilisant la table `troncon_de_route`

L'API DSCR utilise la table `section_de_point_de_repere` et trouve la section à partir deu champ `identifiant_de_section` présent sur cette table ainsi que sur la table `point_de_repere`

La doc BDTOPO dit à propos de la table `section_de_points_de_repere` :

> Définition : Portion de route continue portant le même numéro. Les points de repères sont reliés à une section.
> Chaque section porte un PR de début de section (DS) et un PR de fin de section.
> Source de la mise à jour : Les sections sont calculées à partir des PR projetés sur la table Tronçon de route, et des filaires routiers des gestionnaires.

Donc en fait cette table est construite à partir des tronçons de route, en théorie selon la même logique que notre calcul, mais on peut imaginer que le calcul est "mieux fait" par l'équipe qui produit la BDTOPO que nous.

Pour réduire les risques d'erreur il faudrait donc qu'on s'appuie sur `section_de_points_de_repere`

Ça impliquerait de 

1. Intégrer cette table dans notre instance BDTOPO
2. Modifier le calcul de PR+abs pour utiliser cette table

Le PR+abs est calculé par l'API DSCR comme suit, c'est proche de ce qu'on fait et la diff principale est bien l'usage de la section de point de repère

0. Trouver le PR noté `p` d'où on veut partir grâce aux attributs d'entrée (on le fait déjà)
1. Trouver la section de point de repère notée `s` grâce à l'identifiant de section
2. Calculer l'abscisse du PR sur la section : `abscisse_pr = ST_InterpolatePoint(s.geom, p.geom)` (de notre côté on utilise l'attribut `abscisse` de la table `point_de_repere` mais il s'agit de l'abscisse le long de la route ; or si la route est en plusieurs morceaux comme la RD1120 ça peut poser problème)
3. Calculer les coordonnées du PR+abs : `pr_abs = ST_LocateAlong(s.geom, abscisse_pr + :abscisse)` (on utilise déjà cette fonction `ST_LocateAlong`, mais le long de la route et pas le long de la section de PR)

**Comment by florimondmanca** [comment]
J'ai créé un ticket dédié #1066
