### ISSUE TITLE
L'import de géométrie GeoJSON ne semble pas fonctionner

### ISSUE THREAD

**Issue by MathieuFV** [MTES-MCT/dialog#1071]
## Comportement attendu

Quand on copie/colle un geojson créé à partir d'un service comme GeoJSON.io dans le champ dédié, il est possible de valider la localisation.

## Comportement réel

La validation ne passe pas et on a un message : Cette valeur doit être un GeoJSON valide. (Vous pouvez vous aider d'un validateur tel que https://geojson.io.)

## Pour reproduire

- Créer un nouvel arrêté
- Aller sur GeoJSON.io
- Tracer une géométrie au hasard
- Copier le résultat depuis GeoJSON.io
- Coller dans le champ de géométrie GeoJSON de DiaLog
- Valider

## Contexte supplémentaire

![GeoJSON](https://github.com/user-attachments/assets/40bce60d-d2f5-400a-ab66-bb59f78491d2)

**Comment by florimondmanca** [comment]
@MathieuFV Je propose de préciser dans le msg d'erreur  qu'il faut saisir une _géométrie_ et que Feature et FeatureCollection ne sont pas acceptés
