### ISSUE TITLE
La colonne 'lastFilledStep' devrait être retirée

### ISSUE THREAD

**Issue by florimondmanca** [MTES-MCT/dialog#130]
Découvert en relisant #120 

La colonne `lastFilledStep` sur `RegulationOrderRecord` a été initialement ajouté pour empêcher d'accéder à une étape alors qu'on aurait pas rempli les étapes précédentes : #79 

Mais on peut maintenant accéder à n'importe quelle étape depuis la page de récapitulatif (via les boutons "Modifier").

Cette colonne semble donc inutile aujourd'hui, et de fait elle n'apparaît plus dans le code que pour sa déclaration / getters.

**Comment by mmarchois** [comment]
Effectivement, bonne remarque ! :+1:
