### ISSUE TITLE
ETQ détenteur du pouvoir de police de circulation, je valide le statut de délégataire de la compétence voirie d'un autre utilisateur afin de lui permettre de renseigner des arrêtés sur mon territoire

### ISSUE THREAD

**Issue by MathieuFV** [MTES-MCT/dialog#184]
## User story

ETQ détenteur du pouvoir de police de circulation, je valide le statut de délégataire de la compétence voirie d'un autre utilisateur afin de lui permettre de renseigner des arrêtés sur mon territoire

## Critères d'acceptation

- [ ] _(Must have)_ Les utilisateurs déclarés délégataires de la compétence voirie doivent obtenir une validation
- [ ] _(Nice to have)_ Les utilisateurs déclarés détenteurs du pouvoir de police de circulation sur un territoire reçoivent et approuvent les demandes de validation

## Contexte supplémentaire

Voir aussi #183 : Le détenteur du pouvoir de police de circulation est, par défaut, celui qui exerce la compétence voirie. Il peut la déléguer à un tiers (par exemple au niveau de l'EPCI, mais on peut aussi imaginer un mandataire).

**Comment by florimondmanca** [comment]
Je remets mon commentaire du Pad:

Ici on fait l’hypothèse que la validation se fera dans DiaLog. Est-ce que c’est adapté à tous les cas ? Une signature “en off” (à partir d’un PDF exporté) suffirait-elle ? Comment est alors intégrée la notion de validation dans le passage du “Brouillon” à l’état “Publié” ? Une simple action de type changer le statut ? Ou faut-il une sorte de signature électronique, et alors comment authentifier la personne signataire ? Il faut peut-être extraire une epic “Validation des arrêtés” de l’epic 4 Publication pour pleinement explorer ce sujet. En effet, ce sont deux sujets orthogonaux : on peut imaginer de publier sans validation (c’est le cas actuellement), et faire valider sans forcément publier.

**Comment by florimondmanca** [comment]
@MathieuFV 

"Je valide le statut de délégataire" laisse penser qu'un utilisateur peut faire une sorte de demande pour devenir délégataire". Est-ce que c'est ce qu'on envisage ?

À minima, il me semblerait logique qu'un utilisateur police de circulation doit pouvoir ajouter des utilisateurs comme délégataires de la compétence voirie dans son organisation. On peut éventuellement imaginer un système d'invitation (_nice to have_).

La possibilité pour un utilisateur quelconque de demander à devenir délégataire d'une organisation serait une fonctionnalité distincte.

**Comment by johanricher** [comment]
On ferme ce ticket pour l'instant en attendant d'avancer sur l'exploration de #183
