### ISSUE TITLE
ETQ titulaire/délégataire de la compétence voirie, je modifie les emprises d'un arrêté afin de le garder à jour

### ISSUE THREAD

**Issue by MathieuFV** [MTES-MCT/dialog#193]
## User story

ETQ titulaire/délégataire de la compétence voirie, je modifie les emprises d'un arrêté afin de le garder à jour

## Critères d'acceptation

- [ ] _(Must have)_ La localisation des emprises peut être modifiée
- [ ] _(Nice to have)_

**Comment by florimondmanca** [comment]
@MathieuFV Selon moi cette user story ne concerne pas tant la modification (on peut déjà modifier) que la restriction de cette possibilité au rôle "titulaire / délégataire de la compétence voirie".

On pourrait donc plutôt mettre comme critères d'acceptation :

* _(Must have)_ Un utilisateur ayant le rôle "Compétence voirie" d'une organisation peut modifier les arrêtés brouillon de cette organisation

(La question des arrêtés publiés est en suspens...)

**Comment by florimondmanca** [comment]
Intégré à #188
