### ISSUE TITLE
ETQ titulaire/délégataire de la compétence voirie, je modifie les mesures d'une emprise dans un arrêté et leur plage de validité afin de le garder à jour

### ISSUE THREAD

**Issue by MathieuFV** [MTES-MCT/dialog#194]
## User story

ETQ titulaire/délégataire de la compétence voirie, je modifie les mesures d'une emprise dans un arrêté et leur plage de validité afin de le garder à jour

## Critères d'acceptation

- [ ] _(Must have)_ Les mesures d'une emprise peuvent être modifiées
- [ ] _(Nice to have)_

**Comment by florimondmanca** [comment]
Si on reformule #193 en "ETQ titulaire/délégataire de la compétence voirie comme suggéré ici https://github.com/MTES-MCT/dialog/issues/193#issuecomment-1450492905, je modifie un arrêté brouillon afin de le garder à jour", je pense que cette issue n'est pas nécessaire.

**Comment by florimondmanca** [comment]
Intégré à #188
