### ISSUE TITLE
ETQ titulaire/délégataire de la compétence voirie, j'indique qu'une mesure doit être publiée afin de la communiquer aux parties prenantes

### ISSUE THREAD

**Issue by MathieuFV** [MTES-MCT/dialog#195]
## User story

ETQ titulaire/délégataire de la compétence voirie, j'indique qu'une mesure doit être publiée afin de la communiquer aux parties prenantes

## Critères d'acceptation

- [ ] _(Must have)_ Une switch "publication" doit être présent en face de chaque mesure pour indiquer le souhait de l'utilisateur
- [ ] _(Nice to have)_ On paramètre automatiquement le switch sur "oui" si l'utilisateur renseigne des mesures qui impactent la circulation (selon nous)

**Comment by florimondmanca** [comment]
Ici il faut décider de si une action est nécessaire / pertinente du point de vue utilisateur pour obtenir la publication sur l'endpoint DATEX (option 1).

Ou si la publication se fait "d'office" (option 2).

* L'option 2 est plus compatible avec les principes d'ouverture des données publiques.
* Elle met aussi moins de charge mentale sur les utilisateurs.
* Elle pose aussi moins de questions de notre côté. Par exemple le critère "On paramètre automatiquement le switch sur "oui" si l'utilisateur renseigne des mesures qui impactent la circulation (selon nous)" devient caduque.
* Il faut cependant qu'il soit clair que la "publication" (= passage à l'état publié) a cet effet de diffuser via l'endpoint DATEX et autres connecteurs externes.

Je proposerais qu'on opte pour la publication d'office, et _en cas de retours utilisateurs motivés_, on pourrait investiguer la pertinence d'un "_opt out_". Qu'en pensez-vous ?

**Comment by florimondmanca** [comment]
Après discussion @MathieuFV @mmarchois 

Proposition est faite de tout publier d'office, au moins dans un premier temps
