### ISSUE TITLE
ETQ pouvoir de police de circulation, je valide un arrêté afin d'autoriser sa diffusion

### ISSUE THREAD

**Issue by MathieuFV** [MTES-MCT/dialog#197]
## User story

ETQ pouvoir de police de circulation, je valide un arrêté afin d'autoriser sa diffusion

## Critères d'acceptation

- [ ] _(Must have)_
- [ ] _(Nice to have)_

**Comment by florimondmanca** [comment]
Comme dans #196 je me dis qu'il faut creuser le parcours utilisateur ici aussi. 

Exemples de questions qui me viennent :

* Où est-ce qu'on peut voir les arrêtés "en attente de validation" ?
* En est-on notifié ?
* Quelles informations et actions doivent être disponibles pour traiter la validation ?
* Que se passe-t-il si on "refuse" ?

**Comment by aureliebaton** [comment]
Il est également important de prévoir le cas où certaines mairies ne seront pas équipées de Dialog (comme certaines mairies dans la métropole de Rennes). Donc dans certaines cas, la "validation" et la signature se feront en dehoars de l'outil.

**Comment by johanricher** [comment]
On ferme ce ticket pour l'instant en attendant d'avancer sur l'exploration de https://github.com/MTES-MCT/dialog/issues/183
