### ISSUE TITLE
Intégrer les données DiaLog dans Waze

### ISSUE THREAD

**Issue by florimondmanca** [MTES-MCT/dialog#198]
## Contexte

DiaLog expose actuellement ses données au format Datex II uniquement. A ce sujet, voir la documentation du projet :
* [Format d'échange de données](https://github.com/MTES-MCT/dialog/blob/main/docs/adr/001_exchangeformat.md)
* [Modèle Conceptuel de Données](https://github.com/MTES-MCT/dialog/blob/main/docs/adr/002_mcd.md)

Waze est le service de navigation (GPS) le plus utilisé en France. A ce titre, il représente potentiellement le vecteur principal de diffusion des données de DiaLog.

La documentation publiée par Waze indique que pour intégrer des données dans Waze il est nécessaire de [devenir partenaire](https://www.waze.com/partners/) et de fournir à Waze un flux de données au format XML ou JSON selon la [spécification CIFS](https://developers.google.com/waze/data-feed/cifs-specification).

## Critères d'acceptation

* (Must have) Les restrictions de circulations exposées en Datex II par DiaLog sont visibles par les utilisateurs de Waze.
* (Won't do) Certaines données de DiaLog ne sont pas prises en comptes par Waze.
* ~(Must have) Les utilisateurs de DiaLog sont informés que certaines caractéristiques des arrêtés créés dans DiaLog ne sont pas prises en compte par Waze.~ => À traiter dans #588
* (Could have) À des fins de diagnostic "Pourquoi tel arrêté n'est pas dans tel GPS", pouvoir savoir quels arrêtés n'ont pas pu être exportés en CIFS, et pourquoi

## Exploration

[Pad](https://pad.incubateur.net/oWOMyTaeQ--ruex-WA8lFg)

## Implémentation

* Exposer un endpoint CIFS séparé de l'endpoint DATEX II
  * [Spec](https://developers.google.com/waze/data-feed/cifs-specification)
  * [Exemples](https://developers.google.com/waze/data-feed/road-closure-information?hl=fr#closure-examples)
  * [Schéma XSD](http://www.gstatic.com/road-incidents/cifsv2.xsd)
* Exporter autant d'`incident` (CIFS) que de `period` (DiaLog) (car un incident ne peut avoir qu'un seul `<schedule>` avec 1 créneau horaire par jour de la semaine)
* Ne diffuser que les mesures dont on peut respecter l'intégrité / le sens une fois converties en CIFS
  * Arrêtés temporaires (avec une date de fin) cf. https://github.com/MTES-MCT/dialog/pull/521#issuecomment-1786802739
  * Interdiction de circulation (type ROAD CLOSED)
  * Pas de caractéristiques véhicules
  * Calendrier cohérent avec ce que Waze permet de faire
* Enregistrer le flux partenaire https://www.waze.com/partnerhub/tools-center/partner-feed/request

Travaux en cours :

* [x] Finir #521 => https://dialog.beta.gouv.fr/api/regulations/cifs.xml
* [x] Demander l'enregistrement du flux sur Waze Partner Hub https://www.waze.com/partnerhub/tools-center/partner-feed
* [ ] Obtenir l'approbation du flux
* [ ] Vérifier prise en compte des restrictions dans un itinéraire Waze
* Traitement des problèmes
  * [x] #716 
  * [ ] #729

### Alternatives envisagées

DATEX II vers CIFS

* Pas possible depuis DATEX II TrafficRegulation, car trafficRegulation n'a pas d'ID qui correspondrait à l'ID d'un incident
* Pour info, script de conversion Situation -> CIFS : https://github.com/stadtnavi/cifs-transformer/blob/main/cifs_transformer/datexII2cifs.py#L72

**Comment by florimondmanca** [comment]
@MathieuFV Suite à discussion au daily d'aujourd'hui, je repasse ce ticket en "investigation" car il y a un point assez bloquant : le format CIFS ne permet _pas_ de distinguer les véhicules.

On pourrait fournir les données CIFS mais ce serait seulement celles applicables à "tous les véhicules".

Ça veut dire qu'aujourd'hui Waze n'a pas les connecteurs nécessaires pour accepter la donnée pour "informer les utilisateurs des mesures de restriction de circulation poids lourd" (art. 122).

On pourrait implémenter le CIFS comme preuve de bonne foi, pour montrer qu'on aura essayé, et ce serait d'ailleurs utile à Waze puisqu'établissant un lien avec les arrêtés, mais ça ne servira pas à l'objectif "poids lourds" de DiaLog.

Selon toi, que doit-on faire sur ce ticket ?

**Comment by johanricher** [comment]
J'ai mis à jour ce ticket suite à #425 :

Je propose de mettre de côté pour l'instant l'exploration CIFS afin de comprendre dans quelles conditions des données DiaLog nativement en Datex II pourraient être intégrées à Waze.

@florimondmanca Est-ce que tu peux lister les différentes tâches qui résulterait du feedback qu'on a reçu et les questions en suspens qu'on pourra poser au contact de Waze (au retour de @MathieuFV) ?

**Comment by florimondmanca** [comment]
Je me suis assigné

* Lister les questions à formuler en réponse au retour de Waze
* Voir avec @MathieuFV pour obtenir le contact de Waze pour un échange facilité tech-tech

**Comment by florimondmanca** [comment]
J'ai regardé la dernière réponse de Waze reçue par mail

Il y a un problème de compatibilité.
Notre flux DATEX contient des <trafficRegulationOrder> (arrêtés) qui peuvent avoir plusieurs <trafficRegulation> (restrictions) à l'intérieur.
Chaque <trafficRegulationOrder> a un ID (l'ID de l'arrêté), mais DATEX II ne permet pas d'en définir sur <trafficRegulation>.
Or, CIFS requiert que chaque événement (restriction) ait un ID.

Je vois alors 3 possibilités

Modifier notre export DATEX pour que 1 trafficRegulationOrder ne contiendrait qu'un seul trafficRegulation
C'est ce que Waze suggère
Le problème c'est qu'on dévierait du sens de DATEX II. trafficRegulationOrder est décrit ainsi : " legally recognised document or publication issued to enact a specific traffic regulation or regulations by a competent authority" Ça représente donc un arrêté. Si on "découpe" l'arrêté en plusieurs "arrêtés fictifs", on s'éloigne de la réalité et ça me semble problématique.
D'autre part, ça serait "tordre" le standard pour plaire à un GPS donné. Si tous les GPS nous demandent des ajustements de ce type, on s'en sortira pas.

Etendre DATEX II pour permettre de définir un id sur <trafficRegulation>.
Concrètement on remplirait ce champ avec l'ID de la restriction. Dans ce cas Waze utilisera cet ID-là plutôt que l'ID de l'arrêté pour identifier l'événement (ça semble logique : 1 événement = 1 restriction).
Problème : l'extension de DATEX II n'a pas l'air tout à fait triviale. https://docs.datex2.eu/expert/level2extensionguide.html
Mais on peut peut-être s'en sortir, car ce serait "seulement" ajouter un champ à une classe existante (TrafficRegulation).
À creuser.

Exporter du CIFS XML bien formatté nous-mêmes
Ça serait renoncer à DATEX II comme format standard unifié pour tous les GPS.

Je suis donc tenté de creuser l'option 2

Des avis ?

**Comment by mmarchois** [comment]
Merci @florimondmanca pour ton retour.

Plusieurs remarques :
- Totalement d'accord sur le fait de ne pas tordre le standard DATEXII pour "plaire" à Waze ... 
- Est-on sûr que Waze (et autres systèmes de navigation) prendront bien en compte l'extension DATEXII pour y rajouter l'ID ?
- L'option 3 ne me convient pas totalement. Je trouverai dommage d'abandonner ce format.… 
- Une 4e option serait une évolution de la 3e : on conserve notre export DATEXII mais on propose également un export CIFS qui sera plus adapté à Google et Waze. L'inconvénient sera de maintenir deux systèmes, mais a-t-on le choix ?

Qu'en pensez-vous ?

**Comment by florimondmanca** [comment]
>  on conserve notre export DATEXII mais on propose également un export CIFS qui sera plus adapté à Google et Waze.

C'est ce que je voulais dire dans l'option 3, on conserve DATEX II mais _en plus_ on exporte un CIFS XML bien formatté par nos soins pour l'utilisation de Waze.

En espérant que les autres GPS pourront utiliser DATEX II correctement.

**Comment by johanricher** [comment]
>  CIFS requiert que chaque événement (restriction) ait un ID.

A aucun moment dans les échanges avec Waze ils ne parlent de CIFS. Ma compréhension c'est qu'ils implèmentent DATEX II. Leur implémentation semble différer de la nôtre mais je ne crois pas que ça ait un lien avec CIFS.

**Comment by johanricher** [comment]
[La spec](https://docs.datex2.eu/trafficregulation/) ne semble pas tout à fait soutenir ces hypothèses. L'arrêté (texte juridique publié par une autorité administrative) est le `LegalBasis`, qui peut déterminer plusieurs instances de `TrafficRegulationOrder` qui peuvent avoir plusieurs `TrafficRegulation`.

* `trafficRegulationOrder` = paquet (qui contient notamment le `LegalBasis`) qui permet de décrire la façon dont est publiée une restriction de circulation, c'est à dire l'arrêté
* `TrafficRegulation` = paquet qui décrit les informations sur une restriction de circulation, c'est à dire les conséquences de l'arrêté

J'ai l'impression que notre implémentation de Datex II confond les deux notions.

**Comment by florimondmanca** [comment]
> A aucun moment dans les échanges avec Waze ils ne parlent de CIFS. 

Dans les échanges de mails, notre contact fait référence à la spec CIFS dans des hyperliens pour justifier tel ou tel mapping de champ. Mon impression est qu'ils implémentent DATEX II mais en réutilisant leur "modèle de données CIFS" par derrière.

La notion "d'événement" (comme dans "event ID") est absente de DATEX II, mais centrale dans CIFS : ["type of your event", "the way your event will be consumed by Waze", "the road on which the event is occurring", etc](https://developers.google.com/waze/data-feed/cifs-specification?hl=en).

Je veux bien demander une confirmation explicite que c'est bien cette approche technique qui est employée.

**Comment by mmarchois** [comment]
Le CIFS est le format standard de Waze. Le DATEX II n'est, d'ailleurs, pas spécifié dans la documentation sur la création d'un flux partenaire. (cf https://github.com/MTES-MCT/dialog/wiki/Analyse-de-l'existant#waze)

**Comment by florimondmanca** [comment]
> L'arrêté (texte juridique publié par une autorité administrative) est le LegalBasis, qui peut déterminer plusieurs instances de TrafficRegulationOrder qui peuvent avoir plusieurs TrafficRegulation.

La legalBasis est bel et bien une propriété de `TrafficRegulationOrder`. Ça n'apparaît pas sur le diagramme UML simplifié sur la page que tu as partagé, mais c'est bien défini comme ça dans le schéma :

https://github.com/MTES-MCT/dialog/blob/ac45b8d86706fe483b6eb87f65950d165b616b8c/docs/spec/datex2/DATEXII_3_TrafficRegulation.xsd#L1700-L1704

Par contre c'est vrai qu'un `TrafficRegulationsFromCompetentAuthorities` peut contenir plusieurs `TrafficRegulationOrder`.

Mais :

* `TrafficRegulationsFromCompetentAuthorities` n'a pas d'autre propriétés qu'une liste de `TrafficRegulationOrder`, en particulier pas de propriété ID.
* `TrafficRegulationOrder` représente bien un arrêté ou autre document ou loi (la legalBasis permet de préciser en format texte la référence de cet arreté) : "Traffic regulations from competent authorities are published through a traffic regulation order."

Donc ça ne résout pas la problématique du fait qu'on ne peut inscrire des "event IDs" (à mon sens, les IDs des mesures) qu'à 1 niveau, dans `<trafficRegulationOrder id="...">``. Or cet élément fait bien référence à un arrêté, d'où ce que j'indiquerais comme inconvénients/risques de l'option 1.

**Comment by MathieuFV** [comment]
> L'arrêté (texte juridique publié par une autorité administrative) est le `LegalBasis`, qui peut déterminer plusieurs instances de `TrafficRegulationOrder `qui peuvent avoir plusieurs `TrafficRegulation`.

Je pense que **pour un gestionnaires d'infra**, la `LegalBasis `(base légale) ferait plutôt référence aux annexes citées en entête d'un arrêté, par exemple le code de la route, le code général des collectivités territoriales, etc. Qui légitiment le droit du signataire de l'arrêté à prendre les décisions qui y sont consignées.

Et ensuite le `TrafficRegulationOrder `est l'acte qui réunit une ou plusieurs `TrafficRegulation `sur la base de cette `LegalBasis`.

Mais je n'ai pas lu en détail la spec donc c'est surtout pour vous faire part du point de vue "métier".

**Comment by florimondmanca** [comment]
On devrait pouvoir relancer ce sujet bientôt, maintenant que l'intégration des données Eudonet est proche #343 ?

Proposition de @MathieuFV au daily du jour : leur fournir un endpoint CIFS "appauvri" (puisque CIFS est moins riche que DATEX), en communiquant sur les pertes par rapport à DATEX II (caractéristiques véhicules, etc).

**Comment by florimondmanca** [comment]
À noter : Waze un processus de validation au cas par cas des routes fermées (ROAD_CLOSED)

https://developers.google.com/waze/data-feed/road-closure-information?hl=fr

> Ces problèmes de carte nécessitent qu'un éditeur de carte de niveau supérieur de la communauté les examine, les approuve ou les refuse. Une fois les examens et les approbations terminés, les routes fermées s'affichent sur la carte.

Ça signifie que l'ingestion CIFS ne "suffit" pas, il faut ensuite que la donnée passe cette étape de validation.

**Comment by johanricher** [comment]
>  il faudrait alors par précaution appeler leur géocodeur inverse

Pour moi ce n'est utile que pour vérifier que Waze retrouve bien dans sa base adresse le nom de la voie qu'on lui fournit. Comme dit précédemment (https://github.com/MTES-MCT/dialog/issues/419#issuecomment-1660705243), les différents fournisseurs services de navigation (Waze, HERE, TomTom...) ont tous des bases adresses et des géocodeurs différents. Je pense qu'on ne doit pas intégrer dans notre base des spécificités liées à l'un ou l'autre de ces systèmes mais plutôt travailler de façon plus générique avec eux, en identifiant clairement les problèmes d'intégration de nos données dans ces systèmes, pour les résoudre au cas par cas.

Donc je dirais qu'il faut d'abord aller jusqu'au bout de l'intégration de nos données dans Waze, de telle façon à ce qu'on puisse le constater directement depuis l'interface de l'application, en conditions réelles, ou par un autre moyen comme leur outillage partenaires par exemple. Et on améliorera ensuite en fonction de ça et des éventuels retours qu'on aura.

**Comment by MathieuFV** [comment]
J'ai réussi à ajouter deux polygones dans le hub partnership Waze... On a à peu près le quart nord-ouest de couvert. Je vais continuer comme ça même si je trouve ça un peu étrange et on arrivera peut être à couvrir toute la France...

**Comment by florimondmanca** [comment]
@MathieuFV est en train d'ajouter les polygônes de couverture qui représentent l'espace où on va pouvoir leur envoyer des données...

Dans le Partners Hub il y a une section "Flux partenaire", c'est là qu'il faudra visiblement soumettre notre endpoint CIFS

https://www.waze.com/partnerhub/tools-center/partner-feed/request

**Comment by florimondmanca** [comment]
#521 a été mergée, j'ai fait la demande d'ajout du flux sur Waze Partner Hub, il est "en attente d'approbation"

**Comment by florimondmanca** [comment]
Je relis les critères d'acceptation, que devrait-on faire concernant celui-ci ? cc @aureliebaton 

> (Must have) Les utilisateurs de DiaLog sont informés que certaines caractéristiques des arrêtés créés dans DiaLog ne sont pas prises en compte par Waze.

**Comment by florimondmanca** [comment]
OK pour moi

**Comment by florimondmanca** [comment]
Réponse de Waze (signé "Mel"), pas encore analysé mais apparemment les linéaires de l'IGN ne leur vont pas :thinking: 

Hi Florimond,

We received your feed (dialog.beta.gouv.fr), and have some feedback.

To ensure your road closures are automatically added to the map, please change the following to meet our requirements:

    Update the polyline coordinates (lat/lon for the closure path)
        Provide at least 2 sets of unique coordinates.
        Keep the length of your road closure between 35 m - 10 km (6.2 mi).
        Place the first and last points of your road closure around a junction or intersection and not in the middle of a road. Only a whole segment of a road can be added as a closure, and not just parts of it.

**Comment by johanricher** [comment]
Lors du passage en revue des données DiaLog (export CIFS) [le 15/02](https://pad.incubateur.net/MaOMoW0QS82FIj5oAABVAw#2024-02-15-Probl%C3%A8mes-d%E2%80%99int%C3%A9gration-de-donn%C3%A9es) on a constaté des problèmes à résoudre avant de reprendre, en faisant table rase, les travaux et échanges en vue d'une intégration de nos données dans Waze.

En attente de :
* #533 
* #623 

Une fois ces étapes franchies on refera un nouveau contrôle qualité similaire au précédent (à la main, échantillon au hasard).

**Comment by florimondmanca** [comment]
Je n'ai pas l'impression que les problèmes qu'on avait discutés et listés dans le pad soient dûment trackés ici

Les tickets #533 et #623 ne vont pas résoudre certains problèmes comme certaines localisations qu'on devrait juste exclure, ou le fait de s'assurer que l'intégration Eudonet exclut en entier tout arrêté où on n'arrive pas à intégrer fidèlement une donnée, ce qui inclut le géocodage

Concernant ce point

> Beaucoup de “if” dans l’ETL d’intégration, spécifique pour chaque intégration, pas pertinent de rendre générique à ce stade, hardcoding pour exclure les arrêtés qui posent problème

Ça rejoint un peu les discussions sur le degré "d'artisanalité" des intégrations, c'est intéressant

Je dirais qu'il faut considérer l'adage "all data is messy", et qu'il y aura des cas à exclure "manuellement" (avec des if ou autres formes de "filtres" spécifiques), des situations particulières à traiter et qui font sens, etc

Néanmoins je suis d'accord pour dire qu'il faut réduire les cas spéciaux au minimum. Faire des hypothèses de base et dès qu'elles ne sont pas remplies, on zappe, plutôt qu'essayer de modifier ou interpréter un peu la donnée source pour la faire rentrer dans ces hypothèses.

Il y a cependant probablement un compromis à trouver entre volume de données intégré et "sévérité" par rapport aux données sources. Certaines interprétations spécifiques à telle ou telle intégration peuvent faire sens.

À terme, dans le cas de la gestion de nombreuses intégrations, il y a deux approches potentiellement complémentaires qui me viennent en tête. D'une part tendre vers un "coeur" le plus générique possible. D'autre part, permettre un niveau de spécialisation mais le "pousser" vers une frontière clairement définie, et surtout définie de façon la plus déclarative possible (en gros, un fichier de conf plutôt que du code supplémentaire). Ainsi on aurait un "coeur d'intégration" (en PHP, vite dit), et des "fichiers de conf" pour chaque intégration. Ça serait l'idéal.

Mais ça me semble encore beaucoup trop tôt...

**Comment by johanricher** [comment]
D'accord avec tout ce que tu dis, en tout cas la partie que je comprends :slightly_frowning_face: et pas d'avis sur la partie plus technique.

J'ai ajouté le ticket #663 dans mon commentaire précédent, il pourra servir à centraliser les discussions sur le "contrôle qualité" Eudonet, pour qualifier les problèmes de façon plus précise qu'actuellement, et kes détailler éventuellement dans des tickets dédiés (qu'on pourra prioriser / étaler dans le temps).
