### ISSUE TITLE
ETQ utilisateur connecté, je consulte les arrêtés temporaires passés afin de répondre à une sollicitation extérieure

### ISSUE THREAD

**Issue by MathieuFV** [MTES-MCT/dialog#203]
## User story

ETQ utilisateur connecté, je consulte les arrêtés temporaires passés afin de répondre à une sollicitation extérieure

## Critères d'acceptation

- [ ] _(Must have)_ L'utilisateur peut accéder à un tableau ne contenant que les arrêtés passés

**Comment by johanricher** [comment]
La page [/regulations](https://dialog.incubateur.net/regulations) permet de consulter la liste des arrêtés temporaires "passés" (publiés). Il me faudrait je pense un exemple de situation en conditions réelles où l'application présente un manque ou un irritant en l'état actuel.

**Comment by johanricher** [comment]
Remplacé par #202

**Comment by MathieuFV** [comment]
Fermé comme faisant partie des fonctionnalités de recherche avancée de #202

Exemple de cas d'usage : Un assureur demande à obtenir un arrêté temporaire qui était en vigueur le jour d'un accident (dans le passé), je souhaite donc retrouver les arrêtés qui mentionnent une localisation précise et étaient en vigueur à la date de l'accident.
