### ISSUE TITLE
ETQ qu'utilisateur connecté, je consulte la liste des arrêtés permanents en vigueur afin de consulter l'ensemble des arrêtés permanents dans la base de données.

### ISSUE THREAD

**Issue by MathieuFV** [MTES-MCT/dialog#204]
## User story

ETQ qu'utilisateur, je consulte la liste des arrêtés permanents afin de consulter l'ensemble des arrêtés permanents en vigueur dans la base de données.

## Critères d'acceptation

- [ ] _(Must have)_ L'utilisateur peut accéder à un tableau ne contenant que les arrêtés permanents

**Comment by johanricher** [comment]
La page [/regulations](https://dialog.incubateur.net/regulations) permet de consulter la liste des arrêtés permanents "en vigueur" (publiés).
