### ISSUE TITLE
ETQ compétence voirie, je publie un arrêté validé afin de le diffuser aux GPS

### ISSUE THREAD

**Issue by florimondmanca** [MTES-MCT/dialog#206]
## User story

ETQ compétence voirie, je publie un arrêté validé afin de le diffuser aux GPS

## Critères d'acceptation

- [ ] _(Must have)_ Critère 1
- [ ] _(Nice to have)_ Critère 2

**Comment by johanricher** [comment]
Est-ce que ce ticket est encore d'actualité ?

**Comment by florimondmanca** [comment]
La seule différence avec l'état actuel est le "validé". Aujourd'hui on peut "publier" un arrêté et l'effet sera notamment de l'ajouter à l'export DATEX. Mais il n'y a pas encore de notion de "validation". Ça doit sûrement être une story à part ?

**Comment by johanricher** [comment]
Je vois en effet un label dédié https://github.com/MTES-MCT/dialog/labels/EPIC%20-%20Validation%20des%20arr%C3%AAt%C3%A9s qui contient un ticket qui introduit la notion de valider un arrêté "afin d'autoriser sa diffusion". Pour l'instant je laisse tel quel en attendant d'avoir plus d'infos mais pour moi il manque des éléments qui permettent de comprendre le besoin et un exemple d'usage potentiel constaté en conditions réelles.

**Comment by johanricher** [comment]
On ferme ce ticket pour l'instant en attendant d'avancer sur l'exploration de #183
