### ISSUE TITLE
Refonte de la page d'accueil et ajout de nouvelles pages par profil 

### ISSUE THREAD

**Issue by MathieuFV** [MTES-MCT/dialog#219]
## User story

ETQ potentiel utilisateur/réutilisateur, je me rends sur la page d'accueil de DiaLog afin de m'informer sur l'outil

## Critères d'acceptation

- [ ] _(Must have)_ La page d'accueil permet aux prospects de comprendre l'intérêt de DiaLog et d'accéder aux informations correspondant à leur profil (collectivités, services numériques, usagers de la route)

## Design

La page d'accueil est complètement refondue et 3 nouvelles pages sont ajoutées :
* Collectivités
* Services numériques
* Usagers de la route

Chacune de ces pages est accessible depuis un onglet dans le header.

[Maquettes](https://www.figma.com/file/YuT6Uh4wxe90U8LaPLlDzO/Dialog?type=design&node-id=2189-111201&mode=design&t=baCAPBH44VIgL7PJ-4)

:warning: Voir les commentaires sur Figma pour des précisions sur certains éléments.

## Implémentation

On peut se répartir les pages

1. Créer un controller pour la nouvelle landing, par ex `/v2`. Rien ne pointera vers cette page
2. Ajouter les pages au fur et à mesure (collectivités, services num, usagers)
3. Quand tout est prêt, faire le "switch" : la nouvelle landing passe sur `/` et l'ancienne disparaît

* Nouvelle landing => @Lealefoulon #449 #454
* Collectivités => @florimondmanca #447
* Services numériques => @Lealefoulon #453
* Usagers => @florimondmanca #463
* Finalisation => @Lealefoulon 
  * Cartes cliquables #465 
  * Layout 'landing' avec la nouvelle navbar. Le layout actuel reste appliqué aux pages sous /regulations, dans un layout appelé par exemple 'app'.

**Comment by MathieuFV** [comment]
TO DO : 

- Préparer les éléments du bloc pédagogique : FAQ + Etape par étape. On nomme ce bloc "Comment ça marche ?"
- Le bouton du header "Comment ça marche ?" renvoie à ce bloc
- Discuter de la vidéo pédagogique, de ce qui pourrait la remplacer si on préfère un autre médium
- Choix de si on prend une nouvelle adresse mail dédiée pour le support 
- Construire une newsletter :')

**Comment by astranchet** [comment]
J'ai commencé à mettre en place certains changements pour visualiser
![Image](https://user-images.githubusercontent.com/1374389/224965596-1d94382f-6894-4b8d-b432-c3e6933a985b.png)

**Comment by MathieuFV** [comment]
Point avec Aurélie le 17 mars 2023 : 

**Comment ça marche :** 

Une page dédiée avec un paragraphe explicatif + Un processus étape par étape (voir ci-dessous) + FAQ (à faire)

1° En tant qu'administration, je numérise mes arrêtés de circulation dans DiaLog
2° DiaLog transforme les données dans le bon format
3° Les GPS récupèrent l'information et la diffusent dans leurs outils

=> Le processus étape par étape pourra être réutilisé en Home Page.

- Article 122 : C'est quoi ? Comment ça marche ? Suis-je concerné ? => Landing page GPS ou Home page ?
- Accéder à la base de données : Expliquer ce qui est dispo aujourd'hui et ce qui est en préparation (pareil que pour Comment ça marche ?)

**Comment by johanricher** [comment]
[Les maquettes Figma](https://www.figma.com/file/YuT6Uh4wxe90U8LaPLlDzO/Dialog?type=design&node-id=2189-111201&mode=dev) (quatre pages "Landing v2") ont été finalisées et le ticket est mis en "Prêt à développer" afin de les implémenter. Il manque des précisions sur certains éléments en particulier vers quoi doivent pointer les liens et autres boutons. Je propose d'utiliser les commentaires afin d'apporter les derniers détails sur ce qu'il faut implémenter.

**Comment by johanricher** [comment]
Je ne comprends pourquoi la page d'accueil a été mise en prod alors qu'il reste des discussions sur le Figma et que les autres pages ne sont pas finalisées ?

**Comment by florimondmanca** [comment]
L'ensemble des nouvelles pages de landing ont été implémentées

Voir https://dialog.beta.gouv.fr

Des suggestions d'affinage ont été faites et seront traitées par #470 

Je propose de clore ce ticket
