### ISSUE TITLE
Les numéros devraient être désactivés quand la restriction s'applique à la commune entière

### ISSUE THREAD

**Issue by aureliebaton** [MTES-MCT/dialog#266]
## Comportement attendu

Lorsque je spécifie la ville uniquement, les numéros de rue devraient être désactivés car aucune voie n'est spécifiée.

## Comportement réel

Lorsque j'entre la ville uniquement dans le champ, je peux indiquer des numéros de rue.

## Pour reproduire

- Sur le formulaire de localisation, entrer le nom de la ville
- Entrer des numéros de début et fin

## Pistes de résolution

Si on entre la ville uniquement dans le champ, il ne devrait pas y avoir les numéros car ils ne pourraient pas s'appliquer s'il n'y a pas de rue. Solution : griser les champs numéro de début et numéros de fin.

**Comment by MathieuFV** [comment]
Fermé car on désactive la possibilité de renseigner des restrictions sur des communes entières. Voir #536.
