### ISSUE TITLE
[perf] Récupération des objects `regulationOrder` et `regulationOrderRecord` eu deux requêtes au lieu d'une

### ISSUE THREAD

**Issue by mmarchois** [MTES-MCT/dialog#273]
Lorsque j'ai besoin de récupérer un objet `regulationOrder` depuis `regulationOrderRecord`, je ne devrais pas avoir une requête SQL supplémentaire.

**Comment by florimondmanca** [comment]
@mmarchois Dans quelles situations / quelles parties du code on fait actuellement une requête supplémentaire ?

**Comment by mmarchois** [comment]
Dès lors que tu fais un `$regulationOrderRecord->getRegulationOrder()`, il te génère une requête SQL pour aller récupérer le regulationOrder, alors qu'on a bien les jointures qui vont bien etc. Je me demande si ce n'est pas lié à la relation `OneToOne`.

**Comment by johanricher** [comment]
Est-ce que ce sujet est toujours d'actualité ?

**Comment by florimondmanca** [comment]
Peut-être mais c'est vraiment mineur. Je ne pense pas que ça soit prioritaire. Je serais à l'aise pour fermer le ticket, personnellement.
