### ISSUE TITLE
Liste : la suppression d'un arrêté ne nécessite pas de recharger toute la page

### ISSUE THREAD

**Issue by mmarchois** [MTES-MCT/dialog#282]
## Problème

Actuellement, quand on supprime un arrêté dans la liste, toute la page est rechargée entièrement (redirection 303) afin d'afficher le nouveau tableau

On pourrait en fait ne renvoyer que le nouveau tableau

Ça évite au navigateur de retraiter le CSS, le JS, etc etc

## Solution envisagée

Recharger uniquement le `.fr-tabs` contenant le tableau, les onglets avec les totaux, et la pagination

## Suites possibles

Dans un second temps, on peut être + fin :

* `delete` la ligne supprimée
* Charger la ligne de la page suivante le cas échéant
* Mettre à jour la pagination (si jamais la page suivante est la dernière et qu'elle ne contenait qu'1 seul item)
* Mettre à jour les totaux

**Comment by johanricher** [comment]
Est-ce que ce sujet est toujours d'actualité ? la PR #284 a été abandonnée mais je ne comprends pas pourquoi

**Comment by florimondmanca** [comment]
@johanricher On avait abandonné la PR pour la raison indiquée dans cette conclusion de discussion https://github.com/MTES-MCT/dialog/pull/284#discussion_r1172664884

En bref, on était finalement partis sur autre chose sans pour autant forcément rendre ce ticket 282 caduque

Ce ticket est tjr d'actu car le comportement décrit est toujours actuel : on supprime un arrêté, la page se recharge

Mais ça me paraît mineur comme sujet, pas très impactant ni prio à mon avis. De même, je serais à l'aise pour le fermer...

**Comment by florimondmanca** [comment]
Ce ticket me semble obsolète, la liste a été refondue depuis
