### ISSUE TITLE
[Turbo Stream] Dans le formulaire de création d'un arrêté, lorsqu'une erreur de validation est remontée par le backend, elle n'est plus affichée dans le frontend

### ISSUE THREAD

**Issue by mmarchois** [MTES-MCT/dialog#285]
## Comportement attendu

Lorsque je fais une erreur de saisi dans le formulaire de création d'un arrêté (identifiant déjà existant ou date incorrecte), je dois voir l'erreur remonter au niveau du champ. Actuellement, plus rien n'est précisé et on ne comprends pas pourquoi on ne peut pas passer à l'étape suivante.

## Pour reproduire

- Visiter l'URL http://localhost:8000/regulations/add
- Remplir les informations du formulaire avec un identifiant déjà existant
- Soumettre le formulaire
- Rester sur la même page sans voir le message d'erreur

## Pistes de résolution

Cette erreur se produit uniquement dans le cas de la création d'un arrêté et est causée par `'data-turbo-frame' => !$options['isEdit'] ? '_top' : null'` (`src/Infrastructure/Form/Regulation/GeneralInfoFormType.php:L81`).

**Comment by florimondmanca** [comment]
@mmarchois Qq questions complémentaires pour mieux comprendre

Comment as-tu déterminé que le pb provenait du data-turbo-frame ?

Lors de la création on est en `_top` effectivement, qu'est-ce que cela pourrait changer au rendu du formulaire ? Les `<p />` d'erreurs ne sont pas présents dans le DOM ? En quoi Turbo (Streams) pourrait perturber ça ? On n'a pas l'air de le détecter dans les tests d'intégration.

**Comment by mmarchois** [comment]
@florimondmanca Je me suis aperçu qu'en commentant cette ligne, ça fonctionnait de nouveau. Le problème, c'est que lors de la validation et du passage à l'étape suivante, tu restes sur la même frame ....

**Comment by florimondmanca** [comment]
OK, ma question portait plus sur la compréhension de _pourquoi_ le `_top` n'affiche pas les erreurs quand il y en a

Comme on renvoie le fragment `general_info_form`, je m'attendrais à ce qu'on ait le formulaire "brut" affiché en pleine page (effet du `_top`)

J'imagine que Turbo ne fait cet affichage pleine page qu'en cas de réponse 200 OK ? En cas d'erreur on renvoit une 422.
