### ISSUE TITLE
Affichage de la page de détail d'un arrêté HS sur format Tablette et Mobile 

### ISSUE THREAD

**Issue by Lealefoulon** [MTES-MCT/dialog#312]
## Comportement attendu
Les boutons "modifier" et "supprimer" doivent être alignés et ne pas sortir de leur "card"

## Comportement réel

Le bouton modifier sort de son contenant à partir d'un écran medium. 
En mode mobile les boutons "modifier" et "supprimer" ne sont pas alignés

## Pour reproduire

- Visiter l'URL : https://dialog.incubateur.net/regulations
- Cliquer sur un bouton de modification d'un arrêté
- Réduire la taille de l'écran au format tablette puis mobile
- Constater le problème

## Traces et captures d'écran
en mode tablette : 
![image](https://user-images.githubusercontent.com/116151499/235706331-2399604e-5460-4597-8156-1c51cb48e39a.png)

en mode mobile : 

![image](https://user-images.githubusercontent.com/116151499/235706571-1b219c1c-a073-4431-b96d-91142944fbba.png)

## Pistes de résolution

Revoir le nombre de colonnes en mode medium (tablette) 
Appliquer les mêmes marges / centrage aux boutons "supprimer" et "modifier" ? (affichage mobile)

**Comment by florimondmanca** [comment]
Ça provient de #281... Il va falloir qu'on systématise un peu plus de développer en mode mobile first...

**Comment by mmarchois** [comment]
Est-ce qu'on laisse uniquement les icons ? 
@florimondmanca indeed, mais faudrait que ce soit aussi le cas en design alors, sinon c'est compliqué je trouve.
