### ISSUE TITLE
En tant qu’utilisateur non-connecté, je me connecte afin d’accéder aux fonctionnalités qui me sont accessibles

### ISSUE THREAD

**Issue by mmarchois** [MTES-MCT/dialog#35]
Idée : des identifiants partagés pour l’instant ? MonComptePro plus tard…

**Comment by astranchet** [comment]
Clairement, c'est pas la US qui a le plus de valeur ajoutée pour le moment ; donc aller au plus simple.

**Comment by mmarchois** [comment]
@astranchet exactement, on va faire une authentification vraiment simple ("basic auth"), mais qui protègera l'application tout de même.

**Comment by mmarchois** [comment]
@MathieuFV Tu peux tester de ton côté sur l'URL https://dialog-staging-pr54.osc-fr1.scalingo.io/
