### ISSUE TITLE
ETQ compétence voirie, je renseigne les visas liés à un arrêté pour donner une base juridique au dispositif qui y est décrit

### ISSUE THREAD

**Issue by MathieuFV** [MTES-MCT/dialog#355]
## User story

ETQ compétence voirie, je renseigne les visas liés à un arrêté pour donner une base juridique au dispositif qui y est décrit

## Critères d'acceptation

- [ ] _(Must have)_ L'utilisateur peut renseigner les visas dans un champ texte
- [ ] _(Nice to have)_ L'utilisateur dispose d'un champ visas et d'un autre champ visas complémentaires

## Design

Les visas sont des références à des textes précédant l'arrêté, qui lui donnent une assise juridique justifiant la possibilité pour l'autorité compétente de prendre les mesures consignées dans le dispositif (= l'ensemble des mesures). Ils s'expriment toujours en commençant par "Vu...". Il n'est pas obligatoire que les visas apparaissent systématiquement dans un arrêté (cf. https://www.collectivites-locales.gouv.fr/institutions/les-arretes-et-deliberations : "Les arrêtés municipaux ne sont applicables que sur le territoire de la commune. Ils concernent à la fois les habitants de la commune et toutes les personnes y résidant momentanément, même les étrangers de passage. Ils ne doivent respecter aucune forme déterminée. Il faut qu’ils soient écrits, datés et signés.") mais la structuration en trois parties ("Visas", "Considérant", "Dispositif") est fortement recommandée et adoptée par la très grande majorité des collectivités.

Les visas sont généralement placés en première position, avant les motifs et le dispositif (= l'ensemble des mesures). Ainsi on peut placer le champ correspondant au niveau de la première étape de saisie de l'arrêté. Ce champ est cependant assez long (on rédige généralement un visa par ligne, et il y a souvent plusieurs visas donc plusieurs lignes) et il pourrait donc être placé plus tard ou collapsé afin de ne pas gêner l'utilisateur dans la saisie d'autres informations.

Les visas peuvent être séparés en deux catégories (exemple d'Eudonet) : 

- Les références à des annexes légales généralement utilisées pour disposer des mesures du dispositif, par exemple issues du Code Général des Collectivités Territoriales (CGCT), du code de la route, du code pénal, d'autres codes, décrets ou arrêtés.
- Les références plus contextuelles à des documents internes ou non opposables, par exemple une délibération du conseil municipal.

On appellera par convention les premiers les "visas", les seconds des "visas complémentaires". 

En termes de format (type de données et taille), les champs des visas et visas complémentaires est semblable au champ des motifs. Le regroupement de ces champs (visas, visas complémentaires, motifs) dans un espace dédié de l'interface pourrait être envisagé (?)

**Comment by MathieuFV** [comment]
Pour mémoire l'analyse de Florimond sur les champs "motifs" et "visas" dans Eudonet :

Motifs
Ce sont des fiches contenant un texte libre. Ils sont liés à la fiche arrêté.

Annexes ("Visas")
Dans Eudonet, les annexes sont appelés "Visas". Les "annexes" pour Eudonet sont des fichiers joints (PDF, Word).

Il y a :

Visas :

Ça semble correspondre aux annexes légales généralement invoqué pour tel ou tel type de mesure
Constitué d'un type de mesure (ex : circulation interdite), d'une liste (text libre) d'articles du CGCT (Code général des collectivités territoriales) et d'une liste (texte libre) d'articles du Code de la route
Exemple : Mesure = "135 - circulation interdite", article CGCT = "L. 2213-1 ; L. 2213-2 ; L. 2512-14", article du code de la route = "R. 411-25 ; R. 411-8"
Ça pourrait faire office de "bibliothèque", sauf que les visas ne sont pas directement reliés à d'autres fiches. Par conséquent je ne suis pas sûr de comment ils sont utilisés par le système Eudonet. Ajout automatique lors de la génération en fonction des mesures en présence ? À clarifier.
Il semble y avoir beaucoup de quasi-duplication. Les visas d'un même type de mesure ont souvent les mêmes articles, mais pas toujours. J'imagine que cela correspond à des changements dans la loi : il faut référencer tel ou tel article en plus. Le visa le plus ancien dte de 2017, le plus récent date de 2021.
Visas complémentaires :

Reliés à un arrêté
Ce sont des "Vu" spécifiques à un contexte, par exemple "Vu la délibération du conseil municipal de telle date..."

**Comment by johanricher** [comment]
Est-ce qu'on a des exemples d'arrêtés avec des visas et qui illustrent la distinction avec les motifs spécifiés dans #354  (qu'on devrait appeler appelés "considérants" si l'on suit [la terminologie de la DGCL](https://www.collectivites-locales.gouv.fr/institutions/les-arretes-et-deliberations).

**Comment by MathieuFV** [comment]
Oui ! En réalité presque tous les arrêtés peuvent servir d'illustration pour cela. Voici un exemple intéressant : 

**Dans l'arrêté municipal de la Ville de Wissous (AG-08-015) nous trouvons :** 

Trois annexes : 

Vu le code général des collectivités territoriales et notamment les article L2213-1 à L2213-6,
Vu le code de la route,
Vu le code pénal et notamment l'article R610-5 relatif à la circulation.

Et un motif : 

Considérant l'infrastructure routière de la rue André Thierry, située dans une zone résidentielle.

Ainsi les visas ou annexes désignent la **base légale** sur laquelle la ville de Wissous s'appuie pour arrêter les restrictions de circulation et les sanctions applicables aux contrevenants, tandis que le motif désigne la raison pour laquelle la ville apporte des modifications à la réglementation routière.

S'agissant des annexes, on peut remarquer : 

- Un appel au CGCT pour les articles spécifiques L2213-1 au L2213-6 : Ces articles appartiennent au chapitre III "Pouvoirs de police portant sur des objets particuliers", du titre Ier ("Police"), du livre II ("Administration et services communaux"), de la deuxième partie ("La commune") de la partie législative (articles en LXXXX) du CGCT. Ces articles définissent les pouvoirs du maire quant aux restrictions de circulation qu'il a droit d'appliquer aux voiries qu'il administre.
- Un appel au code de la route, en entier ici pour éviter les erreurs mais on peut trouver des appels à des articles spécifiques. On trouvera souvent par exemple le L411-6 qui stipule que seule l'autorité en charge de la voirie a droit de placer de la signalisation sur la route.
- Au code pénal article R610-5 qui précise que la violation des dispositions de l'arrêté seront punies par une contravention de la 2ème classe.

=> L'ensemble de ces articles garantit que les dispositions de l'arrêté sont légales, i.e très concrètement qu'un avocat ne pourra pas tirer un chauffeur peu scrupuleux d'affaire en attaquant la légalité de l'arrêté, par exemple :)

Le motif est pour sa part libre de toutes contraintes rédactionnelles, mais généralement il s'agit d'une phrase unique assez courte expliquant la raison pour laquelle l'autorité arrête de nouvelles restrictions.

[015-2008-Circ-Stat-Andre-Thierry.pdf](https://github.com/MTES-MCT/dialog/files/12213544/015-2008-Circ-Stat-Andre-Thierry.pdf)

**Comment by johanricher** [comment]
Remplacé par #557
