### ISSUE TITLE
Problème au moment de la validation lorsque les numéros de rue ne sont pas reconnus

### ISSUE THREAD

**Issue by mmarchois** [MTES-MCT/dialog#367]
## Problème
Je rentre une voie et des numéros, mais je ne peux pas valider, j’ai une erreur :

![image](https://github.com/MTES-MCT/dialog/assets/2683379/7245851a-6198-45fe-b9f7-a9bce373ad23)

## Solutions

- Valider les numéros au moment où on les entre
- Afficher un message d’erreur plus clair :  “Cette adresse n’est pas reconnue. Vérifier le nom de la voie, et les numéros de début et fin.”

**Autres petits ajustements :**
- Est-il possible de diminuer un peu la taille du H4 (Restriction) pour qu’il y ait plus de différence avec le H3 ?
- Pour éviter de surcharger l’interface, il faudrait supprimer la petite phrase en dessous du label Type de restriction : “Quel type de restriction…”
![image](https://github.com/MTES-MCT/dialog/assets/2683379/77f93040-7e30-4999-8dd6-bb11598955f1)

Le champ “Créneaux horaires” n’est pas obligatoire, il faut donc retirer l’asterisque
![image](https://github.com/MTES-MCT/dialog/assets/2683379/a6babba7-2b81-4a36-a69d-4798caa44638)

- Créneaux horaires
Pour éviter la confusion avec le bouton “Ajouter une restriction”, on peut utiliser l’icone de calendrier au lieu du + comme sur les maquettes :

![image](https://github.com/MTES-MCT/dialog/assets/2683379/d4b5d9d8-fab1-444c-ae29-188a3cde0b33)

**Comment by mmarchois** [comment]
@aureliebaton @astranchet 
> Valider les numéros au moment où on les entre
Je me demande si, avec un message plus clair comme celui que tu as mis, ce ne serait pas suffisant (dans un premier temps) ?
Sinon, tous les autres points remontés ont été corrigés. Disponible en recette ici : https://dialog-staging-pr368.osc-fr1.scalingo.io/ 

J'attendrai votre GO avant de mep.

**Comment by aureliebaton** [comment]
Oui je me suis posée la question aussi, mais l'autre problème c'était notamment qu'au début je n'avais pas vu le message d'erreur car il était tout en haut de la page et non visible au moment de la validation (j'ai dû scroller pour voir s'il y avait un problème). Donc si on laisse comme ça, il faudrait le message d'erreur à 2 endroits : en haut près du champ et en bas près du bouton Valider. 
T'en penses quoi toi @astranchet ?

Super pour les autres points, je regarderai ça !

**Comment by mmarchois** [comment]
Je suis d'accord avec toi, mais se pose la question de l'affichage des erreurs dans sa globalité.
On va retrouver le même problème sur n'importe quel champ. Si tu as une erreur, par ex, sur les jours applicables d'une restriction et que tu dois scroller x restrictions pour valider, tu ne verras pas tout de suite ton message.

**Comment by astranchet** [comment]
Effectivement, je pense qu'on a pas assez abouti les messages d'erreurs. Généralement, je propose quelque chose avec 2 indicateurs : 
- Une information au niveau "global"
- Une information au niveau du champ
Et habituellement, je propose que le champ validé revienne en haut de page (pour donner du feedback que l'action de validation a bien eu lieue). Mais ici, je pense que ça serait plus judicieux de retomber un poil plus bas puisque le haut de la page est déjà "validé"

Ça donnerait quelque chose comme ça : 
Après validation, si erreur, on verrait : 
![image](https://github.com/MTES-MCT/dialog/assets/1374389/9b1f0fc4-5a3e-4a14-a25a-608742bf38d7)

Est-ce que tu veux qu'on prenne le temps de maquetter différents cas avec @aureliebaton ?

**Comment by mmarchois** [comment]
Dans ce cas-là, je propose de clore ce ticket (les autres points ont été traités) puis d'en créer un autre spécifiquement lié aux messages d'erreurs.
