### ISSUE TITLE
Les champs de dates sont peu pratiques

### ISSUE THREAD

**Issue by mmarchois** [MTES-MCT/dialog#371]
## Problème
 Les champs de dates sont trop larges, et si l’utilisateur clique dans le champ rien ne se passe. Il faut aller tout à droite et cliquer sur la bonne icone.

![image](https://github.com/MTES-MCT/dialog/assets/2683379/c7da234f-6e5f-43ba-8b07-4c53f74359d0)

## Solution

- Pouvoir activer le calendrier en cliquant dans le champs
- Réduire la taille des champs pour que les icônes soient plus proches
- Retirer la double icone (mais probablement lié au DSFR)

![image](https://github.com/MTES-MCT/dialog/assets/2683379/f5cd8b52-7b0a-47b3-bbd5-0d06f1d53693)

**Comment by florimondmanca** [comment]
> Retirer la double icone (mais probablement lié au DSFR)

C'est un problème sous Firefox version 109+ : https://stackoverflow.com/questions/75855800/how-to-style-an-date-inputs-calendar-icon-in-firefox-108

Un ticket est ouvert côté DSFR : https://github.com/GouvernementFR/dsfr/issues/411

On l'avait déjà lié à ce ticket : https://github.com/MTES-MCT/dialog/issues/113#issuecomment-1411841407

Sous Chromium et les anciens Firefox, on pouvait cibler le picker avec `::-webkit-calendar-picker-indicator` pour en modifier les styles.

Par ex on peut cacher l'icône par défaut et étendre la zone du picker-indicator à tout l'input, ce qui permet d'ailleurs d'ouvrir le picker si on clique n'importe où sur l'input : https://stackoverflow.com/a/51349612
