### ISSUE TITLE
Affichage des véhicules concernés

### ISSUE THREAD

**Issue by florimondmanca** [MTES-MCT/dialog#375]
## User story

* ETQ utilisateur je consulte les véhicules concernés par une mesure afin de savoir s'il y a lieu de les modifier

## Critères d'acceptation

- [ ] _(Must have)_ Les véhicules concernés par chaque mesure apparaissent dans la vue "lecture" de l'arrêté

## Design

La [maquette](https://www.figma.com/file/YuT6Uh4wxe90U8LaPLlDzO/Dialog?type=design&node-id=6-2&t=20nlkpxhGaXibmX3-0) suggère d'indiquer les véhicules concernés dans le tiret de la mesure

Elle montre pour l'instant les cas suivants :

* Tous les véhicules
* Pour les poids lourds

## Implémentation

* Modifier le `_location.html.twig`, de la même façon que pour l'affichage des périodes (#359) 

## Contexte supplémentaire

Fait suite à #358 qui a ajouté la possibilité d'éditer les véhicules concernés

**Comment by florimondmanca** [comment]
@aureliebaton @astranchet J'essaie d'imaginer comment formater les véhicules concernés

Je pensais partir sur ce template :

> Circulation interdite pour les VÉHICULES CONCERNÉS [, sauf VEHICULES EXEMPTÉS]

Exemples :

* Circulation interdite pour tous les véhicules
* Circulation interdite pour les poids lourds, sauf bus
* Circulation interdite pour tous les véhicules, sauf piétons, ambulances et vélos

J'ai cru comprendre que vous réfléchissiez à une autre solution pour l'affichage suite aux discussions sur les périodes

Est-ce qu'on partirait néanmoins sur un affichage textuel de cette forme (quitte à ce que ça soit sur d'autres bullet points) ?

**Comment by aureliebaton** [comment]
Effectivement, je pense qu'on peut rester sur le format textuel. Il faudra peut-être simplement mettre des sous-titres ou autre, mais ta suggestion me semble pertinente dans tous les cas.
