### ISSUE TITLE
Analyse des erreurs remontées par Sentry

### ISSUE THREAD

**Issue by mmarchois** [MTES-MCT/dialog#392]
![image](https://github.com/MTES-MCT/dialog/assets/2683379/ce9be0de-0dd3-4d6a-bfb0-6d7dde35a196)

**Comment by mmarchois** [comment]
@florimondmanca Je n'arrive pas à avoir accès au Sentry (problème de double auth). Arrives-tu à te connecter dessus toi ?

**Comment by florimondmanca** [comment]
@mmarchois Oui j'ai réussi à me connecter

**Comment by florimondmanca** [comment]
@mmarchois Apparemment tu peux demander à Tristan de "reset two-factor authentication" (je suis simple membre donc je n'ai pas les droits)

![Screenshot 2023-06-27 at 11-37-51 Sentry](https://github.com/MTES-MCT/dialog/assets/15911462/cca226fa-f9d8-42d5-9e93-2bdd6c962bc2)

**Comment by florimondmanca** [comment]
Il y a pas mal d'erreurs qui semblent liées à Redis aussi.

![Screenshot 2023-06-27 at 11-45-11 Issues - betagouv - Sentry](https://github.com/MTES-MCT/dialog/assets/15911462/ef0a4e62-bfdf-4450-8163-b620ea4cb5f1)

**Comment by mmarchois** [comment]
Tu peux les resolve celle-ci, c'était hier au moment du déploiement en prod, l'authentification n'avait pas été configurée.
