### ISSUE TITLE
Créneaux horaires dans l'export DATEX II

### ISSUE THREAD

**Issue by florimondmanca** [MTES-MCT/dialog#435]
## Comportement attendu

Quand on ajoute des créneaux horaires à une mesure, ils devraient appraître dans l'export DATEX II

## Comportement réel

Les créneaux horaires n'apparaissent pas

## Pour reproduire

- Vérifier que https://dialog.incubateur.net/regulations/01898e05-0621-74c6-9b56-36ff4a1052a9 a des créneaux horaires : "Circulation interdite le jeudi de 12h00 à 20h00, le samedi de 12h00 à 20h00 pour tous les véhicules " sur l'avenue Jean Moulin
- Dans https://dialog.incubateur.net/api/regulations.xml, constater que pour l'élément `trafficRegulation` qui concerne cette mesure, rien ne mentionne qu'elle n'est applicable que "le jeudi de 12h00 à 20h00" et "le samedi de 12h00 à 20h00"

## Pistes de résolution

TODO

Comment représenter les créneaux horaires dans DATEX II ? Retourner voir le système de `Period` avec les `applicableDays` etc.

## Contexte

On avait délaissé l'export DATEX II pendant tout un moment, pour avancer uniquement sur la partie interface de saisie, ce qui a accumulé la dette technique. Malheureusement on en vient à en payer le prix maintenant que la perspective de collaborer avec des GPS se concrétise.

**Comment by florimondmanca** [comment]
@johanricher Je ne sais pas quelle priorité on pourrait donner à ça.

Contrairement à #434, ce n'est pas vraiment un "(quick) fix" mais bien une sorte de nouveauté (affichage des créneaux horaires dans l'export DATEX).

On a possiblement un sujet plus large "exhaustivité / cohérence de l'export DATEX vis à vis des données structurées stockées dans DiaLog".

Quelques autres sujets que j'ai repérés :

* Toutes les mesures sont émises comme si c'était des interdictions de circulation (`noEntry` codé en dur dans l'export). Or on a plusieurs types : Sens unique, Limitation de vitesse, Circulation alternée.
* Sauf que... Le type de mesure "Limitation de vitesse" est incomplet : il manque la possibilité de définir la vitesse. Or c'est une valeur obligatoire pour définir une `SpeedLimit` dans DATEX II.

**Comment by johanricher** [comment]
Pour moi la priorité c'est d'engager le plus tôt possible une discussion avec un fournisseur de service de navigation (GPS) de telle façon à passer de la théorie (on a des données) à la pratique (elles sont utilisées). J'ai l'espoir que #425 permette d'enclencher ça donc la priorité absolue c'est le fichier Datex. L'application elle-même devra suivre en fonction des échanges techniques avec au moins un GPS. C'est à partir de ça qu'on pourra voir quelle sont les priorités selon moi.
Le fait que l'application soit en retard sur Datex n'est pas un problème en soi. On sait qu'implémenter Datex à 100 % sera très laborieux, et on sait aussi que ça ne sert à rien si seulement une partie a été implémentée par les GPS eux-mêmes, ou d'une façon qui diffère (cf. #3).

**Comment by johanricher** [comment]
Est-ce que tous les horaires implémentés dans le cadre de #455 sont tous exposés aujourd'hui en Datex II ? @mmarchois @florimondmanca

**Comment by florimondmanca** [comment]
@johanricher Non

**Comment by johanricher** [comment]
Ce ticket est antérieur à #455. Il me semblait que l'export Datex avait fait partie du chantier des horaires. @mmarchois J'ai mal compris ?
