### ISSUE TITLE
En tant que contributeur je veux définir le type de transport concerné afin de passer ce paramètre aux GPS

### ISSUE THREAD

**Issue by MathieuFV** [MTES-MCT/dialog#45]

**Comment by florimondmanca** [comment]
@mathieuFV Si j'ai bien compris, il s'agit ici des types de transport comme "Bus", "Camion citerne", etc ?

La partie usage ("transport de marchandises" (véhicule affecté au)) est déjà répertoriée dans #44

Pour l'instant le type de transport n'est pas dans la maquette

@astranchet La liste de codes de carte grise que tu as trouvée correspondrait plutôt au type de véhicules ? Et la codification DATEX est plutôt pour l'usage (et donc #44)
