### ISSUE TITLE
En tant que contributeur je veux modifier la plage de validité d'une réglementation afin de la prolonger

### ISSUE THREAD

**Issue by MathieuFV** [MTES-MCT/dialog#46]

**Comment by florimondmanca** [comment]
Il y aura une partie (la modification "brute") dans #79, qui permet de modifier une réglementation.

À voir si on souhaite plus d'enrobage : garder un historique de modifications, par ex.

**Comment by florimondmanca** [comment]
Normalement ce sujet est traité pour les brouillons, il est possible de modifier les dates et heures de début ou de fin sur une réglementation en brouillon.

Est-ce qu'il y avait une attente particulière pour les réglementations publiées ?

Si on n'est pas sûrs, je pense qu'on peut fermer cette epic.

**Comment by mmarchois** [comment]
Je pense qu'effectivement, on peut clôturer ce sujet.
