### ISSUE TITLE
Liste des éléments à modifier dans la landing page

### ISSUE THREAD

**Issue by Lealefoulon** [MTES-MCT/dialog#470]
# Liste des éléments à modifier dans la landing page

- Utiliser title-grey ou default-grey et pas le "mention-grey"
- Spécifier les meta tilte : 
    Pour l'accueil, ça devrait être "DiaLog"
    "Collectivités - DiaLog"
    "Services numériques - DiaLog"
    "Usagers - DiaLog"

## Sur la page d'accueil :

- Dans le titre de la page d'accueil bien veiller à écrire DiaLog avec un L majuscule.
- Ecrire "Mettre en oeuvre les ZFE" plutôt que "Promouvoir"
- Dans le comment ça marche écrire "Ces données sont ensuite transmises aux services numériques" plutôt que "publiées"
Enlever le "s" aux données de circulations

## Dans la landing collectivités : 

- Enlever le nom de Sogelink sous "Gagnez du temps" (pour éviter de faire de la pub).

## Dans la landing services numérique :

- sous "Des données qualitatives" dans "Au bon format" enlever le s à intégrables
Dans l'encart gris en dessous mettre le L en majuscule à DiaLog

## Dans la landing usagers de la route :

Ajouter des petites images qui représentent chaque type de route dans "Comment sont gérées les routes en France ?", @MathieuFV  pourrait les fournir à partir de la médiathèque du ministère

## Design

https://www.figma.com/file/YuT6Uh4wxe90U8LaPLlDzO/Dialog?type=design&node-id=6-2&mode=design&t=FByn2lfaDNK6V45j-0

**Comment by florimondmanca** [comment]
Ça a été résolué par #471 c'est ça ?

**Comment by aureliebaton** [comment]
En ce qui me concerne c'est ok, les remarques que j'avais faites ont été prises en compte. Je laisse @astranchet faire la dernière validation comme c'est elle qui a bossé dessus.

**Comment by astranchet** [comment]
Parfait pour moi ! Il reste juste les histoires des petites icônes mais on ne les a pas encore. Pour moi, ça n'est pas bloquant

**Comment by florimondmanca** [comment]
Ok, merci !

**Comment by johanricher** [comment]
Il manque pas ce texte sur la page Usagers ?

![image](https://github.com/MTES-MCT/dialog/assets/10212787/88fb835e-9c04-475e-895e-bbfbb9f05e90)

**Comment by MathieuFV** [comment]
Oui, pour l'instant je vois l'ancienne version. Peut-être déjà prêt dans la prochaine màj ?
