### ISSUE TITLE
Bug sur l'affichage lorsqu'il n'y a pas d'arrêtés

### ISSUE THREAD

**Issue by mmarchois** [MTES-MCT/dialog#483]
![image](https://github.com/MTES-MCT/dialog/assets/2683379/533839c4-e250-45e2-897a-3ff85ffcae91)

**Comment by florimondmanca** [comment]
@mmarchois Tu as bien fait un `make assets` ?

Je ne constate pas ce pb sur staging

https://dialog.incubateur.net/regulations?tab=permanent
