### ISSUE TITLE
Validation de l'export DATEX II

### ISSUE THREAD

**Issue by florimondmanca** [MTES-MCT/dialog#486]
## Problème

L'export DATEX II est sensé être conforme au DATEX II, c'est-à-dire être un document XML valide et conforme à la spécification DATEX II, représentée par les fichiers XSD.

Actuellement aucune validation n'est en place pour s'en assurer.

La création du XML se fait à partir d'un fichier Twig où nous n'avons même pas de retour visuel dans l'éditeur de texte sur la validité ou non du XML qui sera produit.

Il est donc très facile, si on n'y prend pas garde, de produire un XML non-conforme au DATEX II.

## User story

ETQ membre de l'équipe de dev, je suis empêché de mettre en production si l'export DATEX II n'est pas valide afin de garantir la conformité de l'export au DATEX II

## Critères d'acceptation

- [ ] Les tests échouent si l'export DATEX II lors des tests n'est pas valide

## Design

N/A

## Implémentation

Pistes

* Quels validateurs XML/XSD existent dans l'écosystème PHP /Symfony ?

**Comment by johanricher** [comment]
Il me semble qu'un validateur est en soi une implémentation de la spec. Est ce qu'une implémentation canonique (officielle, source de vérité) existe pour valider la conformité d'un fichier au format Datex II ?

(de la même façon que [la spec GTFS static](https://developers.google.com/transit/gtfs) a [un validateur canonique](https://github.com/MobilityData/gtfs-validator))

Comment on sait sur quelle version de la spec Datex II on vérifie la validité de fichier `regulations.xml` de DiaLog ? et corollaire : Comment on gère le versionnement de la spec (et donc du validateur) ?

**Comment by florimondmanca** [comment]
@johanricher Oui la conformité peut être vérifiée à l'aide des fichiers XSD (définition des schémas XML) : https://github.com/MTES-MCT/dialog/blob/0a9afc994f14a48d6fcfd20225b7dbbb036665ac/docs/spec/datex2

Dans #487 c'est ce que j'utilise pour faire la vérification dans les tests unitaires

Ça semble suffisant

Ces fichiers proviennent du Webtool DATEX II comme expliqué dans notre doc : https://github.com/MTES-MCT/dialog/blob/main/docs/tutorials/datex2.md#obtenir-les-sch%C3%A9mas-xsd

Comme indiqué dans DATEXII_3_D2Payload.xsd pour l'instant on est en 3.3

Le versionage se fait donc via ces fichiers stockés dans git

Si on veut "passer à la 3.4" (ou une autre version ultérieurement) on téléchargerait les nouveaux fichiers, on les met dans Git, de là on voit ce qui a changé grâce au diff, et on peut faire les modifications nécessaires le cas échéant
