### ISSUE TITLE
Page mentions légales

### ISSUE THREAD

**Issue by johanricher** [MTES-MCT/dialog#488]
C'est une obligation légale.

# Tâches

- [x] Ecrire le contenu : https://pad.incubateur.net/YNRgAwnKR6K9DQfeSOLBIQ
- [x] Implémenter le contenu dans une nouvelle page `dialog.beta.gouv.fr/mentions-legales`
- [x] Ajouter lien dans le footer
- [x] En profiter pour ajouter un lien "Code source" dans le footer qui pointe vers `https://github.com/MTES-MCT/dialog`

**Comment by johanricher** [comment]
@MathieuFV Première version de la page disponible pour relecture. Une fois finalisée cette page pourra être implémentée selon en fonction des priorités lors d'une prochaine itération.

**Comment by florimondmanca** [comment]
J'ai précisé l'hébergeur (Scalingo) et sa domiciliation

**Comment by johanricher** [comment]
@aureliebaton @astranchet Il faudrait ajouter les différentes ressources (icones, visuels) et leur licence d'utilisation dans les crédits.

**Comment by aureliebaton** [comment]
J'ai ajouté les crédits illustrations et icones dans le pad.

**Comment by johanricher** [comment]
Top, merci ! Storyset n'est pas sous licence libre mais [les CGU](https://storyset.com/terms) ("6. Licence Agreement for Storyset Content") m'ont l'air compatible avec notre usage (j'avoue ne pas avoir vérifié en détail).

Je laisse @MathieuFV relire et valider avant qu'on mette ce ticket en "Prêt à développer".

**Comment by MathieuFV** [comment]
Hello, après relecture j'ai corrigé le nom du directeur général qui est Rodolphe Gintz depuis le début de l'année. Autrement je n'ai pas de remarques. Merci à tous !

**Comment by aureliebaton** [comment]
@johanricher effectivement j'ai regardé aussi les CGU et tout me semblait OK, c'est juste qu'il faut c'est spécifier l'utilisation de Freepik, ce qu'on fait ici.
J'ai aussi regardé dans les mentions légales de beta.gouv https://beta.gouv.fr/apropos/, ils disent juste : "Illustrations des pages accueil (section équipe) et FAST : Freepik. Toute autre illustration : beta.gouv.fr"

**Comment by florimondmanca** [comment]
@johanricher J'ai vu que tu as réouvert ce ticket

La PR a été mergée et elle permet de cocher toutes les cases des critères d'acceptation du ticket

Y a-t-il d'autres choses à faire ?

Je remarque que https://dialog.incubateur.net affiche la page mentions légales, mais pas https://dialog.beta.gouv.fr... Je relance le déploiement au cas où

**Comment by johanricher** [comment]
Oui comme je n'ai pas pu tester en prod ("recette" dans notre process), c'était pour me faire penser à le faire plus tard. :+1:  :)
