### ISSUE TITLE
Affinage de l'affichage PL et catégories Crit'Air

### ISSUE THREAD

**Issue by florimondmanca** [MTES-MCT/dialog#492]
## Comportement actuel

L'affichage est du type :

> Circulation interdite tous les jours pour les poids lourds de plus de 3.5 tonnes, crit'air 4, crit'air 5 et crit'air 3

## Comportement attendu

* Le poids max et gabarit des poids lourds devrait utiliser le format français "3,5" (avec une virgule), et non le format anglais "3.5" (point)
* Les catégories Crit'Air devraient être regroupées, triées dans l'ordre croissant (actuellement c'est par ordre d'édition)
* Ecrire "Crit'Air" (majuscules) et pas "crit'air"

Nouvel affichage attendu :

> Circulation interdite tous les jours pour les poids lourds de plus de 3,5 tonnes et véhicules Crit'Air 3, 4 et 5

## Contexte supplémentaire

Voir [discussion Figma](https://www.figma.com/file/YuT6Uh4wxe90U8LaPLlDzO?node-id=2367:137066&mode=design#553141196)

**Comment by johanricher** [comment]
@aureliebaton Est-ce que ce ticket est toujours d'actualité selon toi ?

**Comment by florimondmanca** [comment]
Comme vu en réunion la dernière fois, oui tous les petits détails qui sont indiqués ici sont encore d'actualité
