### ISSUE TITLE
Intégration DSFR

### ISSUE THREAD

**Issue by florimondmanca** [MTES-MCT/dialog#51]
Suggéré par https://github.com/MTES-MCT/dialog/issues/41#issuecomment-1330771941

Nous allons utiliser le [DSFR](https://www.systeme-de-design.gouv.fr/) (Système de design de l'Etat) pour DiaLog.

Le site "vide" actuel https://dialog.beta.gouv.fr pourrait d'ores et déjà être porté sous

**UI**

* Header : logo "République française" + titre DiaLog + sous-titre "Digitaliser, diagnostiquer et diffuser la réglementation de circulation"

**Implémentation**

Voir https://www.systeme-de-design.gouv.fr/comment-utiliser-le-dsfr/developpeurs/prise-en-main-du-dsfr

Le DSFR peut être utilisé soit sous forme d'un CSS minifié tout-en-un, soit en incluant ses "composants" (header, boutons, liens, tabs, tags, etc) un à un.

**Comment by mmarchois** [comment]
@MathieuFV @astranchet prêt pour une recette ici : https://dialog-staging-pr56.osc-fr1.scalingo.io/.
Le nom d'utilisateur est `dialog`, le mot de passe est le même que celui utilisé en production.
