### ISSUE TITLE
DATEX2 : coordonnées GPS manquantes pour une rue complète

### ISSUE THREAD

**Issue by florimondmanca** [MTES-MCT/dialog#512]
## Critères d'acceptation

- [ ] _(Must have)_ Critère 1
- [ ] _(Nice to have)_ Critère 2

**Comment by johanricher** [comment]
Est-ce que ce ticket est toujours d'actualité @florimondmanca ?

**Comment by florimondmanca** [comment]
Non, ça avait été résolu par #536
