### ISSUE TITLE
Restriction de circulation avec plusieurs localisations

### ISSUE THREAD

**Issue by johanricher** [MTES-MCT/dialog#522]
## Contexte

Certains arrêtés portent sur des restrictions de circulations qui concernent plusieurs localisations, par exemple plusieurs voies (#518) et/ou plusieurs zones (#519).

L'UI de DiaLog permet actuellement de créer et publier un arrêté avec une restriction définie sur une seule localisation.

## Exemple

![image](https://github.com/MTES-MCT/dialog/assets/10212787/3bf9e2fa-550b-46db-bb0b-d1dd5ac79f2d)

Extrait d'un arrêté municipal où est définie une "[zone 30](https://fr.wikipedia.org/wiki/Zone_30)" en listant différentes voies où une restriction est appliquée (vitesse des véhicules limitée à 30 km/h, cf. dispositions générales du [décret zone 30](https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000019274295).

## Critères d'acceptation

* (Must have) Je peux définir une restriction de circulation sur plusieurs localisations avec l'interface de DiaLog.
* (Must have) On peut intégrer dans DiaLog des données avec des restrictions définies sur plusieurs localisations.
* (Must have) Les restrictions de circulation, créées ou intégrées dans DiaLog, et définies sur plusieurs localisations, sont servies par l'API Dialog en Datex II.
* (Must have) Les restrictions de circulation, créées ou intégrées dans DiaLog, et définies sur plusieurs localisations, sont servies par l'API Dialog en CIFS.

## Implémentation

Cette fonctionnalité dépend à priori au préalable de la gestion correcte par DiaLog des 2 types de localisations (voies #424 et zones #519).

Liste non-exhaustive des problèmes à explorer avant de décider de l'implémentation :
* UX ?
* Evolution de [notre modèle de données](https://github.com/MTES-MCT/dialog/blob/main/docs/adr/002_mcd.md) ?

**Comment by florimondmanca** [comment]
> Evolution de [notre modèle de données](https://github.com/MTES-MCT/dialog/blob/main/docs/adr/002_mcd.md) ?

Il faudrait procéder à la fameuse "inversion" dont on avait parlé à l'atelier du 21 septembre

Actuellement on stocke : "une localisation A une ou plusieurs restrictions"

Il faudrait aller vers : "Une restriction A une ou plusieurs localisations"

La chose à valider c'est : fait-il _aussi_ sens de faciliter le cas d'usage "plusieurs restrictions sur une localisation", ou est-ce qu'en pratique les articles des arrêtés sont par restriction et pas par localisation ? cc @aureliebaton

**Comment by aureliebaton** [comment]
A la base le modèle partait d'un localisation avec 1 ou plusieurs restrictions pour couvrir cartains cas d'usage tels que :
* Rue de la République : 
* la vitesse est limitée à 30
* la circulation est interdite aux poids lourds
* le stationnament est interdit

Dans un sens ou dans l'autre (si on part des restrictions) on aura des cas compliqués.
L'objectif est de trouver la solution la moins "pire" ;-)

**Comment by johanricher** [comment]
@florimondmanca 

Je suis d'accord sur le fait qu'il faudrait probablement aller vers une entrée par l'objet "restriction", qui de mon point de vue devrait être central dans notre modèle de données et UI/UX. De ce que j'ai vu, c'est le choix qui a été fait pour [l'éditeur Waze](https://www.waze.com/fr/editor).

C'est notamment pour nous aider dans ces réflexion que j'aimerais qu'on puisse étudier les UI/UX de BAC IDF et autres (Sogelink, etc.). @MathieuFV possible d'avoir des accès ou des démos ?

@aureliebaton 

> la vitesse est limitée à 30

C'est une restrition qui il me semble est définie uniquement par un arrêté permanent donc pas mélangé avec des dispositions temporaires (interdiction de circulation par exemple).

> le stationnament est interdit

Les arrêtés qui ont ces restrictions ne sont pour l'instant pas dans le périmètre de DiaLog car pas diffusables dans les services de navigation.

Est-ce qu'on a des exemples d'arrêtés qui définissent plusieurs restrictions de circulation pour une seule localisation ?

**Comment by MathieuFV** [comment]
Pour info : https://dialog.beta.gouv.fr/regulations/69618570-ef1b-4e47-9532-80fe57a1c597

Cas d'un arrêté ayant la même restriction sur plusieurs localisations

**Comment by johanricher** [comment]
Encore en question : comment le modèle de données doit évoluer ? est-ce qu'évoluer vers la possibilité d'avoir plusieurs restrictions sur une localisation est nécessaire ? inverser restriction / localisation ?

**Comment by florimondmanca** [comment]
A-t-on ou un des exemples d'arrêtés avec un article qui définit plusieurs restrictions sur plusieurs localisations identiques ?

**Comment by MathieuFV** [comment]
@aureliebaton a trouvé les arrêtés suivants : 

https://kdrive.infomaniak.com/app/drive/184671/shared-with-me/184671/25462/preview/pdf/25463
https://kdrive.infomaniak.com/app/drive/184671/shared-with-me/184671/25219/preview/image/25221

On y voit dans un article unique la définition de plusieurs restrictions sur une même localisation.

Les deux paradigmes semblent donc exister : Une localisation et plusieurs restrictions OU une restriction et plusieurs localisations.

**CCL :** 

1. L'arrêté contient un dispositif, qui est l'ensemble des mesures (remplacer "Localisations" par "Dispositif" dans l'écran d'édition des arrêtés).
2. Inversion entre restrictions et localisations : Le titre du bloc devient la restriction, on peut ajouter plusieurs localisations à une restriction. La mesure = l'ensemble restriction + localisations.
3. Possibilité de dupliquer une mesure.

Autre exemple de multi localisations pour la même restrictions dans DiaLog : https://dialog.beta.gouv.fr/regulations/018b6c90-02a7-75a7-a6c6-ceb7ccca9cbd

**Impacts :** 

- Liste des arrêtés
- Page affichage et d'édition des arrêtés
- Duplication globale de l'arrêté
- Publication de l'arrêté
- Modèle de données
- Migration de données
- Export DATEX
- Export Word
- Design

**Comment by florimondmanca** [comment]
J'ajoute aux impacts : intégration Eudonet

**Comment by MathieuFV** [comment]
Je ferme le ticket car remplacé et mis à jour dans #577

**Comment by johanricher** [comment]
> https://kdrive.infomaniak.com/app/drive/184671/shared-with-me/184671/25462/preview/pdf/25463
> https://kdrive.infomaniak.com/app/drive/184671/shared-with-me/184671/25219/preview/image/25221
> 
> On y voit dans un article unique la définition de plusieurs restrictions sur une même localisation.

J'ai du louper quelque chose dans ces 2 arrêtés. Il me semble que définir "plusieurs restrictions sur une même localisation" est déjà possible actuellement avec DiaLog :

Par exemple :
* Localisation : avenue de Ségur à Paris
  * Restriction 1 : vitesse limitée à 30 kms pour tous les véhicules
  * Restriction 2 : circulation interdite aux poids lourds

Screenshot après validation ;
![image](https://github.com/MTES-MCT/dialog/assets/10212787/ed7cd99f-3851-4f00-8b33-b93cd826c4e6)
[Screenshot en mode édition](https://github.com/MTES-MCT/dialog/assets/10212787/40f53eff-1220-4cf4-bf6b-9c25ae98011f)
  
Ce que je ne peux pas faire c'est par exemple le cas suivant :
* Localisation
  * 1: avenue de Ségur à Paris
  * 2 : rue d'Estrées à Paris
  * Restriction : circulation interdite à tous les véhicules
  
C'est à dire "plusieurs localisations pour une restriction". C'est l'objet de ce ticket, avec l'arrêté donné en exemple.

Ce que je préciserais cependant après réflexion : d'un point de vue utilisateur (UI / UX), il s'agit d'une seule "localisation" (à laquelle est attachée une ou plusieurs restrictions comme actuellement).
En effet, comme dans l'arrêté en exemple, l'utilisateur va souhaiter définir une "zone", un périmètre, donc une "localisation", où s'applique une ou plusieurs restrictions. Et sur une visualisation cartographique ce périmètre, cette "localisation", serait représentée par une ou plusieurs lignes et/ou une plusieurs polygones, mais qui visuellement forment une unité où s'applique la restriction définie. Du côté des données je ne sais si cela serait compatible avec les modèles Datex II, CIFS et autres.

Concernant la discussion sur le vocabulaire ("dispositif", "mesure", "restriction", "localisation"...), elle est je pense orthogonale au sujet et au besoin des utilisateurs adressés par ce ticket.

**Comment by florimondmanca** [comment]
@johanricher Ce que tu écris (même la "présentation UX" où la liste de rues représente "une seule localisation") est compatible avec #577 sauf ce point d'ambigüité

> où s'applique la ou les restrictions

Ce qu'il faut trancher, et ce qui pourrait sinon être un "facteur dynamique créneaux", c'est si on part sur

* (A) UNE restriction s'appliquant sur PLUSIEURS localisations
* ou bien
* (B) UN "dispositif" (ou autre entité englobante) = PLUSIEURS restrictions s'appliquant sur PLUSIEURS localisations

À l'issue de la journée de jeudi on envisageait plutôt (A), en gardant en tête que ça restreint l'utilisation pour un cas d'usage où j'ai _vraiment_ envie de mettre plusieurs mesures _exactement_ sur les mêmes localisations. Dans ce cas, on s'est dit que pouvoir dupliquer une mesure avec ses localisations serait suffisant.

**Comment by johanricher** [comment]
Intuitivement, il me semble que l'option B est plus en adéquation avec le monde réel.

En effet, du point de vue utilisateur, quand je circule avec mon véhicule, et tout particulièrement quand je le fais à l'aide d'un assistant à la navigation comme Waze, ce qui définit mon expérience c'est l'espace, c'est à dire le contexte dans lequel je circule et où je vais rencontrer des éléments qui restreignent ma circulation (interdiction, limitation de vitesse...). 

Le point d'entrée du modèle de données de DiaLog me paraît donc être la localisation.

D'ailleurs, le fait que DiaLog adopte une UI / UX carto pour devenir un jour un outil au moins aussi puissant et intuitif que [l'éditeur Waze](https://www.waze.com/fr/editor) semble être une évolution assez logique et qui fait il me semble consensus dans l'équipe. Dans ce paradigme, je sélectionne d'abord une localisation (ma définition étant : "une ou plusieurs lignes et/ou une ou plusieurs polygones") pour y appliquer une ou plusieurs restrictions.

Quoi qu'il en soit, de ce que je comprends, les 2 modèles que tu décris (1 restriction sur n localisation ; n restriction sur n localisation) pourront permettre de saisir tous les arrêtés. Et l'UI / UX seront des détails d'implémentation qui pourront s'adapter pour arriver au résultat qu'on veut, quel que soit le modèle.

Ce qui aiderait très certainement nos travaux cependant serait qu'on s'accorde sur le vocaculaire qu'on utilise et en particulier qu'on définisse ce qu'est une "localisation" dans le modèle qui est en train d'être (re)défini (ma proposition est ci-dessus). Si possible en s'appuyant sur le même vocabulaire que Datex II, ou bien sur un terrain intermédiaire propre à DiaLog, qui serait plus proche du langage commun des utilisateurs finaux (automobilistes) que celui des arrêtés (qui utilise le terme de "dispositif" ??).

@florimondmanca Si tu n'identifies dans ces réflexions rien qui bloque #577 et si ça reste le meilleur moyen pour avancer, ce ticket peut bel et bien être fermé. :slightly_smiling_face:

**Comment by florimondmanca** [comment]
@johanricher 

Selon moi rien ne bloque, non. Voir le **passage en gras** ci-dessous

> Quoi qu'il en soit, de ce que je comprends, les 2 modèles que tu décris (1 restriction sur n localisation ; n restriction sur n localisation) pourront permettre de saisir tous les arrêtés. Et l'UI / UX seront des détails d'implémentation qui pourront s'adapter pour arriver au résultat qu'on veut, quel que soit le modèle.

Oui, avec une moins grande complexité pour le "1 restriction sur n localisations (+ possibilité de dupliquer la restriction)" quand même.

> Si possible en s'appuyant sur le même vocabulaire que Datex II

Comme dit à l'oral jeudi, dans DATEX II le point d'entrée n'est pas la localisation mais la `trafficRegulation`, qu'on peut apparenter ce qu'on appelle actuellement "restriction" et qui est appelé dans #577 "mesure".

Dans DATEX II la `trafficRegulation` fait partie d'un `trafficRegulationOrder` (un "arrêté")

C'est un objet qui contient un `type` de réglementation (accès interdit, sens unique, limitation de vitesse...), et plusieurs "conditions".

Parmi ces conditions on trouve ce qui concerne le temporel (les `validity` correspondant à nos "périodes"), mais aussi le spatial : les `LocationCondition`.

L'approche de #577 serait donc "raccord DATEX II", ce qui minimiserait le travail de compatibilité.

> Dans ce paradigme, je sélectionne d'abord une localisation (ma définition étant : "une ou plusieurs lignes et/ou une ou plusieurs polygones") pour y appliquer une ou plusieurs restrictions.

Je n'ai pas regardé le détail de comment fonctionne l'éditeur Waze, mais on peut aussi imaginer une UX où je sélectionne une localisation, ou plusieurs, pour ensuite dire : voilà la mesure qu'il y a ici. Ensuite j'en sélectionne d'autres pour dire : voilà l'autre mesure qu'il y a là. Car si en fait les mesures ne sont pas exactement les mêmes partout, c'est bien comme ça que je devrais procéder...

**Le compromis d'UX tient vraiment à la fréquence avec laquelle on rencontrerait le cas "plusieurs mesures portant sur EXACTEMENT les mêmes localisations"**. Dès qu'on a + fréquemment des variations entre les localisations où s'appliquent les mesures, le modèle 1-n proposé dans #577 me semble plus "généralement adapté" ?

De plus, la conclusion qui est ressortie c'est que côté rédacteur d'arrêté, on a le plus fréquemment du "Mesure 1 : voici les localisations concernées, Mesure 2 : voici les localisations concernées...". Même si bien sûr il peut y avoir un mix quand effectivement on a plusieurs mesures aux mêmes endroits... Pour des travaux, j'instaure une limitation à 30 km/h ET un sens unique...
