### ISSUE TITLE
Définition d'un ou plusieurs créneaux applicables "Tous les jours"

### ISSUE THREAD

**Issue by aureliebaton** [MTES-MCT/dialog#529]
## Comportement attendu

Je peux ajouter une plage horaire pour apploquer la restriction tous les jours à certaines heures.

## Comportement réel

Lorsqu'on ajoute une nouvelle plage, par défaut l'option "Tous les jours" est sélectionnée mais il n'est pas possible de définir un créneau horaire car le bouton n'est pas disponible

## Pour reproduire
- Créer un arrêté et ajouter une plage horaire

## Traces et captures d'écran

<img width="621" alt="Screenshot 2023-11-08 at 10 36 34" src="https://github.com/MTES-MCT/dialog/assets/85348619/b27cafaa-bd95-434b-86c1-3633d67ca417">

## Contexte supplémentaire

Lié à l'issue https://github.com/MTES-MCT/dialog/issues/455

## Pistes de résolution

- Je clique sur "Ajouter une plage"
- Les dates d'application sont renseignées par défaut avec les dates de l'arrêté
- L'option "Tous les jours" est sélectionnée par défaut
- Le bouton "Définir des horaires" est visible comme sur la maquette

<img width="484" alt="Screenshot 2023-11-08 at 10 51 26" src="https://github.com/MTES-MCT/dialog/assets/85348619/c327ab7d-2e04-4cce-8bc7-a37c8e013f73">

**Comment by mmarchois** [comment]
Merci @aureliebaton , je m'en occuep
