### ISSUE TITLE
Automatiser l'intégration des données Eudonet

### ISSUE THREAD

**Issue by johanricher** [MTES-MCT/dialog#531]
## Description

A la suite de :
* #343 
* [Réunion du 16/10/2023](https://pad.incubateur.net/MaOMoW0QS82FIj5oAABVAw#2023-10-16---Point-Eudonet)
* [Réunion du 15/01/2024](https://pad.incubateur.net/MaOMoW0QS82FIj5oAABVAw?both#2024-01-15---Point-Eudonet)

Actuellement [le processus d'intégration des données Eudonet dans DiaLog](https://github.com/MTES-MCT/dialog/blob/main/docs/tools/eudonet_paris.md) est : 
* manuel
* basé sur la base de recette Eudonet (“GACS TEST”)

En janvier 2024, une mise à jour de la production d'Eudonet a eu lieu et une copie nous a été mise à disposition indéfiniment sur un serveur dédié (identifiants détenus par @florimondmanca). Cette copie est faite depuis la base de production de façon quotidienne.

## Implémentation

* On reprend les scripts précédemment développés (voir [EudonetParisImportCommand.php](https://github.com/MTES-MCT/dialog/blob/main/src/Infrastructure/Symfony/Command/EudonetParisImportCommand.php))
* Adaptations à la nouvelle base #589
* On fait tourner les scripts d'intégration sur Github Actions, de façon à rendre disponibles les logs comme des artefacts de la CI.
  * Trouver une solution pour que Github Actions ait accès 1) à la base de données Eudonet et 2) à la base de données DiaLog
* [Event `schedule`](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule)
* [Variables d'auth à définir dans les paramètres du dépôt](https://github.com/MTES-MCT/dialog/settings/secrets/actions)

## Critères d'acceptation

* Les critères de l'intégration précédemment réalisée (#343) sont respectés
* La source des "données Eudonet" est la base de données Eudonet "production", mise à jour quotidienne
* Les données Eudonet sont récupérées et intégrées automatiquement dans DiaLog une fois par semaine (jour et heure à définir arbitrairement)
* On peut accéder au log sans se connecter au serveur DiaLog

**Comment by MathieuFV** [comment]
Le pad avec les reviews qualité des données Eudonet : https://pad.incubateur.net/2IyW3VQRQxu7VC1ojcOeUg

@florimondmanca @johanricher

**Comment by florimondmanca** [comment]
J'ai créé un ticket dédié pour la qualité eudonet https://github.com/MTES-MCT/dialog/issues/663 avec ton pad

**Comment by johanricher** [comment]
Je rouvre ce ticket car "l'automatisation" #634 n'a pour l'instant été réalisée que sur la base de recette Eudonet (“GACS TEST”) or cette base n'est plus mise à jour.

Il était question qu'ils nous mettent à disposition des données mises à jour quotidiennement

@florimondmanca va les contacter pour reconfirmer avec eux le process d'accès ces données.

**Comment by florimondmanca** [comment]
Mail envoyé à nos contacts Eudonet Paris pour demander la mise en place effective de la mise à jour quotidienne de GACS TEST

En effet les données ne sont pas mises à jour : on ne trouve plus que 10 arrêtés à venir si on lance une intégration, contre 28 le mois dernier... Or avec les JOP on devrait avoir une profusion de nouveaux arrêtés

**Comment by florimondmanca** [comment]
On a obtenu les accès à notre base de "prod recopiée", j'ai pu vérifier qu'elle contenait des données à jour

Vu ce qui précède je pense que cela permet de clore ce ticket, les autres sujets Eudonet continuant par ailleurs (par ex avec #837)
