### ISSUE TITLE
Géocodage de voie nommée

### ISSUE THREAD

**Issue by johanricher** [MTES-MCT/dialog#536]
## Description

Voir #518 pour le contexte.

[La documentation de la BD TOPO](https://geoservices.ign.fr/sites/default/files/2023-10/DC_BDTOPO_3-3.pdf), référentiel sur lequel DiaLog s'appuie, donne la définition suivante à "voie nommée"  :

> Une voie désigne une route adressée. Elle est formée par la concaténation des tronçons de route qui portent le même 'identifiant_voie_1_gauche' et 'identifiant_voie_1_droite'.

Il s'agit notamment des voies en milieu urbain (rues, avenues, boulevard...) et portant une adresse qu'on peut, en principe, retrouver dans le référentiel de la [base adresse nationale](https://doc.adresse.data.gouv.fr/) (BAN).

Le géocodage de voie nommée est par exemple nécessaire pour intégrer les restrictions de circulation présentes dans les données Eudonet (ville de Paris) avec une localisation de type "La totalité de la voie", cf. les discussions suivantes :
* https://github.com/MTES-MCT/dialog/issues/518#issuecomment-1803584829
* https://github.com/MTES-MCT/dialog/issues/533#issuecomment-1803600438

## Critères d'acceptation

* (Must have) DiaLog doit pouvoir intégrer et créer des restrictions avec comme localisation une voie nommée.
* (Must have) Les localisations définies par une voie nommée doivent être associées à une géométrie linéaire (`Linestring`).

## Exploration

<details>

* Est-ce qu'il existe un service externe, par exemple une API, qu'on peut appeler pour obtenir une `Linestring` GeoJSON à partir d'une chaîne de caractère ? si oui quelle est le meilleur ? (qualité et taux de réussite basé sur les données Eudonet par exemple)
  * Service WFS vectoriel basé sur la BD TOPO, évoqué sur https://github.com/MTES-MCT/dialog/issues/515 
    * [Documentation API WFS Géoplateforme](https://geoservices.ign.fr/documentation/services/services-geoplateforme/diffusion#70070), [Doc complémentaire avec exemples](https://geoservices.ign.fr/documentation/flux-wfs-les-changements-entre-geoservices-et-geoplateforme)
    * [Doc WFS](https://docs.geoserver.org/latest/en/user/services/wfs/reference.html)
    * [Doc WFS filtering by attributes](https://www.linz.govt.nz/guidance/data-service/linz-data-service-guide/web-services/wfs-filtering-attribute-or-feature)
  * [API Nominatim](https://nominatim.openstreetmap.org/ui/about.html), basée sur OpenStreetMap

WFS IGN : après avoir lu la [doc BD TOPO](https://geoservices.ign.fr/documentation/donnees/vecteur/bdtopo) (BD TOPO - Descriptif du contenu) et https://github.com/MTES-MCT/dialog/issues/515, on peut récupérer le linéaire à partir d'un nom de voie BAN et d'un code INSEE ou d'un code postal en interrogeant `voie_nommee`

Exemple : "Rue de Flandre" à La Madeleine (Insee : 59368)

```
https://data.geopf.fr/wfs/ows?SERVICE=WFS&REQUEST=GetFeature&VERSION=2.0.0&OUTPUTFORMAT=application/json&TYPENAME=BDTOPO_V3:voie_nommee&cql_filter=nom_minuscule=%27rue%20de%20flandre%27%20AND%20code_insee=59368&PropertyName=geometrie
```

La requête prend environ 2s (acceptable)

`nom_minuscule` peut _visiblement_ s'obtenir à partir du nom de de voie BAN mis en minuscule (?)

Problème : on n'a pas actuellement le code INSEE dans DiaLog. À voir si on peut le récupérer dans la réponse de l'API Adresse. Sinon il faut sûrement croiser (Code postal, Nom de la commune) avec la [base officielle des codes postaux](https://www.data.gouv.fr/fr/datasets/base-officielle-des-codes-postaux/).

On peut récupérer le code INSEE ('citycode') via la réponse de  l'API adresse. 
Exemple pour la ville de Paris : 

```
https://api-adresse.data.gouv.fr/search/?q=paris 
```

</details>

## Implémentation

* Géocodage d'une "voie nommée" (entière) #561

Hors scope :

* Géocodage d'une "voie nommée" (section)
* #573
* #575

**Comment by florimondmanca** [comment]
@johanricher En traitant #543 j'ai remarqué qu'on a aussi le sujet des numéros de maison "partiels". Par exemple : numéro de début = 4, pas de numéro de fin ("jusqu'à la fin de la voie") => actuellement on ne peut pas calculer la fin de la voie.

À voir si on en fait un ticket à part. Il dépendrait de celui-ci (calcul du linéaire de voie dont on pourrait donc obtenir "le début" ou "la fin").

**Comment by florimondmanca** [comment]
Oui on peut résumer comme ça. Le sujet "section de voie" incluerait le fait de ramener "sur la voie" les coordonnées renvoyées par l'API Adresse (qui pointe en bordure de voie).

Ce nouveau sujet a comme prérequis le fait d'avoir le linéaire de la voie, donc il dépendrait de ce ticket en effet.

**Comment by florimondmanca** [comment]
On a bien avancé sur l'exploration BD TOPO avec @Lealefoulon 

J'ai mis à jour la description du ticket

On peut récupérer le linéaire des tronçons d'une voie à partir d'un nom de voie issu de la BAN.

Par contre pour la commune, on ne peut pas filtrer par code postal, il faut le code INSEE. Il va donc probablement falloir intégrer la [base officielle des codes postaux](https://www.data.gouv.fr/fr/datasets/base-officielle-des-codes-postaux/) (c'est un petit fichier : 1.5 Mo) pour obtenir le code INSEE à partir du code postal et du nom de la commune.

**Comment by florimondmanca** [comment]
1 sujet d'exploration encore à traiter

* Peut-on récupérer le code Insee à partir de l'API Adresse ?

Ensuite on pourra faire l'implémentation : appeler le service WFS quand on enregistre une localisation sur une voie complète

(On peut sûrement commencer maintenant)

**Comment by florimondmanca** [comment]
Rapidité : essayer avec la version "standard" (pas bêta) du service WFS https://geoservices.ign.fr/documentation/services/api-et-services-ogc/donnees-vecteur-wfs-ogc

**Comment by florimondmanca** [comment]
L'IGN propose une API d'autocomplétion, quelles sont ses capacités ? https://geoservices.ign.fr/documentation/services/api-et-services-ogc/geocodage-20/doc-technique-api-autocompletion

**Comment by johanricher** [comment]
On a fait un point avec @Lealefoulon @florimondmanca pour décider de la meilleure manière d'avancer en se basant sur nos connaissances après deux semaines d'exploration.

Pour la première itération, le critère d'acceptation est de gérer les localisations qui sont trouvables avec l'API Adresse et de récupérer des linestrings de voies entières. Donc dans un premier temps, le géocodage de voie ne gère pas les voies de la BD TOPO qui ne sont pas dans la BAN, et ne gère pas les localisations définies avec des numéros.

Ma proposition serait ensuite d'avancer pour compléter, d'un point de vue géocodage, ce qui est déjà implémenté dans l'UI :
* gérer davantages de types de voies cherchés par les utilisateurs (et pas seulement ce qu'il peut trouver avec la BAN)
* gérer les localisation définies avec des numéros en calculant des "sections de voies" (cf. discussion plus haut dans le ticket)

Ces 2 sujets auraient un effet direct sur l'UI et l'UX à court terme, et avant l'implémentation de la visualisation carto (#537) donc à discuter au préalable avec @aureliebaton pour décider comment cela serait implémenté.

**Comment by florimondmanca** [comment]
# Analyse : code postal, code Insee, etc

@MathieuFV Preneur de ton avis en tant qu'expert administratif de l'équipe

## TL;DR

Je pensais qu'on allait pouvoir récupérer le code Insee via le code postal "ou quelque chose comme ça"

En fait, il semble qu'il faille plutôt le récupérer à partir du nom de la commune et de son département

## Détails

### Rappel du problème

Pour récupérer le linéaire d'une voie via le service WFS de l'IGN (qui permet de requêter la BD TOPO), on a besoin de pouvoir récupérer le "code Insee" (en fait le code commune ou [Code officiel géographique](https://fr.wikipedia.org/wiki/Code_officiel_g%C3%A9ographique), COG) car le service WFS permet de filtrer sur ce champ-là et pas le code postal.

Le code Insee est unique pour les communes donc c'est logique.

Le code Insee des communes est fourni dans le "découpage administratif" https://github.com/etalab/decoupage-administratif où pour chaque commune on a notamment 

* le code Insee
* le nom de la commune
* son type (commune actuelle, [commune déléguée]([commune-deleguee](https://fr.wikipedia.org/wiki/Commune_nouvelle#Communes_d%C3%A9l%C3%A9gu%C3%A9es)), [commune associée](https://fr.wikipedia.org/wiki/Commune_associ%C3%A9e), arrondissement)
* ses codes postaux (une commune peut être desservie par plusieurs codes postaux, typiquement un hameau, par exemple Issanlas)

Mais dans DiaLog on saisit les voies via libellé "postal", par exemple : "Rue du Parc, 59110 La Madeleine".

Au moment de l'enregistrement, on n'a donc accès qu'à la voie "Rue du Parc", au code postal "59110", et au nom de la commune "La Madeleine"

Comment récupérer le code Insee à partir de ce libellé de voie ?

### Option 1 : à partir du code postal

Malheureusement ça ne peut pas suffire, car certaines villes partagent le même code postal. 

Par exemple [Le Mesnil-Le-Roi](https://fr.wikipedia.org/wiki/Le_Mesnil-le-Roi) a pour code postal 78600, qui est le même que sa voisine [Maisons-Laffitte](https://fr.wikipedia.org/wiki/Maisons-Laffitte).

Ou encore 01510 qui est partagé par pas moins de 10 communes de l'Ain.

### Option 2 : à partir du nom de la commune

La plupart du temps ça fonctionnerait

Par exemple

```sql
> select insee_code from fr_city where name ILIKE 'Le Mesnil-le-roi';
 insee_code 
------------
 78396
(1 row)
```

Mais certaines communes partagent le même nom ! Par exemple il y a 4 communes qui s'appellent "Romain".

### Option 3 : à partir du nom de la commune et du département

C'est presque bon

Dans le fichier, on a des lignes avec un (nom, département) identique

Ce sont toutes des lignes dans cette situation:

* Même code Insee
* Une ligne de type "commune-actuelle"
* Une ligne de type "commune-deleguee" ou "commune-associee"

Peut-on "ignorer" les communes déléguées et associées, et ne garder que les communes actuelles ? Ainsi, il ne pourrait y avoir qu'une seule commune actuelle d'un nom donné dans un département donné.

Je suis tenté de dire **oui** sur la base de ce qui suit.

Exemple :

* Je tape "Rue de Trait le Four, Chavornay" dans DiaLog (Chavornay](https://fr.wikipedia.org/wiki/Chavornay_(Ain)), pas de code postal, codee Insee 01097, est un hameau qui a fusionné avec d'autres pour former la commune nouvelle d'Arvière-en-Valromey, code postal 01260, code Insee 01453)
* Le seul résultat qui apparaît est "Rue de Trait le Four, 01260 Arvière-en-Valromey"
* Je le choisis et j'enregistre
* L'outil récupère roadName=Rue de Trait le Four, postCode=01510, city=Arvière-en-Valromey

On chercherait donc le code Insee en cherchant la ligne du découpage administratif où le nom est "Arvière-en-Valromey" dans le département "01", et on obtient ainsi le code Insee 01453.

Autre exemple : [Bellegarde-sur-Valserine](https://fr.wikipedia.org/wiki/Bellegarde-sur-Valserine), pas de code postal, code Insee 01033, qui est une ville où passe le TGV Lyria et une autoroute, qui est devenue le chef-lieu de [Valserhône](https://fr.wikipedia.org/wiki/Bellegarde-sur-Valserine), code postal 01200, code Insee 01033, résultat de la fusion avec deux autres communes

Si je tape "Rue des Lilas Bellegarde" dans DiaLog, j'ai deux résultats

* Rue des Lilas, 42210 Bellegarde-en-Forez
* Rue des Lilas, 01200 Valserhône

-> Je choisis la 2e adresse

Dans le fichier, on cherche le nom "Valserhône" dans le "01", et on obtient le code Insee 01033, qui est bien le code Insee de "Bellegarde-sur-Valserine commune déléguée et chef-lieu de Valserhône".

Maintenant si l'utilisateur n'utilise pas l'API Adresse (ou si celle-ci est HS, que notre JavaScript échoue, autre...), hé bien on va aller chercher dans le fichier nom="Bellegarde-sur-Valserine" et departement="01", et on trouve bien aussi le code Insee 01033.

**Comment by johanricher** [comment]
Après discussion avec Florimond :

Le périmètre dont on parle ici est celui sur lequel on travaille actuellement : le géocodage de "voie nommée" (au sens BD TOPO) entière, pour le cas d'usage de création d'arrêté. Le problème : pour récupérer la géométrie d'une voie nommé dans la BD TOPO, on a besoin du code INSEE de la commune.

On ajouterait un champ "Commune" avant la recherche de voie, qui permet de trouver une commune à partir de son libellé (en précisant le code postal quand il y a un homonyme). Potentiellement en utilisant l'API Adresse (type : "municipality").

![image](https://github.com/MTES-MCT/dialog/assets/10212787/4d9a8974-55a3-4ca0-a763-48364d4efbec)
[_Exemple d'UX_](https://app.openmobilityindicators.org/)

Option : on préremplit ce champ avec une valeur par défaut, quand en arrive à inférer la commune à partir du SIRET de l'organisation dans DiaLog.

Ensuite, le champ actuellement nommé dans l'UI "Voie ou ville" serait modifié pour s'appeler "Voie" et permet de trouver (à partir du service WFS, avec ou sans l'API Adresse en amont) dans la BD TOPO la voie dans la commune sélectionnée.

Plus tard :

On ajouterait la possibilité de définir des localisations avec d'autres "types de voies" (c'est à dire les classes de la BD TOPO cf. [documentation](https://geoservices.ign.fr/sites/default/files/2023-10/DC_BDTOPO_3-3.pdf)) :
* Route numérotée ou nommée (routes départementales, nationales, autoroutes...)
* etc.

Potentiellement, on ajouterait un champ supplémentaire qui permet de sélectionner ce type (à explorer).

@aureliebaton Qu'en penses-tu ?

**Comment by florimondmanca** [comment]
Merci @MathieuFV, ça confirme ce que j'ai cru comprendre des données du découpage administratif !

**Comment by florimondmanca** [comment]
Actuellement on autorise de ne rentrer qu'une ville dans le champ "Voie ou ville"

Par exemple "59110 La Madeleine" (=> roadName est NULL)

Mais actuellement ça n'a pas d'effet puisqu'on ne géocode pas les communes entières

@johanricher Si on sépare le champ en 2 on est d'accord que c'est une bonne occasion pour retirer aussi la possibilité de ne mettre que la commune ? Car je dois décider de si le champ `roadName` qu'on va stocker en base est "nullable" ou non ; j'aimerais dire que non, et donc qu'il est obligatoire, c'est-à-dire qu'on ne peut plus mettre de ville entière.

**Comment by MathieuFV** [comment]
Je crois que de toutes façons on n'a pas ou peu de réglementations dont le périmètre est calqué sur le contour administratif d'une ville, ça pourrait être le cas des ZFE mais en réalité plus le temps passera et plus les territoires concernés feront des adaptations du périmètre des ZFE pour comprendre ou exclure certaines voies. Par exemple : Je mets une ZFE sur tout le grand Paris mais ça embête tous les camions qui amènent les produits frais de Rungis, donc j'exclue de la ZFE un ensemble de voies qui permettent à ces véhicules de passer.

En bref, même pour des réglementations par zone on a en fait un ensemble de voies (ce dont on a pu discuter lundi matin avec @johanricher), donc la possibilité de renseigner une commune entière n'a pas beaucoup de sens, et on peut s'en passer à mon avis.

**Comment by johanricher** [comment]
> Si on sépare le champ en 2 on est d'accord que c'est une bonne occasion pour retirer aussi la possibilité de ne mettre que la commune ?

Comme dit @MathieuFV ça ne servirait uniquement pour définir une localisation sur une commune entière donc une zone. Je propose de désactiver ça en attendant qu'on le gère #519 et notamment en termes d'UI/UX.

**Comment by florimondmanca** [comment]
@johanricher On a regardé les SIRET / SIREN avec @Lealefoulon 

En fait le fichier communes.json ne contient que des SIREN

Et il n'y a pas de SIREN pour :

- Les arrondissements
- Les DOM-TOM

Est-ce que ça peut être problématique, je ne sais pas...

Mais pour les autres organisations, on pourrait retrouver leur code Insee à partir de leur SIRET en retirant les 5 derniers chiffres, ce qui donne le SIREN, puis regarder dans notre fichier de communes.

**Comment by johanricher** [comment]
Depuis #552 on a un SIRET de chaque organisation DiaLog, ce qui nous donne évidemment leur SIREN (l'inverse n'est pas possible). Donc on peut faire le lien entre une organisation dans DiaLog et le code INSEE Commune dont on a besoin pour trouver une voie nommée dans la BD TOPO.

**Comment by johanricher** [comment]
J'ai mis dans un ticket séparé le sujet SIRET -> code INSEE commune : #575, ce qui signifie que ce ticket #536 peut être cloturé avec une mise en prod sans cette fonctionnalité (on la priorisera sans doute en suite).
