### ISSUE TITLE
Formulaire pour demander la création d'un compte

### ISSUE THREAD

**Issue by johanricher** [MTES-MCT/dialog#544]
## User Story

En tant qu'utilisateur de DiaLog,  
je souhaite demander qu'on me crée un compte  
afin de pouvoir utiliser l'application.

## Contexte

L'équipe DiaLog souhaite simplifier la création des comptes pour augmenter le nombre d'utilisateurs.

Actuellement les personnes qui n'ont pas de compte pour se connecter à DiaLog sont invitées à envoyer un mail à dialog@beta.gouv.fr. Une personne de l'équipe DiaLog qui a les droits nécessaires (actuellement seulement @MathieuFV) peut ensuite créer un compte depuis l'UI de DiaLog (panneau d'administration).

Or, selon les cas, le lien `mailto:` n'ouvre pas forcément de client email ce qui entraine une confusion pour l'utilisateur. Par ailleurs écrire un email est considéré comme créant une friction, pouvant réduire leur nombre de compte créés.

![image](https://github.com/MTES-MCT/dialog/assets/10212787/9bdd570f-4539-4cd3-9a7f-b267b8448ef9)

## Critères d'acceptation

* (Must have) Les personnes qui visitent dialog.beta.gouv.fr sans être connectées peuvent voir à tout moment dans l'interface un élément qui leur permet de demander la création d'un compte.
* (Must have) Les personnes qui visitent dialog.beta.gouv.fr sans être connectées peuvent demander la création d'un compte depuis une page du site dialog.beta.gouv.fr, sans envoyer un email.
* (Must have) Les personnes qui demandent la création d'un compte peuvent, optionnellement, donner explicitement leur consentement pour être recontactées afin d'aider à l'amélioration de DiaLog.
* (Must have) Les personnes de l'équipe DiaLog avec les droits nécessaires peuvent recevoir les demandes de création de compte.

## Implémentation

* [DSFR](https://www.systeme-de-design.gouv.fr/)
* Champs obligatoire : mail, nom de l’organisation
* Champ optionnel : message, numéro SIRET
* Case à cocher en option pour être recontacté afin d'aider à l'amélioration de DiaLog
* Affichage dans le panneau d'administration de DiaLog
* Un admin DiaLog peut approuver une demande de création de compte via le panneau admin
  * Cela a pour effet de créer l'orga (sauf si elle existe déjà) et le compte utilisateur dans l'orga
  * Pour refuser une demande : bouton Supprimer
* Le mot de passe est créé et envoyé manuellement par mail par un admin (comme actuellement)
* L'acceptation ou le refus d'une demande sont envoyés manuellement par mail par un admin (comme actuellement)

**Comment by johanricher** [comment]
Suite à la discussion d'aujourd'hui :

* Ajout d'un champ "SIRET" facultatif dans le formulaire (et en base dans chaque orga)
  * Chaine de 14 caractères
* Un admin DiaLog peut approuver une demande de création de compte
* Cela a pour effet de créer l'orga (sauf si elle existe déjà) et le compte utilisateur dans l'orga
* Pour refuser : Supprimer la demande
* Le mot de passe est créé et envoyé par mail manuellement par un admin (même syst
* Information si la demande ou refusé envoyée manuellemnt par un admin

**Comment by mmarchois** [comment]
@johanricher @MathieuFV 

> Le mot de passe est créé et envoyé par mail manuellement par un admin (comme actuellement)

Autre option sinon, pour simplifier le travail de Mathieu, serait de laisser l'utilisateur définir son mot de passe dans le formulaire de création de compte.

**Comment by mmarchois** [comment]
@johanricher @MathieuFV 

> Ajout d'un champ "SIRET" facultatif dans le formulaire

Je me demande si on ne devrait pas rendre ce champ obligatoire pour qu'on puisse faire une bonne correspondance entre utilisateur <-> organisation. 
J'ai peur qu'on se retrouve avec des cas un peu bizarre (par ex dupliquer des organisations parce que la casse est différente, ou qu'un espace ou autre a été rajouté)  lors de la conversion en "vrai utilisateur". 
Ou alors est-ce un travail que @MathieuFV doit faire en amont avant de valider le compte ?

**Comment by johanricher** [comment]
Le problème c'est que si on demande le SIRET de leur orga, pas mal de personnes ne vont pas être capable de le donner, notamment car elles ne sauront même pas que leur orga (commune par exemple) en a un.

Ce qu'on s'est dit c'est que, pour l'instant et avant #551, c'est à @MathieuFV de trouver le SIRET de l'orga si la personne ne l'a pas renseigné.

**Comment by aureliebaton** [comment]
J'ai fait une revue avec quelques petites suggestions d'amélioration en me basant sur le modèle de création de compte du dsfr. 
https://www.figma.com/file/YuT6Uh4wxe90U8LaPLlDzO/Dialog?type=design&node-id=3826%3A15360&mode=design&t=Yl0eNSE4jxT0DfpE-1

**Comment by johanricher** [comment]
Ca me paraît effectivement trivial et si c'est le cas peut être implémenté dans le cadre de la PR en cours, mais je me range derrière l'avis de @mmarchois. :slightly_smiling_face:
