### ISSUE TITLE
Case "Voie entière"

### ISSUE THREAD

**Issue by florimondmanca** [MTES-MCT/dialog#573]
## User story

En tant qu'utilisateur qui remplit un arrêté, je choisis si je veux préciser des numéros de début et de fin afin de clairement cibler une voie entière ou une section

## Critères d'acceptation

- [ ] _(Must have)_ Critère 1
- [ ] _(Nice to have)_ Critère 2

## Design

Voir Maquette : case à cocher "Voie entière" sous la voie, cochée par défaut

## Implémentation

Peut attendre #572 mais pas obligé

**Comment by florimondmanca** [comment]
Je crée ce ticket pour ne pas l'oublier, cette feature a l'air sèche, en tout cas revu en daily avec Aurélie, à voir pour la priorité

**Comment by florimondmanca** [comment]
@johanricher Ce ticket correspond à la case à cocher déjà matérialisée dans la maquette

Est-il à prioriser ? Ça me semble assez sec

Il faut juste attendre #572

**Comment by johanricher** [comment]
Oui pour moi il est même dans le périmètre de #536 pour pouvoir définir une localisation sur une voie nommée, soit entière (avec géocodage) ou soit sur une section entre des numéros (comme actuellement, sans géocodage)

**Comment by florimondmanca** [comment]
@Lealefoulon Ce ticket t'avait été assigné mais est-ce que je peux le reprendre ?
