### ISSUE TITLE
Pouvoir indiquer des dimensions quel que soit le type de véhicule

### ISSUE THREAD

**Issue by florimondmanca** [MTES-MCT/dialog#582]
* Motivé par https://github.com/MTES-MCT/dialog/issues/456#issuecomment-1866279000

## Situation actuelle

Dans l'interface DiaLog, quand on choisit que la restriction concerne "Certains véhicules":

* On DOIT choisir au moins un "type de véhicule concerné" (poids lourds, matières dangeureuses, crit'air...)
* Si "poids lourds" est choisi, on DOIT saisir un poids maximum
* On ne PEUT PAS saisir le poids ou les dimensions max si on ne choisit pas "poids lourds"

## Problème posé

Pour l'intégration des données BAC-IDF #456 la situation actuelle problème car:

* Les arrêtés n'ont pas de notion de "véhicule concerné"
* Les arrêtes peuvent pourtant indiquer un poids max ou des dimensions max

Si on essaie de se conformer au modèle de données DiaLog, on doit d'abord faire comme si on avait choisi "poids lourds". C'est souvent conforme à l'intention de l'arrêté, mais peut-être pas toujours.

Si une dimension max est indiquée par l'arrêté mais sans poids max, on doit se conformer au fait que DiaLog attend un poids max, et mettre par exemple 3.5 tonnes, ce qui ne reflète pas le contenu de l'arrêté.

## Que dit DATEX II ?

Dans DATEX II, les champs type de véhicule (`vehicleType`) poids (`grossWeightCharacteristic`) et dimensions (par ex `widthCharacteristic`) du type `VehicleCharacteristics` peuvent être saisis indépendamment. Il n'y a pas de contrainte de devoir remplir tel champ si tel autre est rempli.

## Que dit le terrain ?

Y a-t-il un sens juridique à ce qu'un arrêté vise "les poids lourds" ?

Je crois qu'on a toujours associé à ça un PTAC maximum. Le fait de viser "les poids lourds" ne serait donc que pour les besoins de rédaction de l'arrêté, non ?

cc @MathieuFV 

## Solution envisagée

Modifier le modèle de données DiaLog et donc l'UI pour permettre l'intégration des données BAC-IDF de façon fidèle

Pour cela, s'aligner sur DATEX II, et donc :

* En base de données, permettre de remplir librement les champs sans contrainte entre eux
* Dans l'encadré "Certains véhicules", permettre de saisir des dimensions max peu importe le type de véhicule concerné
* GARDER l'obligation de choisir un poids max si on saisit "Poids lourds"

**Comment by MathieuFV** [comment]
Yep ! Juridiquement Poids Lourd = Minimum 3.5t de PTAC, d'où l'initialisation auto du champ "Poids" à 3,5t quand on clique sur le bouton "Poids lourd", mais bien sûr on peut relever le poids admissible sur une voie, par exemple un pont peut être dimensionné pour accueillir des véhicules jusqu'à 12t, auquel cas les arrêtés font traditionnellement références aux "Poids lourd de plus de 12t"

**Comment by florimondmanca** [comment]
En revenant sur Bac-IDF #456 je confirme qu'il faut traiter ce sujet

En bref, il s'agit de permettre de préciser des "dimensions" (hauteur, largeur, longueur) maximum indépendamment du type de véhicule et en particulier du PTAC max des poids lourds

**Comment by aureliebaton** [comment]
J'ai mis dans les maquettes une propositions d'icones pour le gabarit https://www.figma.com/file/YuT6Uh4wxe90U8LaPLlDzO/Dialog?type=design&node-id=4417%3A15666&mode=design&t=3gZIyvQY2Sm5qJgw-1
<img width="293" alt="Screenshot 2024-01-10 at 15 15 53" src="https://github.com/MTES-MCT/dialog/assets/85348619/7169dea3-d2e2-4f0d-9272-564f404cb907">

**Comment by florimondmanca** [comment]
@aureliebaton Super, merci
