### ISSUE TITLE
Indisponibilité des données de test

### ISSUE THREAD

**Issue by vparpoil** [MTES-MCT/dialog#583]
Bonjour,
Les données de test sont indisponibles depuis le 20/12/2023

https://dialog.beta.gouv.fr/api/regulations.xml

<img width="640" alt="Capture d’écran 2023-12-26 à 15 53 23" src="https://github.com/MTES-MCT/dialog/assets/1492912/66bbca50-3ab7-45fc-b981-969e004ee588">

Merci

**Comment by florimondmanca** [comment]
@vparpoil Merci beaucoup pour ce signalement, je suis dessus

**Comment by florimondmanca** [comment]
@vparpoil Les données sont de retour.

À noter que l'URL https://dialog.beta.gouv.fr/api/regulations.xml correspond aux données "de production" et non à des données "de test".

Nous allons probablement voir pour mettre en place de l'alerting basique sur le flux DATEX pour éviter que ce genre d'indisponibilité se reproduise sans alerte rapide de notre côté.

**Comment by vparpoil** [comment]
Merci, j'ai été induit en erreur par le nom affiché sur [data.gouv](https://www.data.gouv.fr/fr/datasets/64947a4af5faf2f1f9eee299/) : API DiaLog (Test)

**Comment by florimondmanca** [comment]
Bien vu merci, on va corriger ça ! cc @MathieuFV
