### ISSUE TITLE
Le géocodage de voie nommée ne fonctionne pas sous Firefox

### ISSUE THREAD

**Issue by johanricher** [MTES-MCT/dialog#598]
Bug apparu suite à #536 

Reproduction sous Firefox :

[](https://github.com/MTES-MCT/dialog/assets/10212787/362a064b-fffd-4891-8e2c-e423cb7238d3)

Je n'arrive pas à reproduire le bug sous Chromium (ça fonctionne)

**Comment by florimondmanca** [comment]
Actuellement le service de l'IGN a l'air HS :scream: https://data.geopf.fr/wfs/ows?SERVICE=WFS&REQUEST=GetFeature&VERSION=2.0.0&OUTPUTFORMAT=application/json&TYPENAME=BDTOPO_V3:voie_nommee&cql_filter=nom_minuscule=%27rue%20de%20flandre%27%20AND%20code_insee=59368&PropertyName=geometrie

Etait-ce déjà le cas hier ? Car j'ai aussi ce "bug" sous Firefox, mais du coup sous Chromium aussi.

**Comment by johanricher** [comment]
Le bug semble avoir disparu. J'ai pu créer un arrêté avec une localisation sur une rue, donc je ferme le ticket.
