### ISSUE TITLE
Problème d'affichage des créneaux horaires

### ISSUE THREAD

**Issue by aureliebaton** [MTES-MCT/dialog#602]
## Comportement attendu

Quand je définis une restriction et que j'ajoute un créneau horaire, les champs des heures s'affichent correctement

## Comportement réel

Quand je définis une restriction et que j'ajoute un créneau horaire les champs horaires sont tronqués en hauteur et les boutons icones (ajouter et supprimer) ne sont pas alignés à droite des horaires.

## Pour reproduire

- Cliquer sur "Ajouter une plage"
- Cliquer sur "Définir des horaires"

## Traces et captures d'écran
Sur Firefox : 

![Image](https://github.com/MTES-MCT/dialog/assets/85348619/5b654979-21c1-433b-b932-76f7128d3251)

![Image](https://github.com/MTES-MCT/dialog/assets/85348619/bd9e7e77-5b1a-4da0-ac00-d067af7983e4)

## Pistes de résolution

Voir le Figma si besoin

**Comment by florimondmanca** [comment]
À mon avis c'est un problème de CSS lié à notre utilisation de `.fr-fieldset`, voire à `.fr-fieldset` lui-même que je trouve pas évident à utiliser sans avoir de problèmes de marges. Il y a sûrement une interaction avec `fr-input`, etc...

J'aurais tendance à dire qu'on pourrait ne pas utiliser `.fr-fieldset` du tout et faire nos marges "à la main" (je veux dire avec le pattern [box](https://every-layout.dev/layouts/box/) par exemple).
