### ISSUE TITLE
S'assurer qu'une erreur de formulaire apparaît dans le viewport

### ISSUE THREAD

**Issue by aureliebaton** [MTES-MCT/dialog#603]
## Comportement attendu

Si une erreur est sur un champ, je devrais pouvoir la voir au moment de la validation.

## Comportement réel

Si l'erreur est sur un champ hors du viewport, elle n'est pas visible lorsqu'on clique sur le bouton Valider et on se demande pourquoi la validation ne fonctionne pas.

## Pour reproduire

- Sur une mesure, saisir une date de fin antérieure à la date de début (cela déclenchera une erreur)
- Remplir le reste du formulaire
- Cliquer sur Valider...
- Rien ne se passe... (il faut remonter touten haut du formulaire pour voir qu'il y a une erreur.

## Pistes de résolution

Au moment de la validation, on pourrait remonter automatiquement au champ en erreur, comme pour les champs obligatoires qui ne sont pas remplis.

#612

**Comment by MathieuFV** [comment]
Dans certains formulaires quand un champ est mal renseigné mais hors du viewport au moment de la validation il y a un scroll automatique qui ramène l'utilisateur jusqu'au champ concerné. Vous pensez que ça peut être une solution ?

**Comment by aureliebaton** [comment]
Effectivement, je pense que cela serait une bonne solution.

**Comment by florimondmanca** [comment]
> Dans certains formulaires

@MathieuFV Tu as déjà vu ce comportement dans DiaLog ? Ou tu veux dire "sur certains autres sites" ?

J'ai vérifié en laissant le champ "Ville ou commune" vide, ce qui déclenche une erreur "Cette valeur ne doit pas être vide", et on ne remonte pas non plus automatiquement pour que l'erreur soit dans le viewport

**Comment by MathieuFV** [comment]
Pardon, je voulais dire sur d'autres sites que DiaLog en effet.

**Comment by aureliebaton** [comment]
@florimondmanca Dans la description du bug,partie Pistes de résolution, je proposais "Au moment de la validation, on pourrait remonter automatiquement au champ en erreur, comme pour les champs obligatoires qui ne sont pas remplis."
Je crois que c'est le même comportement que @MathieuFV indiquait, et à l'heure actuelle ce comportement existe sur les champs obligatoires.

**Comment by florimondmanca** [comment]
Oui si un champ est `required` (signalé au navigateur comme obligatoire), si on essaie de soumettre le formulaire le navigateur remet le champ dans le viewport avec le tooltip "Ce champ est obligatoire" (ou similaire)

Je suis d'accord que ça serait le bon comportement

En espérant qu'au niveau technique il y a un moyen facile/standard de dire : "mets tel élément dans le viewport"

**Comment by MathieuFV** [comment]
Je propose d'envisager la solution suivante (pour synthétiser) : 

Quand un champ provoque une erreur au moment de la validation : 
1° Le viewport "remonte" au niveau de ce champ
2° Le message d'erreur est écrit au dessus du champ concerné

**Comment by florimondmanca** [comment]
Ce ticket a l'air obsolète, l'exemple précis qui est présenté a un comportement correct désormais (on a une erreur précise sur le fait qu'on n'a pas trouvé l'adresse)

![Screenshot 2024-09-24 at 14-48-48 Arrêté temporaire TEST-1-1-1-2-1 - DiaLog](https://github.com/user-attachments/assets/648f18fb-788b-4904-80f2-22cf9374d679)

Pour l'idée de faire remonter le viewport au niveau de l'erreur par contre, c'est toujours d'actualité

Je vais reformuler le ticket en ce sens
