### ISSUE TITLE
Obliger à choisir une ville parmi la liste

### ISSUE THREAD

**Issue by aureliebaton** [MTES-MCT/dialog#604]
## Comportement attendu

Le message d'erreur devrait indiquer que le nom de la ville est incorrect et inviter l'utilisateur à choisir une ville qui existe.

## Comportement réel

Lorsque j'entre un mauvais nom de ville le message d'erreur indique une erreur perturbante "Cette valeur ne doit pas être vide"

## Pour reproduire

- Dans le champ "Ville ou commune", j'entre un nom de ville incorrect.
- Je remplis le reste du formulaire
- Je clique sur Valider
- Je remonte en haut du formulaire et sur le champ "Voir ou commune" l'erreur affichée est "Cette valeur ne doit pas être vide"

## Traces et captures d'écran

![Image](https://github.com/MTES-MCT/dialog/assets/85348619/522b49fa-13d6-4874-9971-c3a7d93af6d2)

## Pistes de résolution

* Modifier le message d'erreur "Choisissez une ville ou commune dans la liste."
* Faire en sorte que la liste s'affiche à nouveau dès lors qu'on clique dans le champ

**Comment by florimondmanca** [comment]
@aureliebaton On vient de constater ce même bug avec @Lealefoulon. C'est lié au fait qu'on ne choisit pas une option dans la liste et donc le code Insee ne peut pas être déterminé. Or on en a besoin...

Une option serait de détecter ce cas et afficher sur le champ "Commune" une erreur du type "Veuillez choisir une commune dans la liste" (à reformuler). Qu'en penses tu ?

**Comment by johanricher** [comment]
Hypothèse de @mmarchois à vérifier : Le message renvoyé concerne un champ caché (champ code INSEE commune ?).

**Comment by florimondmanca** [comment]
@aureliebaton Comme vu ce matin, en plus de modifier le texte d'erreur affiché, on propose de réafficher la liste quand on focus à nouveau le champ.

En effet la liste de suggestions s'affiche actuellement que quand on tape quelque chose
