### ISSUE TITLE
Le géocodage d'une voie nommée peut échouer à cause de tirets / traits d'union

### ISSUE THREAD

**Issue by florimondmanca** [MTES-MCT/dialog#616]
## Comportement attendu

Quand on saisit une voie nommée qui peut ou pas contenir un trait d'union, le géocodage réussit dans tous les cas

## Comportement réel

Si l'API Adresse renvoie une suggestion ne contenant pas de trait d'union mais que l'API de l'IGN ne connaît que la version avec un trait d'union, le géocodage échoue (erreur "La voie n'existe pas")

## Pour reproduire

- Saisir Ville = Valenciennes
- Saisir Voie = Rue du Faubourg Sainte, choisir "Rue du Faubourg Sainte Catherine" (NB : pas de trait d'union)
- Soumettre
- Le géocodage échoue
- Pourtant l'API IGN répond favorablement si on demande la version AVEC trait d'union : https://data.geopf.fr/wfs/ows?SERVICE=WFS&REQUEST=GetFeature&VERSION=2.0.0&OUTPUTFORMAT=application/json&TYPENAME=BDTOPO_V3:voie_nommee&cql_filter=nom_minuscule=%27rue%20du%20faubourg%20sainte-catherine%27%20AND%20code_insee=59606

## Contexte supplémentaire

Découvert en faisant la liste #614

## Pistes de résolution

On avait eu le même problème avec les accents et on avait pu appliquer un filtre : #595 

Une solution pourrait être d'appliquer un filtre pour supprimer tous les traits d'union dans la recherche. En l'occurrence `strReplace('-', '', true)`. Voir [Filter function reference (geoserver.org)](https://docs.geoserver.org/stable/en/user/filter/function_reference.html#string-functions)

... À plus long terme, on voit que l'API de l'IGN et l'API Adresse diffèrent quelque peu dans le formatage des noms de voies. Et l'API de l'IGN est très "sensible" (pas du tout fuzzy) donc on doit implémenter une forme de "normalisation" nous-mêmes. L'IGN a aussi une API de géocodage. Devrait-on envisager de l'utiliser ? Est-ce que ça réduirait ces "subtiles incompatibilités" ?

**Comment by johanricher** [comment]
Comment ça se fait qu'on utilise le libellé et pas le code INSEE ? :thinking:

**Comment by florimondmanca** [comment]
On utilise le code Insee pour la commune, mais le problème se situe sur le nom de la voie ici (et une voie n'a pas de code unique)

**Comment by johanricher** [comment]
Ah, d'accord. Ca m'étonnait aussi. :sweat_smile: 

On ne peut pas se passer de l'API Adresse et requêter directement l'API Géoplateforme ? Eventuellement via [l'API dédiée aux besoins d'autocomplétion](https://geoservices.ign.fr/documentation/services/services-geoplateforme/autocompletion) ?

**Comment by florimondmanca** [comment]
C'était ce que je me demandais aussi dans la description du ticket

> ... À plus long terme, on voit que l'API de l'IGN et l'API Adresse diffèrent quelque peu dans le formatage des noms de voies. Et l'API de l'IGN est très "sensible" (pas du tout fuzzy) donc on doit implémenter une forme de "normalisation" nous-mêmes. L'IGN a aussi une API de géocodage. Devrait-on envisager de l'utiliser ? Est-ce que ça réduirait ces "subtiles incompatibilités" ?

Ça serait potentiellement un autre ticket je dirais, pour bien explorer les tenants et aboutissants...

**Comment by johanricher** [comment]
Je parlais du service d'_autocomplétion_  de la Géoplateforme pas celui de _géocodage_ qui est celui que tu mentionnais dans le corps du ticket.

Concernant l'[API d'autocomplétion](https://geoservices.ign.fr/documentation/services/services-geoplateforme/autocompletion) (`https://data.geopf.fr/geocodage/completion`) :

> l'option terr qui d'après leur doc accepte un code insee  (...) Elle accepte en fait des codes postaux

Ca pour moi c'est un bug à faire remonter ! ou une incohérence de la doc, mais qu'un tel service s'appuie sur le code postal plutôt que le code commune INSEE me paraît aberrant.

A priori le dépôt est ici : https://github.com/Geoplateforme/gpf-geocodeur

Une prise de contact auprès de Jérôme Desboeufs (via email ou Mattermost beta) serait utile je pense.

Concernant l'[API de géocodage](https://geoservices.ign.fr/documentation/services/services-geoplateforme/geocodage) (`https://data.geopf.fr/geocodage/search`) :

Elle propose bien un paramètre `citycode` pour filtrer les résultats par code commune INSEE.

Mais je suppose que si on l'utilise à la place de l'API Adresse, on perdra l'autocomplétion...

Il y a aussi un ["Service Géoplateforme de recherche"](https://geoservices.ign.fr/documentation/services/services-geoplateforme/service-geoplateforme-de-recherche) que je n'ai pas exploré.

**Comment by florimondmanca** [comment]
> Ca pour moi c'est un bug à faire remonter ! ou une incohérence de la doc, mais qu'un tel service s'appuie sur le code postal plutôt que le code commune INSEE me paraît aberrant.

Oui ça me semble être un bug aussi. Je vais ouvrir un ticket pour le signaler et en discuter

**Comment by aureliebaton** [comment]
Il y a peut-être également un problème avec les apostrophes : 

![Image](https://github.com/MTES-MCT/dialog/assets/85348619/7a0ee7b4-9dfe-4769-bc3d-b31d73727952)

**Comment by florimondmanca** [comment]
J'ai créé un ticket séparé https://github.com/MTES-MCT/dialog/issues/661 pour la question du remplacement possible de l'API Adresse par l'API autocomplétion de l'IGN

**Comment by florimondmanca** [comment]
@aureliebaton Oui dans ton screenshot l'apostrophe a l'air d'être spécial ? ՚ (U+055A) vs ' (U+0027) -> Prévoir une normalisation des apostrophes aussi...

**Comment by aureliebaton** [comment]
@florimondmanca j'ai sélectionné dans la liste qui m'était proposée, mais mon navigateur est en anglais donc c'est sans doute ça le pb ?

**Comment by mmarchois** [comment]
@aureliebaton ton problème est résolu par #668

**Comment by florimondmanca** [comment]
@mmarchois Intéressant : l'apostrophe spéciale était renvoyée par l'API Adresse directement, ça ne provenait pas d'Aurélie

**Comment by mmarchois** [comment]
> ... À plus long terme, on voit que l'API de l'IGN et l'API Adresse diffèrent quelque peu dans le formatage des noms de voies. Et l'API de l'IGN est très "sensible" (pas du tout fuzzy) donc on doit implémenter une forme de "normalisation" nous-mêmes. L'IGN a aussi une API de géocodage. Devrait-on envisager de l'utiliser ? Est-ce que ça réduirait ces "subtiles incompatibilités" ?

Ce sujet va devenir important : il y a des cas qu'on ne peut pas anticiper, comme les différences de liaisons (Rue **de** Saint-Denis, etc). On va devoir explorer la piste de l'utilisation du service de l'IGN pour faire les deux : autocomplétion et géocodage.
