### ISSUE TITLE
Arrêtés permanents : une période devrait pouvoir ne pas avoir de date de fin

### ISSUE THREAD

**Issue by florimondmanca** [MTES-MCT/dialog#622]
Découvert en travaillant sur #502 

### Problème

Quand on remplit un arrêté permanent, on peut par exemple vouloir définir une période qui va concerner les lundis... sans date de fin.

Actuellement l'UI et notre modèle de données exigent une date de fin dans tous les cas.

### Solution envisagée

* Rendre le champ `endDateTime` de la table `period` optionnel en base de données
* Cacher les champs de date et heure de fin d'une période pour les arrêtés permanents (et stocker des valeurs vides en base)

## Contournements

Pour l'instant dans #502 j'ai dû mettre une date de fin très loin dans le futur (le 1er janvier 2100...). Pas pérenne...

**Comment by florimondmanca** [comment]
@johanricher @aureliebaton Un avis sur la solution à adopter ?

Je pensais cacher les champs "date et heure de fin" dans le cas d'un arrêté permanent.

Idéalement il faudrait résoudre ça pour #502 où pour l'instant j'ai mis une date de fin très lointaine. Mais ce n'est pas _bloquant_, on peut toujours supprimer la date et heure de fin pour tous les arrêtés de type Permanent plus tard.

**Comment by aureliebaton** [comment]
@florimondmanca je serais effectivement d'avis de cacher les champs "date et heure de fin" dans le cas d'un arrêté permanent.

**Comment by florimondmanca** [comment]
OK j'ai mis à jour le ticket avec une proposition d'implémentation. De mon point de vue c'est près à passer en "prêt à développer" mais je l'ai passé en "review avant implé".
