### ISSUE TITLE
Section entre deux numéros d'une voie nommée

### ISSUE THREAD

**Issue by florimondmanca** [MTES-MCT/dialog#623]
## Contexte

Suite à #536, DiaLog permet de créer des restrictions de circulation localisées sur la **totalité** d'une voie nommée (par exemple : "La rue des écoliers à L'Abergement-Clémenciat"). Pour rappel, une "voie nommée" est un type de voie dans la BD TOPO, présente en milieu urbain (rues, avenues, boulevard...) et portant une adresse qu'on peut, en principe, retrouver dans le référentiel de la [base adresse nationale](https://doc.adresse.data.gouv.fr/) (BAN).

En milieu urbain, un nombre significatif de restrictions sont cependant localisées sur une **section** (ou "tronçon") de voie nommée, c'est à dire pas sur la totalité mais sur une partie de celle-ci (par exemple "Du 9 au 15 de l'avenue de la République à Paris").

L'objectif de ce ticket est de gérer un seul type de section : **section entre deux numéros d'une voie nommée**.

Pour les autres types de sections, voir le paragraphe "Sections" de l'epic #518, qui centralise tous les travaux liés aux localisations sur du linéaire.

## Implémentation

_Explo à terminer avant implé._

### Backend

Une section entre deux numéros d'une voie nommée est une ligne : une `Linestring` en GeoJSON. Pour générer cette géométrie, on doit concevoir un système qui permet de :
* géocoder une adresse (déjà géré grâce à la BAN / API Adresse) : 1 point de début et 1 point de fin, qui ne sont pas situés sur la ligne à sectionner
* géocoder une voie nommée (déjà géré #536) : ligne à sectionner
* calculer le point situé sur la ligne le plus proche d'un point de début/fin

[Idée d'implé à approfondir](https://github.com/MTES-MCT/dialog/issues/518#issuecomment-1853738349) :
> dans le code qui calcule la géométrie au moment d'enregistrer une localisation, si des numéros de maison sont définis, on va prendre le linéaire de voie, et géocoder les adresses de maison, puis faire un calcul géométrique avec PostGIS (à concevoir) pour "tronquer" le linéaire.

Questions auxquelles l'explo doit répondre pour concevoir un système robuste :
* Comment garantir qu'un point de début/fin (géocodé grâce à la BAN/API Adresse) appartient bien à la voie nommée (géocodé grâce à la BD TOPO) ?
* Pour le cas d'usage "intégration de données" :  est-ce un travail nécessaire/prioritaire si les données actuellement à intégrer (Eudonet #533, BAC-IDF #456) fournissent des sections déjà calculées ? (à vérifier)
* Pour le cas d'usage "création d'arrêté" (UI DiaLog) : Est-ce que le calcul d'une section à la volée, au moment de la définition de la localisation, est possible sans engendrer des problèmes d'UX ? (délai long, etc.)calcul en tâche de fond ?

### UI

Voir aussi : 

* #573

Voir [maquettes](https://www.figma.com/file/YuT6Uh4wxe90U8LaPLlDzO/Dialog?type=design&node-id=4811-16739&mode=design&t=iwnIJFDfOwmkTQJO-4)

### UX

A définir (voir #571 pour exemple) 

## Critères d'acceptation

* (Must have) DiaLog doit pouvoir intégrer et créer des restrictions avec comme localisation une section entre deux numéros d'une voie nommée.
* (Must have) Export Datex II
* (Must have) Export DOCX
* (Must have) Export CIFS

Hors périmètre (tickets à créer, voir #518) : section entre 2 intersections #419, etc.

**Comment by johanricher** [comment]
J'ai mis à jour le ticket pour restreindre son périmètre à un seul problème et une seule implé pour l'instant ([la plus prioritaire pour les JOP](https://pad.incubateur.net/MaOMoW0QS82FIj5oAABVAw?both#2024-01-31-Milestone-JOP)) : une section entre deux numéros d'une voie nommée.

Pour commencer l'exploration, reprendre discussion commencée ici : https://github.com/MTES-MCT/dialog/issues/518#issuecomment-1852052168

J'ai ajouté des questions dans le corps du ticket, je pense que c'est important d'y réfléchir et d'en ajouter d'autres pour périmétrer encore davantage le travail d'implé.

**Comment by florimondmanca** [comment]
@johanricher Je réponds ici aux

> Questions auxquelles l'explo doit répondre pour concevoir un système robuste :

> * Comment garantir qu'un point de début/fin (géocodé grâce à la BAN/API Adresse) appartient bien à la voie nommée (géocodé grâce à la BD TOPO) ?

Je ne suis pas sûr d'avoir compris la question, en particulier ce que veut dire "appartenir à"

Actuellement si je demande "9 Avenue de la République, Paris" à l'API Adresse j'obtiens un point qui ne tombe pas "sur" le linéaire de voie

Pour le voir copier-coller le GeoJSON suivant (obtenu en combinant le Point de l'API Adresse et la MultiLineString de l'IGN) dans https://geojson.io

```json
{"type":"FeatureCollection","features":[{"type":"Feature","id":"voie_nommee.1172044","geometry":{"type":"MultiLineString","coordinates":[[[2.38720084,48.86287689],[2.3872814,48.86286471]],[[2.38559574,48.86317084],[2.38701646,48.86290742],[2.38720084,48.86287689]],[[2.38494136,48.86329429],[2.38559574,48.86317084]],[[2.38229374,48.86379418],[2.38222679,48.86380732],[2.3814767,48.86395364],[2.38129088,48.86399045],[2.38128542,48.86399132],[2.38119936,48.86400706]],[[2.38024167,48.86418647],[2.38100535,48.86404473],[2.38119936,48.86400706]],[[2.38494136,48.86329429],[2.38338261,48.86358575]],[[2.38229374,48.86379418],[2.38338261,48.86358575]],[[2.3745253,48.86527372],[2.37465633,48.86526001],[2.37477514,48.86524175]],[[2.37258659,48.8656386],[2.37275738,48.86560532],[2.37411958,48.86534534],[2.3745253,48.86527372]],[[2.37477514,48.86524175],[2.37520694,48.86515497]],[[2.37803789,48.86461032],[2.378303,48.86455504],[2.38024167,48.86418647]],[[2.37520694,48.86515497],[2.37803789,48.86461032]],[[2.37151819,48.86583804],[2.3711889,48.86590106],[2.37085277,48.86596675]],[[2.37085277,48.86596675],[2.3706615,48.86600171]],[[2.3706615,48.86600171],[2.37060274,48.866014],[2.37051666,48.86603063],[2.37017508,48.86609539]],[[2.36896174,48.86633002],[2.36914619,48.86629502],[2.36954381,48.86621797]],[[2.36885106,48.86635102],[2.36896174,48.86633002]],[[2.36679615,48.86673677],[2.36641493,48.8668094],[2.3660228,48.86688287],[2.36567433,48.86695297],[2.36550363,48.86697725]],[[2.36731266,48.86663608],[2.36800811,48.86650485]],[[2.36679615,48.86673677],[2.36731266,48.86663608]],[[2.36885106,48.86635102],[2.36813655,48.86648035]],[[2.36813655,48.86648035],[2.36800811,48.86650485]],[[2.37017508,48.86609539],[2.36964899,48.86619964]],[[2.36954381,48.86621797],[2.36964899,48.86619964]],[[2.3723256,48.86569029],[2.37258659,48.8656386]],[[2.3723256,48.86569029],[2.37208794,48.86572951],[2.37151819,48.86583804]]]},"geometry_name":"geometrie","properties":{},"bbox":[2.36550363,48.86286471,2.3872814,48.86697725]},{"type":"Feature","geometry":{"type":"Point","coordinates":[2.367957,48.866665]},"properties":{"label":"9AvenuedelaRépublique75011Paris","score":0.980391818181818,"housenumber":"9","id":"75111_8158_00009","name":"9AvenuedelaRépublique","postcode":"75011","citycode":"75111","x":653634.09,"y":6863145.04,"city":"Paris","district":"Paris11eArrondissement","context":"75,Paris,Île-de-Frœance","type":"housenumber","importance":0.78431,"street":"AvenuedelaRépublique"}}],"crs":{"type":"name","properties":{"name":"urn:ogc:def:crs:EPSG::4326"}}}
```

L'hypothèse qu'on doit faire (je pense) est qu'un résultat renvoyé par l'API Adresse correspond effectivement bien à une adresse existante

Par exemple si je demande le 9 Avenue de la République, Paris, et que l'API Adresse renvoie un résultat, on doit supposer que ce résultat est bien pour cette adresse-là

C'est basique mais si on fait cette hypothèse alors je ne pense pas qu'on ait besoin d'autre "garantie"

Par contre il faut "recaler" le point renvoyé par l'API Adresse SUR le linéaire de voie, ce qui est l'objet de ce ticket

> * Pour le cas d'usage "intégration de données" : est-ce un travail nécessaire/prioritaire si les données actuellement à intégrer (Eudonet https://github.com/MTES-MCT/dialog/issues/533, BAC-IDF https://github.com/MTES-MCT/dialog/issues/456) fournissent des sections déjà calculées ? (à vérifier)

Comme signalé dans #533 Eudonet ne fournit pas de sections déjà calculées

Pour BAC-IDF en revanche on ne fait aucun géocodage de notre côté car Bac-IDF fournit directement les géométries, donc effectivement pour BAc-IDF ce ticket n'a pas d'intérêt particulier

> * Pour le cas d'usage "création d'arrêté" (UI DiaLog) : Est-ce que le calcul d'une section à la volée, au moment de la définition de la localisation, est possible sans engendrer des problèmes d'UX ? (délai long, etc.)calcul en tâche de fond ?

De mon point de vue le calcul de section sera rapide si mon hypothèse se confirme qu'il s'agit d'un calcul purement géométrique à faire faire par PostGIS.

Voilà un dessin du calcul qui doit être fait

![section](https://github.com/MTES-MCT/dialog/assets/15911462/3d93108d-1a0c-4f4b-a2a3-75b39a219f40)

**Comment by florimondmanca** [comment]
@MathieuFV Comme je disais ce matin, les voies nommées à plusieurs "côtés" comme des avenues avec voies séparées par un terre-plein central posent quelques questions supplémentaires

Si je demande "Avenue des Dentellières, Valenciennes" à l'IGN, il me sort cette géométrie : deux lignes continues, une le côté pair, l'autre pour le côté impair (au milieu c'est une double voie de tram)

![Screenshot from 2024-03-06 10-57-20](https://github.com/MTES-MCT/dialog/assets/15911462/bf5c5f24-b95e-4897-aab1-6ccc53d0ec9d)

Prenons l'exemple d'un section "du 2 au 4", qui correspond à la portion entre le Zeeman et le Tribunal de Grande Instance sur la photo

Je me dis qu'il faudrait :

* Trouver à quelle ligne appartient le 2
* À quelle ligne appartient le 4
* Si ce n'est pas la même ligne (par ex je demande le 2 et le 7), erreur : "Veuillez indiquer des numéros situés sur la même voie de circulation" ? (cc @aureliebaton)
* Si c'est sur la même ligne on est bon, j'applique ce que j'ai déjà dans #669 à cette ligne-là

Actuellement avec #669 j'ai une erreur technique de Postgis, car au moment de "recoller" les points je lui file les deux lignes alors qu'il exige de n'en recevoir qu'une seule, il faut donc choisir laquelle

Réflexion en cours, peut-être qu'il faut procéder par étapes, on ne va pas pouvoir traiter tous les cas "particuliers" tout de suite...

**Comment by florimondmanca** [comment]
Autre cas "rigolo" : les rues qui s'étendent à travers plusieurs intersections et/ou rond-points

La Rue du Faubourg de Paris à Valenciennes est ainsi en "3 morceaux" qui se rejoignent en un rond-point

![Screenshot from 2024-03-06 11-10-47](https://github.com/MTES-MCT/dialog/assets/15911462/a856f1a9-da66-4501-8bdc-bd582c77fb9b)

Est-ce que ça peut exister un arrêté qui dit : "Rue du Faubourg de Paris, du 12 (qui est sur le 'morceau' à l'ouest) au 46 (qui est sur le 'morceau' au nord)" ? @MathieuFV

**Comment by MathieuFV** [comment]
```
Je me dis qu'il faudrait :

Trouver à quelle ligne appartient le 2
À quelle ligne appartient le 4
```

Est-ce que ce ne serait pas là que le produit "BAN plus" de l'IGN peut servir ? J'avais retenu dans la doc qu'il y avait :

```
- Le lien Adresse-Support permet de rattacher une adresse à son « support » BDTOPO® (tronçon de route, zone d’activité ou d’intérêt, zone d’habitation, lieu-dit non habité, point du réseau, équipement de transport, etc…). Une adresse peut avoir plusieurs « supports ».
- Les adresses BAN - les ponctuels adresses issus de la BAN (extraction complète à la date du calcul des 4 liens).

```
Après @johanricher disait qu'on ne pouvait pas appeler ce produit par une API je crois (à confirmer)

**Comment by MathieuFV** [comment]
`Autre cas "rigolo" : les rues qui s'étendent à travers plusieurs intersections et/ou rond-points`

Là tu me pose une colle ! Je ne sais pas, je suppose que ça peut arriver oui... Après dans ce cas on serait obligés de demander à l'utilisateur de diviser en deux sa localisation pour ne fournir qu'une ligne au service PostGis à chaque fois (du numéro 12 au numéro 20 (au rond point, admettons) puis du numéro 22 au numéro 46").

Et dans ce cas je pencherais pour qu'un message d'erreur ("La localisation saisie ne peut contenir d'intersection" ou quelque chose du genre) pour que l'utilisateur soit au courant du blocage... A moins encore une fois que BAN plus ne permette des choses !

**Comment by johanricher** [comment]
J'ai exploré [BD TOPO](https://geoservices.ign.fr/bdtopo) et [BAN PLUS](https://geoservices.ign.fr/ban-plus), et j'ai l'impression que les réponses aux questions ci-dessous sont dans l'usage des tronçons de route à la place des voies nommées et routes de la BD TOPO.

Dans la BD TOPO, les tronçons de route, comme les routes, ont souvent 2 "objets", 2 voies qui correspondent par exemple à "chaussées séparées" comme dans les exemples remontés par Florimond.

Les tronçons de route peuvent porter des attributs "Identifiant voie BAN gauche" ou "Identifiant voie BAN droite". Il est donc possible, en théorie, de relier via un identifiant (donc avec certitude) une adresse BAN et un tronçon de route BD TOPO. Alors que jusqu'à présent on relie une adresse BAN et une voie nommée ou une route BD TOPO via leseul libellé, donc qui peut différer dans les deux bases (assez évident que ce n'est pas un système très robuste et il me semble qu'on commence déjà à se rendre compte des problèmes que ça engendre !). C'était le sens de ma première question.

Si je comprends bien [la doc de BAN PLUS](https://geoservices.ign.fr/sites/default/files/2023-10/DC_BAN-PLUS_1-0.pdf), le lien avec la BD TOPO se fait avec les "tronçons de route", qui sont un objet différent des voies (cf. page 318 de [la doc BD TOPO](https://geoservices.ign.fr/sites/default/files/2024-02/DC_BDTOPO_3-3_0.pdf)).

Dans BAN PLUS, un "lien sémantique" est créé pour relier "l'adresse BAN avec **le point du tronçon le plus proche** de l’adresse".

![image](https://github.com/MTES-MCT/dialog/assets/10212787/d90cb2ad-2cf0-4d6b-a6e4-c7f9d2cae909)
_Illustration avec QGIS sur l'exemple utilisé par Florimond ci-dessus_

Mon interprétation est donc que BAN PLUS ne permettrait pas de géocoder une seule ligne à partir d'une adresse (au lieu de la géométrie avec les 2 lignes), seulement de trouver sur la géométrie le point le plus proche de l'adresse.

Pour les cas "simples" de tronçons avec 2 voies, 2 géométries parallèles, on pourrait calculer une géométrie moyenne au milieu des 2 lignes ? et utiliser ça comme résultat du géocodage de la section entre 2 points d'une voie ?

Pour ton deuxième exemple, les voies en "plusieurs morceaux", l'usage des tronçons nous aidera aussi peut-être ?

Dans tous les cas je suis d'accord avec cette conclusion :slightly_smiling_face: :

> peut-être qu'il faut procéder par étapes, on ne va pas pouvoir traiter tous les cas "particuliers" tout de suite...

**Comment by florimondmanca** [comment]
> Pour les cas "simples" de tronçons avec 2 voies, 2 géométries parallèles, on pourrait calculer une géométrie moyenne au milieu des 2 lignes ? et utiliser ça comme résultat du géocodage de la section entre 2 points d'une voie ?

Au-delà de la faisabilité technique (le calcul est potentiellement facile si les points des voies sont bien "zippés", c'est-à-dire qu'on peut faire une moyenne "point à point" des line strings, sinon c'est un peu plus compliqué), je me demande juste si ça peut créer des problèmes plus tard pour les GPS ? Lesquels semblent être assez tâtillons sur le "calage" des points sur les voies et/ou tronçons que eux connaissent.

**Comment by florimondmanca** [comment]
Il y a des suites à donner à #669...

* **Section entre le "début" et un numéro, ou un numéro et la "fin"**

=> Nécessite de résoudre le problème de l'orientation des voies : est-ce que le métier utilise l'orientation par numéro d'adresse ? Par sens de circulation ?

La BD TOPO a un ordre interne de numérisation (ordre des points dans le linéaire), qui n'est pas forcément ni le sens de numérotation de maisons (quand il existe), ni le sens de circulation.

* **Section pour les voies en plusieurs morceaux** (en termes mathématiques : "voies non-connexes")

On en discutait ci-dessus.

Par exemple 

* Une voie à chaussées séparées
  * Ex: Avenue des Dentellières à Valenciennes
  * Ex: Boulevard de l'Hôpital à Paris 13 (Eudonet)

![Screenshot from 2024-03-26 14-52-07](https://github.com/MTES-MCT/dialog/assets/15911462/ff19d347-8940-4ebb-beaf-e320a1c0341b)

* Une voie éclatée en plusieurs morceaux, séparés par exemple par un rond point ou une intersection
  * Ex: Rue du Faubourg de Paris à Valenciennes
  * Ex: Rue Vauvenargues à Paris 18 (Eudonet), dans la BD TOPO elle est scindée en 2 morceaux à l'intersection avec les rues Ordener et Championet

![Screenshot from 2024-03-26 14-50-30](https://github.com/MTES-MCT/dialog/assets/15911462/63401cbe-fc8b-41e8-91ac-9f63f9e1f55e)

La limitation est certes d'ordre technique. Le calcul PostGIS plante si on lui passe un linéaire de voie qui est en plusieurs morceaux : il faut "choisir" sur quel morceau on essaie d'interpoler le début/fin de section.

> An exception occurred while executing a query: SQLSTATE[XX000]: Internal error: 7 ERROR:  line_locate_point: 1st arg isn't a line

(Actuellement ça se manifestera par "La voie n'est pas valide, veuillez vérifier le nom ou les numéros" dans l'UI.)

Mais elle est aussi logique : si une rue (définie comme un ensemble de morceaux) a des noeuds d'ordre 3 ou plus (c'est-à-dire que 3 morceaux ou plus portant le nom de la rue s'y rejoignent), comme la Rue du Faubourg de Paris à Valenciennes au niveau du rond-point, quelle approche de validation prend-on ? Est-ce que le début et la fin doivent être sur le même segment ?

* Ex: Route de la Muette à Neuilly, à Paris 16 (Eudonet) : un linéaire principal avec un bras annexe au niveau d'un rond point, qui forme un noeud d'ordre 3

![Screenshot from 2024-03-26 14-47-12](https://github.com/MTES-MCT/dialog/assets/15911462/217bff07-e6f4-4bb4-8082-3fe41b659838)

* Ex: Quai Malaquais à Paris 6 (Eudonet): un linéaire principal et une partie complexe au bout du quai

![Screenshot from 2024-03-26 14-49-13](https://github.com/MTES-MCT/dialog/assets/15911462/2c458313-1737-47fe-ba62-fb4a25a3e3b2)

**Comment by florimondmanca** [comment]
> Second point sur les noeuds : que se passe t il pour l'ordre de numérisation des points de la BD TOPO au passage d'un noeud ?
> Sur un noeud d'ordre 2 est ce qu'il y a une réinitialisation de l'ordre de numérisation ?
> Sur un noeud d'ordre 3 ou plus s'il n'y a pas de réinitialisation au passage du noeud comment est choisie la branche sur laquelle on continue de numéroter les points ?

Je ne sais pas ce que serait une "réinitialisation", mais il n'y a pas de garantie ou de standard sur l'ordre de numérisation sur un tronçon il me semble

De notre côté on passe la géométrie à la moulinette de la fonction `ST_LineMerge` de PostGIS qui fait de son mieux pour regrouper les lignes en ignorant leur orientation. Il y a quelques dessins dans la doc : https://postgis.net/docs/ST_LineMerge.html

Grâce à #700 on devrait déjà pouvoir gérer pas mal de nouvelles situations, pourvu que les points demandés tombent sur le même "morceau".

**Comment by florimondmanca** [comment]
Je t'avoue Mathieu que je ne comprends pas forcément l'enjeu de cette réflexion mais je vais essayer de te répondre :sweat_smile: 

> Quand tu parles d'ordre de numérisation je comprends que chaque point d'une ligne a quelque part un numéro, et que ce numéro s'incrémente dans un sens de la ligne, mais je me trompe peut être ?

Non pas vraiment, je veux parler de l'ordre dans lequel les points apparaissent dans la donnée (= l'ordre dans lequel la BD TOPO nous fournit les points des lignes)

```jsonc
{
  "type": "MultiLineString",
  "coordinates": [
    [0.3, 2.4], // 1er point
    [0.4, 2.3], // 2e point
    // ... etc
  ]
}
```

> A ce moment là je me demandais ce qu'il advenait du numéro en question au passage d'un nœud, est-ce qu'il continue comme si de rien était ?

Tout dépend de comment le "noeud" (= recoupement de lignes ?) est représenté "physiquement" dans la BD TOPO

Par exemple, un T (noeud de degré 3) peut être représenté aussi bien par 2 LINESTRINGS dont l'une vient toucher l'autre, que par 3 LINESTRINGs dont l'une des extrémités est commune.

D'un point de vue technique comme je disais au dessus ça importe peu car PostGIS nous permet de faire des calculs en "normalisant" cette représentation

On ne fait pas de calculs en tenant compte de l'ordre de numérisation à ce stade. Pour la gestion des sens de circulation ça va nous intéresser mais peut-être qu'on devrait d'abord poser les cas d'usage, et ensuite on verra techniquement ce qui peut être fait...
