### ISSUE TITLE
Créer un compte pour Angela

### ISSUE THREAD

**Issue by florimondmanca** [MTES-MCT/dialog#638]
Lui ajouter un compte via une migration pour qu'elle puisse accéder à tous les environnements (prod, staging, envs de branche pour tester si besoin...), comme le reste de l'équipe

**Comment by MathieuFV** [comment]
J'avais retenu une question de paramétrage que je ne pouvais pas faire de mon côté, mais j'avoue qu'en relisant je ne sais plus laquelle. Peut-être que @florimondmanca s'en rappelle ? Sinon je lui crée un compte comme d'habitude.

**Comment by florimondmanca** [comment]
@mmarchois Je pense qu'il s'agirait de lui ajouter un compte dans une migration, comme ça elle pourra se connecter et tester sur tous les envs, comme nous autres

**Comment by mmarchois** [comment]
Ok, je m'en occupe alors. @MathieuFV tu peux me donner son nom / prénom / adresse email stp ?
