### ISSUE TITLE
Lenteurs à l'enregistrement d'une mesure (géocodage voie nommée)

### ISSUE THREAD

**Issue by florimondmanca** [MTES-MCT/dialog#639]
## Comportement attendu

Quand on enregistre une localisation (prochainement une mesure contenant des localisations), l'enregistrement est relativement rapide

## Comportement réel

Des lenteurs sont régulièrement observées, où il faut attendre plusieurs longues secondes

C'est dû au géocodage de voie nommée : l'API de l'IGN est lente

NB : le comportement n'est pas observable si on édite une localisation sans la modifier, car alors la voie nommée ne change pas donc on ne refait pas le géocodage.

PAR AILLEURS il n'y a pas d'état de chargement, le bouton "Valider" est grisé, donc on a l'impression que ça a planté, mais c'est un sujet UX qu'on peut traiter séparément dans tous les cas

## Pour reproduire

- Créer une localisation sur une voie nommée, ou bien modifier la voie nommée d'une localisation existante
- Constater la lenteur

De plus, lorsque #625 sera mergé, le problème serait démultiplié avec le nombre de localisations au sein d'une mesure (car les géocodages s'exécuteront à la suite, pas en parallèle).
 
## Contexte supplémentaire

Signalé par @aureliebaton lors de la recette de #625 

## Pistes de résolution

Mettre un spinner pour l'instant https://github.com/MTES-MCT/dialog/issues/639#issuecomment-1971254314

### Options envisagées

Plusieurs idées :

1. Juste afficher un spinner et laisser les lenteurs pour l'instant
    * Complexité technique : très faible
2. Suite à #625, limiter le problème en exécutant l'enregistrement des localisations (donc leur géocodage) en parallèle.
    * Complexité technique : faible
    * Intérêt : statu quo (les lenteurs restent mais n'empirent pas avec le nombre de localisations)
3. Exécuter le géocodage en arrière-plan _avant_ l'enregistrement de la mesure. Une fois qu'on a saisi la voie nommée, une requête est faite par le navigateur pour récupérer la géométrie. Donc quand on clique sur "Valider", le géocodage est déjà fait donc les lenteurs disparaissent
    * Complexité technique : moyenne (nb : gérer la race condition entre l'arrivée d'une réponse de géocodage et l'enregistrement final)
    * Intérêt : résout le problème, mais d'autres problématiques similaires pourraient survenir dans le futur (aux endroits où on fera aussi appel à l'API IGN)
    * Sécurité : au niveau technique, la géométrie serait envoyée comme un champ pré-calculé du formulaire ; il faut que ce champ soit sécurisé pour éviter qu'un utilisateur malveillant n'envoie une géométrie qui ne corresponde pas à la voie (= qui n'ait pas été issu du géocodage en arrière-plan). 
4. Exécuter le géocodage en arrière-plan _après_ l'enregistrement de la mesure (= de façon asynchrone). Quand on clique sur "Valider", le serveur fait le géocodage et une fois fini l'enregistre en base et il est dispo pour DATEX etc, de façon transparente pour l'utilisateur
    * PROBLÈME UX (selon moi) : que faire en cas d'erreur ? À cause du mode asynchrone l'utilisateur sera déjà sur une autre page et aura l'impression que tout était OK. Il faudrait afficher une alerte "Attention en fait on n'a pas réussi à géocoder" ? Et si il ne retourne pas sur la page pour corriger la localisation ? On se retrouve avec des localisations sans géométrie... ce qu'on veut éviter.
5. Héberger directement la BD TOPO sur un serveur Postgres, sans passer par l'API IGN. Hypothèse : c'est l'API qui est lente (utilise l'interface WFS qui permet des requêtes infiniment complexes), mais les requêtes à la BD TOPO seraient simples (SELECT avec un filtre sur deux champs `nom_minuscule` et `code_insee` ; en maîtrisant la BD TOPO on pourrait aussi ajouter un index pour accélérer la requête si besoin)
    * Complexité technique : avancée
    * Intérêt : solution de long terme

**Comment by florimondmanca** [comment]
J'ai ajouté une option 3 "Traitement arrière-plan _après_ l'enregistrement (= asynchrone)" que @mmarchois et @johanricher ont suggéré en daily

Selon moi il y aurait un gros point d'interrogation UX au niveau de la gestion des erreurs avec cette approche

Dans https://github.com/MTES-MCT/dialog/pull/645#issuecomment-1963650168 @mmarchois a levé une possible faille de sécurité car en l'état de la PR on pourrait envoyer n'importe quelle valeur de géométrie (en bidouillant dans la console web) sans qu'elle ait besoin de corresponde vraiment à la voie. Je pense que ça peut être résolu https://github.com/MTES-MCT/dialog/pull/645#issuecomment-1963678649.

**Comment by florimondmanca** [comment]
Conclusion de la discussion du jour

Mettre un spinner ça suffit pour l'instant

Car #645 nécessite de traiter deux sujets qui le rendent un peu moins trivial même si pas du tout insolubles (affichage des erreurs, sécurisation)

**Comment by florimondmanca** [comment]
Les lenteurs de l'API IGN sont vraiment abyssales...

Au moment où j'écris ces lignes je travaille sur #623 qui doit passer par le géocodage de la voie nommée, et j'ai des temps de réponse dépassant les 20 secondes !

Je ne sais pas ce qu'il se passe, d'habitude c'est plutôt maxi 5 secondes.

Mais ce ne sont pas des temps de réponse dont on va pouvoir se satisfaire même avec les options proposées ici.

On a une dépendance croissante à cette API (géocodage de voie nommée, géocodage de route).

Je pense qu'il va falloir explorer l'option 5, la connexion directe via Postgres à notre copie hébergée de la BD TOPO...

**Comment by johanricher** [comment]
> Je pense qu'il va falloir explorer l'option 5, la connexion directe via Postgres à notre copie hébergée de la BD TOPO...

Ca serait bien d'avoir l'avis d'autres personnes, par exemple en posant des questions sur [le salon ~etalab-geo du Mattermost beta](https://mattermost.incubateur.net/betagouv/channels/etalab-geo). Que feraient d'autres équipes concevant un service web face aux mêmes besoins, contraintes et problèmes ?

En précisant le contexte (cas d'usage de géocodage de voie provenant de la BD TOPO + autres calculs spécifiques à partir des géométries récupérées, etc.) et le service avec lequel on rencontre des problèmes (URL du endpoint API)

**Comment by florimondmanca** [comment]
DiaLog utilise maintenant la BD TOPO pour ces opérations grâce à #677 

Je clos ce ticket, on peut rouvrir si en fait les lenteurs n'ont pas disparu, mais de mon côté ça a l'air OK.
