### ISSUE TITLE
Les jours et heures de début et de fin d'une mesure s'incrémentent de -1 jour et +1 heure à la validation de la mesure

### ISSUE THREAD

**Issue by MathieuFV** [MTES-MCT/dialog#652]
## Comportement attendu

Quand on appuie sur le bouton de validation d'une mesure, on retrouve dans le résumé les heures de début et de fin spécifiées dans le bloc horaire

## Comportement réel

Les heures de début et de fin de la mesure s'incrémentent d'une heure à chaque fois que l'on valide le bloc de la mesure. Ceci est valable à chaque modification du bloc horaire. Dans mon exemple j'ai ajouté une localisation et j'ai donc obtenu une heure de plus sur les horaires de début et de fin de ma mesure.

## Pour reproduire

Le bug a été obtenu dans le contexte suivant : 

- Création d'un nouvel arrêté
- Saisie de données dans le bloc mesure : Circulation interdite / Sauf "Autre" + texte dans le champ "autre" / Saisie d'un jour de début (26 juillet 2024) et de fin (11 août 2024) / Saisie d'une heure de début (00h00) et de fin (23h59)
- Saisie de plusieurs localisations (à Saint Ouen sur Seine et Saint Denis)
- Validation

**ATTENTION** : A la PREMIERE validation les jours apparaissent bien tels que renseignés, les heures s'incrémentent de +1 heure. Si je modifie la mesure et que je re-valide SEUL le jour de début est incrémenté de -1 jour, et les heures de +1 heure, enfin lors d'une SECONDE modification de la mesure les jours de début et de fin sont incrémentés de -1 jour et les heures de +1 heure. Ce comportement est ensuite stable lors de nouvelles modifications du bloc mesure.

## Traces et captures d'écran

Sous Chrome Version 114.0.5735.110 (Build officiel) (64 bits) et Windows 10 Pro 64bits (19045)

Les données saisies à l'origine sont les suivantes : 

![Bug1](https://github.com/MTES-MCT/dialog/assets/65396841/876f8cc7-0720-4ab1-bd26-b9fcd86d1c1c)

Après validation j'obtiens ce résultat : 

![Bug2](https://github.com/MTES-MCT/dialog/assets/65396841/9c90be5c-e160-43fd-a212-16efc35c24c7)

Après modification de la mesure puis re-validation j'ai ceci : 

![Bug3](https://github.com/MTES-MCT/dialog/assets/65396841/5d6144ca-6488-49e3-b69e-0b1d71e73a1f)

Enfin, après une autre modification et re-re-validation j'ai cela : 

![Bug4](https://github.com/MTES-MCT/dialog/assets/65396841/c6c9180a-f8cb-4ab0-b4d7-ca32e184d98a)

**Comment by florimondmanca** [comment]
@MathieuFV Merci pour la description détaillée, j'ai réussi à reproduire, je travaille sur un correctif
