### ISSUE TITLE
Etat de chargement lors de l'enregistrement d'une mesure

### ISSUE THREAD

**Issue by florimondmanca** [MTES-MCT/dialog#660]
**Problème**

Actuellement quand on clique sur "Valider", le bouton est grisé et on a l'impression que tout est gelé

Il faudrait un feedback utilisateur pour qu'on comprenne que c'est en train de charger

**Solution envisagée**

Afficher un spinner dans le bouton

Garder le bouton en état désactivé pendant le chargement (pour éviter le re-clic)

**Comment by aureliebaton** [comment]
Voici l'exemple de spinner : https://vue-dsfr.netlify.app/?path=/story/composants-dsfrbutton--bouton-primaire-avec-icone-animee
Je me demande aussi si ça vaut pas le coup aussi de compléter avec une petite notification de ce type, si c'est un peu trop long ?
![image](https://github.com/MTES-MCT/dialog/assets/85348619/c4265305-f651-473b-a3d3-f21dd9ad54a7) avec un message du genre : "les localisations  sont en cours de vérification..."
