### ISSUE TITLE
Incohérences entre la BAN et la BD TOPO

### ISSUE THREAD

**Issue by florimondmanca** [MTES-MCT/dialog#661]
## Problème

Nous avons régulièrement des problèmes de correspondance entre les autocomplétions de l'API Adresse (BAN) et le géocodage IGN (BD TOPO)

Par exemple #616 (tirets, et https://github.com/MTES-MCT/dialog/issues/616#issuecomment-1976087193 pour un pb possible sur des accents) et aussi #595 avant ça

Ces incohérences se manifestent dans l'UI sous la forme de "voies non reconnues"

Elles pourraient aussi empêcher d'intégrer des données si on fait appel à l'API Adresse pour "normaliser" les communes / voies, mais ça n'est pour l'instant pas le cas pour Eudonet Paris ni Bac IDF.

## Exploration

Dans l'idéal l'autocomplétion et le géocodage devraient utiliser la même source de données

Options possibles

* Utiliser l'[API d'autocomplétion](https://geoservices.ign.fr/documentation/services/services-geoplateforme/autocompletion) (https://data.geopf.fr/geocodage/completion) (Comme suggéré dans https://github.com/MTES-MCT/dialog/issues/616#issuecomment-1969580185)
* Utiliser les champs "identifiants d'interopérabilité BAN" de la BD TOPO
  * Avantage : permet de conserver l'API Adresse
  * Inconvénient : nécessite de passer sur la table `troncon_de_route` ce qui nécessite un refactoring d'ampleur
* Implémenter une recherche d'autocomplétion par-dessus la BD TOPO
  * Cf https://github.com/MTES-MCT/dialog/issues/661#issuecomment-2049789090
  * Avantage : on peut continuer à travailler avec `voie_nommee`, pas besoin de passer sur `troncon_de_route`
  * Inconvénient : pas trivial si on veut conserver une recherche "fuzzy"
* Explorer techniquement l'intérêt du remplacement de l'API Adresse par l'API IGN pour l'autocomplétion (commune, voie)
  * Est-ce que ça évite les problèmes comme dans #616 ?
    * => :x: NON. L'API de l'IGN semble renvoyer le même nom que l'API Adresse, et pas le nom tel qu'il est stocké dans la BD TOPO. Exemple avec la "Rue du Faubourg Sainte Catherine" : sans tiret dans l'API Adresse, sans tiret dans l'API IGN non plus, AVEC tiret dans la BDTOPO.
  * Est-ce que l'API de l'IGN est aussi _fuzzy_ que l'API Adresse ? 
    * => OUI, on dirait bien. Par ex "Famars" donne bien "Rue de Famars" comme résultat.
  * _(Optionnel)_ Etude comparative possible : comparer la liste de résultats pour les premiers caractères de chaque `cityLabel` en base (autocomplétion commune) ; faire la même comparaison pour les couples `cityLabel` + les premiers caractères de la `roadName` (autocomplétion commune)
* https://github.com/MTES-MCT/dialog/issues/616#issuecomment-1969580185
* Explorer d'utiliser la BD TOPO elle-même pour faire les recherches (ce qui est différent d'utiliser le service de géocodage de l'IGN)
  * Une recherche "fuzzy search" (ce que fait l'API Adresse)
    * Plus complexe à implémenter, nécessite un ts_search_vector PostgreSQL
    * UX meilleure et similaire à l'API Adresse

## Implémentation

* #727

**Comment by mmarchois** [comment]
> Ouvrir un ticket sur https://github.com/Geoplateforme/gpf-geocodeur pour signaler l'usage de code_postal par l'API alors que la doc parle de code Insee (et c'est ce qu'on veut), cf https://github.com/MTES-MCT/dialog/issues/616#issuecomment-1969580185

Apparemment pas possible de créer un ticket sur le repo :thinking:

**Comment by florimondmanca** [comment]
Ah oui mince. Et y'a pas de CONTRIBUTING.Md non plus. Alors il faut passer par le Mattermost BetaGouv ?

> Une prise de contact auprès de Jérôme Desboeufs (via email ou Mattermost beta) serait utile je pense.

**Comment by johanricher** [comment]
Il y a cette adresse email aussi : contact.geoservices@ign.fr

**Comment by MathieuFV** [comment]
Je fais suivre à mes contacts à l'IGN aussi pour voir si ça peut débloquer la situation

**Comment by florimondmanca** [comment]
@mmarchois Quand on regarde la doc et qu'on essaie l'API https://geoservices.ign.fr/documentation/services/services-geoplateforme/geocodage

On peut sans problème utiliser l'option `code_insee`

```
curl -X 'GET' \
  'https://data.geopf.fr/geocodage/search?q=famars&index=address&limit=10&returntruegeometry=false&citycode=59606&type=street' \
  -H 'accept: application/json'
```

Donc en fait je ne sais plus ce qui nous a fait pensé  qu'il y avait un bug (il n'y a pas d'option "terr" contrairement à ce que je disais dans #616), mais on dirait qu'on pourrait y aller

**Comment by florimondmanca** [comment]
En fait l'API géocodage de l'IGN a l'air de s'appuyer sur la  BAN directement, et pas la BD TOPO.

En effet voilà la réponse à cette question du ticket:

* Est-ce que ça évite les problèmes comme dans #616 ?
    * => :x: NON. L'API de l'IGN semble renvoyer le même nom que l'API Adresse, et pas le nom tel qu'il est stocké dans la BD TOPO. Exemple avec la "Rue du Faubourg Sainte Catherine" : sans tiret dans l'API Adresse, sans tiret dans l'API IGN non plus, AVEC tiret dans la BDTOPO.

Conséquence, je dirais qu'il n'y a pas d'intérêt véritable à basculer de l'API Adresse à l'API IGN du point de vue de la cohérence API / BD TOPO concernant le géocodage de voies nommées

Il ne reste plus que l'option d'utiliser la clé d'interopérabilité...

> Utiliser les champs "identifiants d'interopérabilité BAN" côté IGN. NOTE : ces champs se trouvent dans la table `troncon_de_route` et non `voie_nommee`, donc nécessiteraient de migrer vers l'usage de cette table quand on interroge la BD TOPO.

Mais comme écrit ci-dessus le problème qu'on a c'est qu'il faut alors utiliser `troncon_de_route`. En gros, pour le géocodage de voie nommée, il faudrait alors reconstituer la voie nommée entière à partir des tronçons, au lieu de simplement "piocher" dans `voie_nommee`. (Il n'y a pas de lien entre ces deux tables, l'IGN semble construire `voie_nommee` au moment de la mise en livraison. Le champ `id_pseudo_fpb` a l'air legacy.)

**Comment by florimondmanca** [comment]
Nouveau cas dans Eudonet Paris:

L'arrêté 2023T19817 comporte une localisation sur la "Rue des Docteurs Déjérine"

La BD TOPO connaît "rue des docteurs augusta et rules dejerine"...

**Comment by johanricher** [comment]
La BAN contient bien [cette rue avec ce même libellé](https://adresse.data.gouv.fr/base-adresse-nationale/75120_2874) donc pas un cas d'incohérence mais un problème de matching entre une donnée en entrée et les référentiels BAN / BD TOPO.

Tentative de synthèse de ma compréhension et convergence vers une solution :

Si on demande à l'API Adresse de matcher une voie dans la BAN avec une donnée en entrée, la réponse de l'API a l'air plutôt satisfaisante : [pour reprendre ton exemple](https://api-adresse.data.gouv.fr/search/?q=Rue%20des%20Docteurs%20D%C3%A9j%C3%A9rine&type=street) et nous renvoie un identifiant (celui dont on parlait plus haut et ici https://github.com/MTES-MCT/dialog/issues/518#issuecomment-1982070020), qui nous permet alors de faire un rapprochement dans la BD TOPO qu'on a en local avec un tronçon de route et donc une voie (nommée, numérotée, etc.).

Je me plante quelque part ?

**Comment by florimondmanca** [comment]
> un problème de matching entre une donnée en entrée (arrêté) et les référentiels BAN / BD TOPO.

Oui c'est vrai c'est plus un problème côté saisie Eudonet dans ce cas précis.

**Comment by florimondmanca** [comment]
Nouvelle piste suggérée par @MathieuFV 

Utiliser la BD TOPO elle-même pour faire les recherches (ce qui est différent d'utiliser le service de géocodage de l'IGN)

Deux options de complexité différente

* Une recherche bateau par préfixe (on cherche les voies qui commencent par le terme de recherche)
  * Facile à implémenter
  * UX pas géniale, on peut facilement ne pas trouver ce qu'on cherche
  * => À mon avis à exclure
* Une recherche "fuzzy search" (ce que fait l'API Adresse)
  * Plus complexe à implémenter, nécessite un `ts_search_vector` PostgreSQL
  * UX meilleure et similaire à l'API Adresse
