### ISSUE TITLE
Qualité des données Eudonet

### ISSUE THREAD

**Issue by florimondmanca** [MTES-MCT/dialog#663]
## Comportement attendu

Les données Eudonet sont de bonne qualité (à définir)

## Comportement réel

Des incohérences et défauts sont consttés

cf pad de @MathieuFV https://pad.incubateur.net/2IyW3VQRQxu7VC1ojcOeUg

**Comment by johanricher** [comment]
Le pad mélange des problèmes très hétérogènes. Il faudra faire le tri, mais je préfère d'abord attendre que #533 et #623 pour refaire une passage en revue, vérifier ce qui est encore d'actualité ou pas, cf. discussions sur https://github.com/MTES-MCT/dialog/issues/198#issuecomment-1995279391

**Comment by florimondmanca** [comment]
@johanricher J'ai relancé un import complet des données Eudonet

https://dialog.beta.gouv.fr/api/regulations.xml est à jour

Le log d'import est dispo ici https://github.com/MTES-MCT/dialog/actions/runs/8555029391

```json
{"numProcessed":307,"numCreated":27,"numErrors":7,"elapsedSeconds":152.99}
```

Les erreurs sont les suivantes

* Arrêté 2019T17302, Périphérique Bh/16 -> Connu
* Arrêté 2020T13239, Boulevard de l'Hôpital -> Erreur liée à une linéaire en plusieurs "morceaux" (embranchement)
* Arrêté 2023T10550, Quai Malaquais -> La géométrie de ce quai comporte une sorte de rond-point
* Arrêté 2023T111298, Rue du Faubourg du Temple, depuis l'Avenue Parmentier jusqu'au Quai de Jemmapes -> L'intersection avec le Quai de Jemappes n'a pas été trouvée par Addok
* Arrêté 2023T14842, Avenue de l'Observatoire, de la Rue Michelet à la Rue des Chartreux ->Erreur liée à une géométrie complexe : cette Avenue entoure un jardin et couvre des morceaux de voies sur un carrefour... 

```json
{"type":"MultiLineString","coordinates":[[[2.336553564,48.839768565],[2.336575661,48.840066378],[2.33657613,48.840136531]],[[2.33657613,48.840136531],[2.336582393,48.840179735],[2.336590064,48.84021935],[2.336599166,48.840253576],[2.336617701,48.840295949],[2.33666992,48.840368188],[2.336725012,48.840428751]],[[2.336284251,48.841123314],[2.336112185,48.841046813]],[[2.336143944,48.841013713],[2.336132325,48.840856259],[2.336158797,48.840382441],[2.336152192,48.840259191]],[[2.33677761,48.840792386],[2.336859379,48.840791041],[2.336864828,48.840791071],[2.336936957,48.840797766],[2.337256166,48.840875082]],[[2.33677761,48.840792386],[2.336701189,48.840801856],[2.336628763,48.840818542],[2.336553474,48.840846005],[2.336495818,48.840879861],[2.336444858,48.840922748],[2.336400677,48.84096837],[2.336284251,48.841123314]],[[2.337466719,48.841246787],[2.337411412,48.84141736],[2.337397675,48.841533302],[2.337418266,48.841842797]],[[2.337418266,48.841842797],[2.337464065,48.842527467]],[[2.336434701,48.843432817],[2.336449735,48.843643351],[2.336491285,48.844232665],[2.336495888,48.844299243]],[[2.337464065,48.842527467],[2.337518386,48.843399251]],[[2.337518386,48.843399251],[2.337579625,48.844262979]],[[2.33637236,48.842550196],[2.33638863,48.84277063],[2.336434701,48.843432817]],[[2.336284251,48.841123314],[2.336333663,48.841951004]],[[2.336333663,48.841951004],[2.33637236,48.842550196]]]}
```

* Arrêté 2023T18096, Rue de Bagnolet, de la Rue Pelleport à la Rue des Pyrénnées -> Erreur liée à un linéaire en plusieurs "morceaux" : la Rue de Bagnolet est en deux morceaux séparés au niveau de l'intersection avec la rue Sainte-Blase, et comporte une voie d'à-côté menant à la Rue des Prairies

```json
{"type":"MultiLineString","coordinates":[[[2.394345092,48.856519817],[2.394452411,48.856550039]],[[2.394452411,48.856550039],[2.394491798,48.85656193]],[[2.394491798,48.85656193],[2.39459244,48.856580426]],[[2.39598338,48.856750237],[2.396251643,48.856770477],[2.396873893,48.856823079]],[[2.397148918,48.856847848],[2.396873893,48.856823079]],[[2.39459244,48.856580426],[2.394835887,48.856624826],[2.395322899,48.856703732],[2.395634731,48.856727791]],[[2.395634731,48.856727791],[2.395858081,48.856742409],[2.39598338,48.856750237]],[[2.39932795,48.85758278],[2.399226419,48.857522913],[2.399111281,48.857461179],[2.398997557,48.857394956],[2.398847119,48.857321353],[2.398764379,48.857286762],[2.398689764,48.857256709],[2.398366617,48.857149861]],[[2.40036795,48.858168973],[2.399487764,48.857670818],[2.39932795,48.85758278]],[[2.398127647,48.857071316],[2.397817955,48.856979823]],[[2.398366617,48.857149861],[2.398127647,48.857071316]],[[2.397344846,48.856876714],[2.397234643,48.856859971],[2.397148918,48.856847848]],[[2.397817955,48.856979823],[2.397699782,48.856945053],[2.397582888,48.856917484],[2.397344846,48.856876714]],[[2.401267048,48.858683404],[2.40115465,48.858619887]],[[2.402125843,48.859148162],[2.401543385,48.858832278],[2.401267048,48.858683404]],[[2.402125843,48.859148162],[2.402201609,48.859197105],[2.402303178,48.859254271],[2.402866873,48.859543077],[2.403087628,48.859666489]],[[2.403087628,48.859666489],[2.403915458,48.860100501]],[[2.404859657,48.860848958],[2.405315307,48.861291901],[2.405842372,48.861808043]],[[2.40489394,48.861069467],[2.404922603,48.861066012],[2.404949821,48.861069745],[2.404974211,48.861082457],[2.405453967,48.861563292],[2.405561804,48.861669051],[2.405621067,48.8617314],[2.405658831,48.861766661],[2.405697998,48.861798333],[2.40573735,48.861813817],[2.405842372,48.861808043]],[[2.40836109,48.864347669],[2.408458954,48.864372435],[2.408540564,48.864388128]],[[2.406669227,48.862691702],[2.406824181,48.862849855],[2.407019504,48.863054074],[2.407233737,48.863273675],[2.407470836,48.863520369],[2.407691848,48.8637436]],[[2.407691848,48.8637436],[2.407776696,48.863833954],[2.407907347,48.863972199],[2.408025905,48.864095096],[2.408132318,48.864207141],[2.408168733,48.864241496],[2.408210609,48.864274978],[2.408300008,48.864324884],[2.40836109,48.864347669]],[[2.406346071,48.862342054],[2.405842372,48.861808043]],[[2.406669227,48.862691702],[2.406346071,48.862342054]],[[2.404172956,48.860229491],[2.404208095,48.860255746],[2.404316061,48.860349816],[2.40447513,48.860504395],[2.404727433,48.860730486]],[[2.404727433,48.860730486],[2.404859657,48.860848958]],[[2.400713221,48.858367659],[2.40036795,48.858168973]],[[2.40115465,48.858619887],[2.400713221,48.858367659]]]}
```

* Arrêté 2023T19817, Rue Eugène Reisz, de la Rue Félix Terrier à la Rue des Docteurs Déjérine -> la "Rue des Docteurs Déjérine" n'existe pas dans la BD TOPO, elle s'appelle "Rue des Docteurs  Augusta et Jules Déjérine"

Voilà la liste des arrêtés qui ont été créés, pour vérification de leur contenu...

```
"2022T110159"
"2022T15092"
"2022T16442"
"2022T17620"
"2022T19021"
"2022T19096"
"2023E111464"
"2023T10786"
"2023T110216"
"2023T110291"
"2023T110616"
"2023T110833"
"2023T110972"
"2023T111137"
"2023T111157"
"2023T111410"
"2023T111480"
"2023T15200"
"2023T15201"
"2023T15510"
"2023T15609"
"2023T15735"
"2023T16667"
"2023T17472"
"2023T18240"
"2023T19496"
"2023T19678"
```

**Comment by MathieuFV** [comment]
Un point d'étonnement : Dans les identifiants d'arrêtés créé beaucoup d'années antérieures 2022 ou 2023, il n'y pas un lien entre l'année qui apparaît dans l'identifiant et la date à laquelle a été pris l'arrêté ? Le cas échéant on aurait des arrêtés un peu anciens qui n'entrent que maintenant dans DiaLog ?

**Comment by florimondmanca** [comment]
Ces arrêtés sont juste toujours actifs

Par exemple le 2022T19096 finit le 30 avril 2024

**Comment by johanricher** [comment]
A faire : on supprime les arrêtés de la ville de Paris actuellement en base prod, afin que lors du nouvel import automatisé (27/05 dans l'après-midi) les géométries soient calculées avec les tronçons suite à #773

**Comment by johanricher** [comment]
Régressions sans doute liées au nouvel import :
* Le fichier CIFS est vide : https://dialog.beta.gouv.fr/api/regulations/cifs.xml
* Il y avait 34 "arrêtés temporaires" visibles dans l'UI, il n'y en a plus que 28 https://dialog.beta.gouv.fr/regulations

**Comment by johanricher** [comment]
Pad mis à jour avec les diagnostics en cours : https://pad.incubateur.net/2IyW3VQRQxu7VC1ojcOeUg

Le problème le plus courant semble être lié aux périodes des mesures qui ne sont pas prises en comptes (à priori actuellement seules celles des arrêtés le sont). Florimond a créé un ticket dédié : #812

**Comment by johanricher** [comment]
Oui j'ai évoqué à l'oral la même réflexion, ce ticket n'a plus vraiment lieu d'être. 👍

La bonne pratique qu'on a mise dans le process d'intégration (encore en cours d'élaboration !) serait de traduire les principales erreurs qui sortent des rapports de validation à des tickets

**Comment by florimondmanca** [comment]
Réponse à Stéphane dans la perspective de relancer ce sujet en lien avec l'APUR (Atelier parisien d'urbanisme, intéressé en tant que réutilisateur)

> 
> Salut Stéphane,
> 
> Il y a peut-être un résumé quelque part dans un ticket github, je vais essayer de retrouver ça
> 
> En attendant, au global les difficultés viennent du fait qu'Eudonet est rempli avec l'objectif de remplir un document type Word, donc avec beaucoup de texte libre, alors que pour DiaLog nous avons besoin d'informations plus structurées (champs bien définis)
> L'intégration est fonctionnelle mais n'intègre qu'une minorité des données disponibles, en raison des blocages en question, pour éviter d'intégrer de la donnée non fidèle à l'arrêté
> 
> Les sujets qui me reviennent en tête :
> 
> * [Le plus bloquant] Les périodes d'application sont indiquées de façon non-structurée dans un champ "Alinéa" très difficile / coûteux à intégrer dans DiaLog (ticket 812). Pour nos besoins, il faudrait des champs structurés ou un format standardisé, sur lequel on pourrait travailler avec eux. Bloquant car la plupart des arrêtés temporaires ne sont pas "à temps plein", or on doit donc pour l'instant ignorer une majorité des arrêtés.
> * Problème similaire sur le renseignement des véhicules concernés / exemptés (ticket 596), information non structurée / non standardisée renseignée dans un des champs "Paramètres optionnels".
> * La définition des localisations est trop complexe. Les champs à saisir dépendent du champ "Type" (une zone, un axe, une section) mais l'interface n'interdit pas d'en remplir d'autres, ce qui pourrait expliquer des incohérences rencontrées lors de l'intégration, car les utilisateurs peuvent se tromper ou varier dans leurs pratiques.. Il faudrait définir un schéma de données plus clair et réduire le risque de mauvaise saisie par les agents...
> * De façon globale, la mauvaise ergonomie de l'application Eudonet semble poser des risques de mauvaise saisie et donc de qualité de la donnée...
> * Refaire un point de situation sur les données auxquelles on a accès : s'agit-il toujours bien d'une recopie des données de production ?
