### ISSUE TITLE
Affichage en double de certains utilisateurs dans l'espace admin

### ISSUE THREAD

**Issue by MathieuFV** [MTES-MCT/dialog#678]
## Comportement attendu

L'espace admin n'affiche qu'une fois chaque utilisateur (défini par une adresse mail unique) dans l'onglet "utilisateurs" de l'espace admin. 

ATTENTION : en vous y rendant vous verrez deux fois le nom d'utilisateur "Emilie G...", c'est normal elle intervient sur deux communes différentes avec deux mails différents.

## Pour reproduire

- Se rendre sur l'espace admin
- Aller dans l'onglet "utilisateurs"
- Certains noms apparaissent en double, par exemple prendre "Jérôme L..." qui apparaît en bas de la page 2 se retrouve également en page 4.

NOTA : Apparemment le bug ne se reproduit pas ailleurs que dans mon environnement de travail... La cause du bug n'est pas identifiée.

**Comment by florimondmanca** [comment]
Je pense que j'ai réussi à reproduire

J'ai créé 100 utilisateurs aléatoires avec ce script python

```python
import json
from pathlib import Path
from faker import Faker

fake = Faker()

users = [{'fullName': fake.name(), 'email': fake.email(), 'password': fake.password(), 'uuid': str(uuid4())} for _ in range(100)]

Path('users.json').write_text(json.dumps(users))
```

Mettre ce script dans `users.pý`, lancer `pip install faker`, puisl'exécuter avec `python users.py`. Ça crée un fichier `users.json`.

Ensuite on les ingère dans l'app en local avec ça :

```php
<?php

declare(strict_types=1);

namespace App\Infrastructure\Symfony\Command;

use App\Application\QueryBusInterface;
use App\Application\User\Query\GetOrganizationBySiretQuery;
use App\Application\User\Query\GetOrganizationByUuidQuery;
use App\Domain\User\Repository\OrganizationRepositoryInterface;
use App\Domain\User\Repository\UserRepositoryInterface;
use App\Domain\User\User;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

#[AsCommand(
    name: 'app:data:users',
    description: 'Load users',
    hidden: false,
)]
class LoadUsersCommand extends Command
{
    public function __construct(
        private UserRepositoryInterface $userRepository,
        private OrganizationRepositoryInterface $organizationRepository,
        private QueryBusInterface $queryBus,
        private readonly string $projectDir,
        private EntityManagerInterface $em,
    ) {
        parent::__construct();
    }

    public function execute(InputInterface $input, OutputInterface $output): int
    {
        $rows = json_decode(file_get_contents($this->projectDir . '/users.json'), associative: true);

        $organizations = $this->organizationRepository->findAll();

        foreach ($rows as $row) {
            $user = (new User($row['uuid']))
                ->setFullName($row['fullName'])
                ->setPassword($row['password'])
                ->setEmail($row['email']);

            $organization = $organizations[array_rand($organizations)];
            $user->addOrganization($organization);

            $this->userRepository->add($user);
        }

        $this->em->flush();

        return Command::SUCCESS;
    }
}
```

Je me retrouve avec par exemple Holly Salazar rattaché à la mairie d'Enval qui apparaît à la fois en page 1 et en page 2

Page 1:

![page1](https://github.com/MTES-MCT/dialog/assets/15911462/39e213f0-af1a-40bd-afcd-cced5fc6f07b)

Page 2:

![page2](https://github.com/MTES-MCT/dialog/assets/15911462/2f3b7701-43fd-4107-8d4f-158cb3e50a1c)

Je pense qu'il manque une configuration d'ordre dans le UserCrudController, cf https://symfony.com/bundles/EasyAdminBundle/current/crud.html#search-order-and-pagination-options

**Comment by mmarchois** [comment]
Ceci dit ça n'explique pas pourquoi avec le dump de prod le bug n'a pas été reproduit en local… Mais tant mieux si un sort résout le problème.

**Comment by florimondmanca** [comment]
Tu avais peut-être aussi de la duplication mais pas sur le même cas de "Jérôme L...". C'était peut-être un bug dépendant de l'ordre exact des lignes dans la DB (ordre par défaut si on n'en met pas explicitement) ce qui peut varier quand on exporte/importe un dump ?

**Comment by MathieuFV** [comment]
Eh bien je ne sais pas comment tu as eu cette intuition mais si c'est effectivement la cause du problème je te tire mon chapeau !
