### ISSUE TITLE
Traiter les problèmes remontés par Waze sur le CIFS

### ISSUE THREAD

**Issue by florimondmanca** [MTES-MCT/dialog#716]
* Bloquant pour #198

Nous avions reçu des retours suite au dépôt du flux CIFS sur le Waze Partner Hub

Il faut les traiter pour pouvoir refaire un dépôt sans avoir les mêmes retours

### Retours du 09/02/2024

https://github.com/MTES-MCT/dialog/issues/198#issuecomment-1935546010

> Hi Florimond,
>
> We received your feed (dialog.beta.gouv.fr), and have some feedback.
>
> To ensure your road closures are automatically added to the map, please change the following to meet our requirements:
>
> Update the polyline coordinates (lat/lon for the closure path)
> * Provide at least 2 sets of unique coordinates.
> * Keep the length of your road closure between 35 m - 10 km (6.2 mi).
> * Place the first and last points of your road closure around a junction or intersection and not in the middle of a road. Only a whole segment of a road can be added as a closure, and not just parts of it.
>
> Please reply to this email when you’ve updated your tags, so we can check that the feed is right.
>
> If your data feed doesn't follow these requirements, your road closures will be uploaded to the Map Editor as map problems, which require approval from a community editor before they can go live.

## Analyse

<details>
<summary>Cliquer pour voir le script Python de validation</summary>

```python
import httpx
import xml.etree.ElementTree as ET
import subprocess
import json


def _validate_polyline(value, bdtopo_url):
    if not value:
        raise ValueError("polyline is empty")

    # Number and values of coordinates

    cifs_coordinates = " ".join(s.strip() for s in value.split("\n")).split(" ")

    if len(cifs_coordinates) % 2 == 1:
        raise ValueError("not as many lat and lon coordinates")

    coordinates = []

    for lat, lon in zip(cifs_coordinates[::2], cifs_coordinates[1::2]):
        if not (40 < float(lat) < 50):
            raise ValueError(f"out of expected bounds: {lat=}")

        if not (1 < float(lon) < 2.5):
            raise ValueError(f"out of expected bounds: {lon=}")

        coordinates.append([float(lon), float(lat)])

    linestring = json.dumps({"type": "LineString", "coordinates": coordinates})
    psql = [
        "psql",
        bdtopo_url,
        "-t",
        "-c",
        f"SELECT ST_Length(ST_Transform(ST_SetSRID('{linestring}'::geometry, 4326), 2154));",
    ]
    result = subprocess.run(psql, capture_output=True)
    result.check_returncode()
    length = float(result.stdout.decode().strip())

    if not (35 < length < 10e3):
        print(coordinates)
        raise ValueError(f"out of expected bounds: {length=}")


def main(bdtopo_url):
    r = httpx.get("https://dialog.beta.gouv.fr/api/regulations/cifs.xml")
    r.raise_for_status()
    xml = ET.fromstring(r.text)

    for incident in xml.findall("incident"):
        uuid = incident.attrib["id"]

        try:
            _validate_polyline(incident.find(".//polyline").text, bdtopo_url)
        except ValueError as exc:
            print(f"ERROR: {uuid}: {exc}")


if __name__ == "__main__":
    bdtopo_url = "postgresql://dialog:dialog@localhost:5432/dialog_bdtopo"
    main(bdtopo_url)
```

</details>

### Problème 1 : points uniques

> Provide at least 2 sets of unique coordinates.

Deux polylignes sont vides :

* 018ea930-71df-75cf-84e3-f354f28c28fe (Avenue Georges Bernanos)
* 018ea930-a91b-75a0-a7e6-72288cd59b28 (Rue Vauvenargues)

On ne devrait pas exposer dans le CIFS des localisations sans géocodage

=> Peut-être lié à #690 ?

### Problème 2 : géométries trop longues ou trop courtes

>  Keep the length of your road closure between 35 m - 10 km (6.2 mi).

L'incident ae15b0b6-8143-45e2-8b44-82bd92de3b64 a une longueur 0 car il a 2x le même point

Les autres sont dans ces bornes

### Problème 3 : extrémités éloignées d'une intersection

>  Place the first and last points of your road closure around a junction or intersection and not in the middle of a road. Only a whole segment of a road can be added as a closure, and not just parts of it.

Waze nous demande de s'approcher des points d'intersections / extrémités de tronçons probablement car ils font une opération de "snap" pour recoller les incidents à leur modèle de réseau routier

Pas évident cependant de trouver toutes les polylignes qui sont "au milieu d'une route"...

## Implémentation

* #728

**Comment by florimondmanca** [comment]
> Deux polylignes sont vides :
>
> * 018ea930-71df-75cf-84e3-f354f28c28fe (Avenue Georges Bernanos)
> * 018ea930-a91b-75a0-a7e6-72288cd59b28 (Rue Vauvenargues)

Avenue Georges Bernanos => La géométrie stockée est un point mais la localisation concerne toute la voie. C'est probablement une très vieille localisation. J'ai mis à jour la BD de prod manuellement avec le linéaire récupéré dans la BD TOPO

Rue Vauvenargues => La géométrie stockée est un point et c'est cohérent car la localisation va du numéro 1 au 1...

> L'incident ae15b0b6-8143-45e2-8b44-82bd92de3b64 a une longueur 0 car il a 2x le même point

La localisation est Rue de la Ville à Fronton, du numéro 2 au numéro 2 => c'est "normal" que ça soit deux fois le même point (même si on s'attendrait plutôt à stocker un POINT plutôt qu'une LINESTRING avec 2x le même point)

Comme la Rue Vauvenargues au N°1, que faire de cette localisation pour Waze ?

**Comment by jjacquelinet** [comment]
Si on considère que la rue est fermée à la circulation devant le n°1, et que Waze attend forcément une Line, ne faudrait-il pas lui envoyer une Line de faible longueur arbitraire (3 mètres) ? Ça peut se faire en faisant un ST_Buffer autour du point suivi d'un ST_Intersection avec la ligne.

**Comment by florimondmanca** [comment]
Oui un ST_Buffer + Intersect pourrait marcher... Apparemment Waze exige 35m minimum

> Keep the length of your road closure between 35 m - 10 km (6.2 mi).

**Comment by florimondmanca** [comment]
> Place the first and last points of your road closure around a junction or intersection and not in the middle of a road. Only a whole segment of a road can be added as a closure, and not just parts of it.

Ce point-là me pose beaucoup plus de questions...

Actuellement on est sur une philosophie où on permet de cibler une section, potentiellement très loin d'une intersection, sans garder la trace d'à quel "segment" ça se rattache.

Il n'est pas non plus clair si leur notion de "segment" (en gros "un bout de rue entre deux intersections" ?) correspond aux "tronçons" de la BD TOPO.

**Comment by jjacquelinet** [comment]
Effectivement, j'avais remarqué sur Waze qu'une route est fermée entre deux intersections, même si c'est plus étendu que la fermeture réelle.

**Comment by jjacquelinet** [comment]
On va considérer que le point où une même `Line` change de nom est une intersection.

**Comment by florimondmanca** [comment]
On a reçu une réponse de Waze hier à l'upload #753, transféré sur la mailing list DiaLog

Analyse de la réponse :

* La mesure sur la Rue Esclangon (ID = 018ea930-e170-7e5a-a5f1-15e5e786baae:ff2d69ddef50d4070382a92c7180a1dd:0) va être ajoutée à la carte :tada:
* Mais visiblement c'est la seule...

Problèmes signalés :

Segment non-connu de Waze (?) :

> Some road incidents in your feed cannot be injected into Waze.  This is because they are reported on segments that are not yet mapped in the Waze Map Editor (WME).
>
> Example:
>
> Event id 018ea930-9d48-7746-aab6-d731bee5b1cb:c572db6b2f182b3a5491c405cd639ce1:0 includes a polyline (48.863633215 2.349999717 48.863732105 2.350026797 48.863991455 2.350088992 48.864031974 2.350098028 48.864066184 2.350104417 48.864113013 2.350116101 48.864198527 2.350130029 48.864303847 2.350147799 48.864605418 2.350201289 48.864650419 2.350207543 48.8648188 2.350244974 48.864821498 2.35024494 48.864907063 2.35026841 48.865127339 2.350359555) referencing an unmapped segment.

Sens "both directions" sur des rues à sens unique

> And some incidents in the feed cannot be injected, because we could not find segments due to a direction mismatch
>
> Example:
>
> Event id 018ea930-6876-71ae-a74a-fa27989324cd:1586a85b9629df27abe05325cebaac15:0, hence this is a one way road and your feed says both directions.
>
> Segment link: https://waze.com/en-US/editor?env=row&lat=48.87601&lon=2.38242&marker=true&s=4674068799486&zoomLevel=19&segments=67329484

La réponse pointe vers cette page : https://developers.google.com/waze/data-feed/road-closure-information qui contient + de prose sur les critères d'acceptation des localisations par Waze, analyse encore à faire

**Comment by florimondmanca** [comment]
## Analyse

## TL;DR

Je vais poser des questions supplémentaires à Waze

* À quoi correspond exactement leur notion de "road segment" ; est-ce qu'il est autorisé de fournir une polyligne couvrant plusieurs tronçons d'une même route (donc avec des intersections à certains endroits), ou est-ce qu'ils ont besoin d'une polyligne par tronçon ?
* Direction : est-ce qu'ils peuvent juste inférer que si le segment est à sens unique et qu'on a mis BOTH_DIRECTIONS, ça ne nous importe pas et ils pourraient "juste" réessayer de trouver le segment avec ONE_DIRECTION ?

### Unmapped segments

Cas de la Rue Saint-Denis déclaré par Waze comme "referencing an unmapped segment" :

Je ne comprends pas car le linéaire est pour le coup bien situé entre des intersections

![Capture d’écran du 2024-05-14 10-17-26](https://github.com/MTES-MCT/dialog/assets/15911462/2f6049e9-79f3-4e3b-80fa-9da0956a679a)

@MathieuFV Es-tu déjà repassé sur les arrêtés JOP en déclarant les intersections ? Ça pourrait expliquer qu'ils aient eu un linéaire qu'ils n'arrivaient pas à mapper

Auquel cas je pourrais relancer aussi l'intégration Eudonet pour qu'elle recalcule proprement les intersections (bien qu'avant c'était avec Addok donc ça devait être correct aussi), puis leur resoumettre le flux, autrement dit ce sujet "Unmapped segments" serait déjà en partie résolu par les intersections

Autre possibilité, leur notion de "segment" est très stricte et une polyligne ne peut pas couvrir un linéaire sur plusieurs intersections, mais seulement sur un "tronçon", auquel cas il faudrait découper notre linéaire et fournir une polyligne par tronçon...

### Direction mismatch

Effectivement la Rue Pradier à Paris est à sens unique

Ce problème est plus embêtant car on n'a actuellement pas de moyen de déterminer la direction à partir des seules tables actuellement intégrées dans notre BD TOPO

Il faudrait passer par l'intégration de la table `troncon_de_route` (qui contient un champ "sens de circulation" : double sens, direct, indirect, sans objet) et s'attaquer à la correspondance entre les tronçons de route et les voies nommées...

Je vais demander à Waze s'ils peuvent essayer de trouver une correspondance sur un segment avec ONE_DIRECTION comme fallback

**Comment by florimondmanca** [comment]
Explication de pourquoi la restriction qui était valide n'est pas encore visible dans Waze : il faut qu'au moins 80% du feed CIFS soit valide

>  The feed is not active yet, and the closures won't be injected in the map. For a feed to be activated, the success rate must be at least 80%.

**Comment by florimondmanca** [comment]
J'ai signalé à Waze que https://dialog.beta.gouv.fr/api/regulations/cifs.xml contient maintenant uniquement l'incident qui avait été signalé comme valide, et qu'on s'attend donc à atteindre les critères d'intégration effective dans Waze.

Surveillez votre carte Waze, Rue Esclangon à Paris...

**Comment by florimondmanca** [comment]
La Rue Esclangon devrait apparaître dans Waze :tada:

> Hi Florimond,
> We're happy to say that your feed is now live.
> Your organization will be credited as DiaLog.beta.gouv.fr for all reports.
> Please remember that closure reports with missing or problematic information will be added as map issues, which require approval from your local editing community.
> Best,

**Comment by johanricher** [comment]
> Waze confirme qu'une `<polyline>` ne peut pas porter sur plusieurs tronçons de rue, même enchaînés
> 
> > In event "018ea930-9d48-7746-aab6-d731bee5b1cb:c572db6b2f182b3a5491c405cd639ce1:0", the polyline spans over multiple streets, this answers your question "Polylines cannot span multiple junction points on a given road, correct?" Yes
> > "So in this case, we would need one incident for the portion between Rue Etienne Marcel and Rue de Turbigo, one for the portion between Rue de Turbigo and the crossing road just north of it, and one between that road and Rue Greneta?" Yes, we can try this approach.

On en revient à la problématique de définir ce qu'est un "segment" dans Waze, comme dans les précédents échanges :

> Only a whole segment of a road can be added as a closure, and not just parts of it.

Ca précise et confirme certaines choses. On peut maintenant affirmer avec certitude que dans Waze :
* Les _segments_  sont des morceaux de voies
* Les _junctions_ connectent un ou plusieurs _segments_
* Les _junctions_ sont situés aux intersections (carrefours, croisements...) des voies
* Pour que nos données soient intégrées, les géométries (polylines) diffusées doivent commencer et finir sur une _junction_

Une analyse rapide révèle que les _tronçons de route_ de la BD Topo ne sont pas tout à fait équivalents aux _segments_ de Waze. Cependant, il se pourrait qu'ils puissent être compatibles, notamment si Waze est suffisament tolérant sur la localisation des _junctions_. Mon analyse ne m'a pas permis d'arriver à une certitude sur le fait qu'on ne rencontrera pas de nouveaux problèmes avec l'utilisation des tronçons de route. Malheureusement ce ne n'est qu'après #773 et une nouvelle tentative de diffusion des données dans Waze qu'on pourra réellement le vérifier.

(Pour ne pas surcharger ce commentaire et pour qu'on puisse éventuellement compléter et s'en servir de référence plus tard, j'ai commencé à noter les questions liées à la compatibilité ici : https://pad.incubateur.net/9WRT33WOQmi1e-HaPjAs5A)

**Comment by johanricher** [comment]
La première étape c'était effectivement de faire la preuve de concept qu'on arrive à diffuser des données dans Waze (1 restriction de circulation, 1 arrêté). La deuxième chose à prouver c'est qu'on arrive à généraliser ça sur un volume significatif (au moins une dizaine de restrictions de circulation).

A ce stade, la situation c'est donc plutôt qu'on fait face à un système très strict et qu'on a des choses à améliorer de notre côté pour franchir cette deuxième étape.

Quand on arrivera à atteindre un volume significatif de données diffusées, qu'on ne trouvera plus le système de Waze aussi strict qu'auparavant ou en tout cas qu'on le comprendra mieux et qu'on connaîtra mieux les règles de son jeu, on se rendra peut-être compte qu'on est capable de diffuser des données de mauvaise "qualité" (qui contiennent des erreurs).

Je propose d'attendre ce moment pour réfléchir et décider à ce qu'il faut faire en réaction à ça, tout en étant très vigilant et réactif sur le contrôle qualité et le retrait des données de mauvaise qualité.

Une option en plus est peut-être, quand anticipe qu'un changement dans DiaLog aura pour effet de rendre de nouvelles données diffusables, de le tester d'abord sur staging (dont les données ne sont pas diffusées dans Waze) avant de le pousser en prod.

**Comment by florimondmanca** [comment]
@johanricher OK. Alors je reformule ma demande / mon questionnement

Comment atteint-on cette étape 2 (une dizaine de restrictions dans Waze) ? C'est aussi une question à moi-même, pour réfléchir à voix haute

Pour l'instant il faut bien comprendre que notre export Waze est "verrouillé" : on contrôle très précisément les restrictions qui y sont exposées grâce à la variable d'environnement `APP_CIFS_ALLOWED_LOCATION_IDS`. Actuellement elle ne contient que l'ID de la localisation de la restriction sur la Rue Esclangon.

Maintenant que #773 a été mergé on devrait avoir résolu en majorité le problème "1 polyligne = 1 tronçon" (moyennant

Donc il est _possible_ qu'on ait déjà parmi notre dataset au moins une dizaine de restrictions qui devraient "passer" dans Waze

Mais Comment les identifier ? D'une part, je me note d'aller voir si le Waze Partner Hub a des outils de validation a-priori. D'autre part, on a probablement envie de sélectionner pour l'instant des restrictions qui sont de "bonne" qualité.

Je propose donc

1. Si le Waze Partner Hub permet de pré-valider un feed CIFS (sans essayer de le publier dans Waze ni interrompre le flux existant contenant l'incident Rue Esclangon), identifier la liste des "candidats" = restrictions dont les incidents auront été marqués comme valides par Waze.
2. Parmi ces candidats, en identifier une dizaine qu'on considère de "bonne" qualité.

Je vais vérifier si 1) est faisable

**Comment by florimondmanca** [comment]
Concernant la qualité des données, je n'avais pas bien pris la mesure de cette remarque de notre contact:

> Please remember that closure reports with missing or problematic information will be added as map issues, which require approval from your local editing community.

En gros, si on met des trucs faux dans Waze, les utilisateurs ont toujours la possibilité de signaler un problème, en l'occurrence "non cette route n'est pas vraiment fermée". Je ne suis pas sûr d'où ça nous remontera par contre... Ni de qui est cette "local editing community".

**Comment by florimondmanca** [comment]
Avec #798 les données Eudonet devraient être dans Waze sous peu

Vis à vis de ce ticket, si elles passent et qu'on a un bon taux de succès, on pourra peut-être le considérer comme résolu. Il restera surtout le problème de "direction mismatch" qui viendra avec #691.
