### ISSUE TITLE
Paris : comportement différents entre "Paris 75001" et "Paris 1er arrondissement (75001)"

### ISSUE THREAD

**Issue by jjacquelinet** [MTES-MCT/dialog#722]
## Comportement attendu

Lorsque je sélectionne dans une localisation : Voie, **Paris (75001)**, Rue de Rivoli (75001), et voie entière, le formulaire devrait être validé. 

## Comportement réel

Le formulaire n'est pas validé, l'erreur `Cette adresse n’est pas reconnue. Vérifier le nom de la voie, et les numéros de début et fin.` : s'affiche. 

## Pour reproduire

Construire un arrêté et choisir la localisation comme décrit dans la partie "Comportement attendu" ci-dessus. 
Bug visible en prod. 

## Traces et captures d'écran

<img width="674" alt="Capture d’écran 2024-04-11 à 11 04 20" src="https://github.com/MTES-MCT/dialog/assets/101107163/4f216efb-619a-4318-aa1a-7a051c37cb62">

## Pistes de résolution

Il est aussi possible de sélectionner dans la liste des villes **Paris 1er arrondissement (75001)**, dans ce cas le formulaire est validé.

**Comment by jjacquelinet** [comment]
>> Il est aussi possible de sélectionner dans la liste des villes Paris 1er arrondissement (75001), dans ce cas le formulaire est validé.

À noter que dans ce cas, ça n'est pas la voie entière mais seulement la section de la rue de Rivoli dans le 1er arrondissement de Paris qui est prise en compte.

**Comment by florimondmanca** [comment]
@jjacquelinet Le problème n'est pas résolu avec les changements de code depuis, mais le comportement a changé 

Désormais quand on choisit "Paris (75001)" dans le champ Commune, on n'a plus jamais aucun résultat dans le champ "Voie", car l'autocomplete y passe maintenant par la BD TOPO qui ne connaît donc pas "Paris code insee 75056"

Devrait-on filtrer manuellement l'option "Paris (75001)" dans les résultats de l'API Adresse ?

**Comment by johanricher** [comment]
Je suis pas sûr de comprendre ce qui cause le problème. 🤔

L'autocomplétion renvoie en effet 2 résultats pour la recherche `75001` :

![Screenshot_20240924-163708.png](https://github.com/user-attachments/assets/e605d91c-e440-4d97-b915-ca433b811c12)

L'API Adresse renvoie aussi 2 résultats mais les libellés sont différents

https://api-adresse.data.gouv.fr/search/?q=75001&type=municipality&autocomplete=1

Premièrement, les libellés dans DiaLog ne devraient-ils pas être "Paris" et "Paris 1er arrondissement" ?

Est-ce que le problème c'est que la BD TOPO, dans laquelle on cherche un code INSEE issu de la recherche dans l'API Adresse, n'a pas d'entrée pour la ville de Paris (code insee 75056) mais seulement pour ses arrondissements (ici 75101) ?

Est-ce que du coup le problème ne se reproduirait pas dans les autres villes qui ont des arrondissements ?

**Comment by johanricher** [comment]
Je suis pas sûr de comprendre ce qui cause le problème. 🤔

L'autocomplétion renvoie en effet 2 résultats pour la recherche `75001` :

![Screenshot_20240924-163708.png](https://github.com/user-attachments/assets/e605d91c-e440-4d97-b915-ca433b811c12)

L'API Adresse renvoie aussi 2 résultats mais les libellés sont différents

https://api-adresse.data.gouv.fr/search/?q=75001&type=municipality&autocomplete=1

Premièrement, les libellés dans DiaLog ne devraient-ils pas être "Paris" et "Paris 1er arrondissement" ?

Est-ce que le problème c'est que la BD TOPO, dans laquelle on cherche un code INSEE issu de la recherche dans l'API Adresse, n'a pas d'entrée pour la ville de Paris (code insee 75056) mais seulement pour ses arrondissements (ici 75101) ?

Est-ce que du coup le problème ne se reproduirait pas dans les autres villes qui ont des arrondissements ?

**Comment by florimondmanca** [comment]
Oui, la BDTOPO ne connaît pas de voies nommées dont le code Insee de la commune est 75056

Donc si on choisit le 1er résultat, on n'aura jamais aucun résultat dans le champ "Voie"

> Est-ce que du coup le problème ne se reproduirait pas dans les autres villes qui ont des arrondissements ?

Oui, j'en avais fait l'hypothèse mais c'est très simple à vérifier, il faut tester avec Lyon et Marseille (les 2 seules autres communes à arrondissements), on a le même problème

Dans #971 je vais inclure Lyon et Marseille dans le correctif du coup

**Comment by johanricher** [comment]
Ok merci pour la clarification !
