### ISSUE TITLE
La géométrie n'est pas calculée pour un tronçon de voie n'ayant qu'un numéro de fin

### ISSUE THREAD

**Issue by MathieuFV** [MTES-MCT/dialog#737]
## Comportement attendu

Quand je souhaite que ma restriction porte du début d'un rue jusqu'à un certain numéro, je ne renseigne pas de numéro de début. 

## Comportement réel

Quand je fais ça, je n'obtiens pas de de géométrie dans les données même si la localisation est bien validée dans DiaLog.

## Pour reproduire

Créer un arrêté et localiser une mesure sur une voie avec uniquement un numéro de fin de tronçon.

## Traces et captures d'écran

![jusquau](https://github.com/MTES-MCT/dialog/assets/65396841/23f6b57b-a538-4fa0-b468-855953f6665d)
![jusquau2](https://github.com/MTES-MCT/dialog/assets/65396841/e4a98061-5765-40d3-8bb8-57702035eb14)

## Pistes de résolution

**Pour l'instant** : empêcher d'enregistrer une localisation avec une seule extrémité.

**À terme** : ce sujet n'est pas évident parce qu'on ne peut pas savoir de façon simple où est le "début" ou la "fin" d'une voie nommée / route départementale. Ça nécessite de définir un sens de référence. Sens de circulation ? Sens de numérotation des maisons ? Sens des PR croissants ? Etc. Se recoupe avec #713 notamment

**Comment by florimondmanca** [comment]
En effet c'est un problème "connu" mais malheureusement on dirait qu'on n'avait pas vraiment créé de ticket dédié jusqu'ici, donc merci

**Comment by florimondmanca** [comment]
En attendant de concevoir une solution, proposition de considérer ce cas comme une erreur ? Obliger à soir ne mettre aucun numéro, soit mettre les 2. Car actuellement on permet d'enregistrer comme si "tout était OK" alors qu'il n'y a pas de géocodage.

J'ai mis à jour le ticket

**Comment by florimondmanca** [comment]
La piste "obliger à ne mettre aucune extrémité OU mettre les 2" semble se confirmer
