### ISSUE TITLE
Accéder à la carte depuis la page d'accueil

### ISSUE THREAD

**Issue by aureliebaton** [MTES-MCT/dialog#763]
## Contexte

* #659 
* #820 
* #821 

## User story

En tant qu'usager de la route, 
je veux voir la liste des restrictions sur ma ville 
afin de comprendre là où je peux ou non circuler

## Critères d'acceptation

- [ ] Ajout d'une section sur la page d'accueil pour accéder à la page [Carte](https://dialog.beta.gouv.fr/carte)

## Design

![image](https://github.com/user-attachments/assets/6af43ec5-aaa0-4dea-81f8-f9f64e29de99)

[Maquette de référence](https://www.figma.com/design/YuT6Uh4wxe90U8LaPLlDzO/Dialog?node-id=6854-27885&t=xIWj0rwT9HhE8Wuw-1)

## Contexte supplémentaire

Hors périmètre de ce ticket :
* #858

**Comment by florimondmanca** [comment]
@aureliebaton La "page d'accueil" mentionnée ici serait bien une version retravaillée de https://dialog.beta.gouv.fr ?

**Comment by aureliebaton** [comment]
> > Voir la liste des restrictions de circulation accessible à partir de la page d'accueil
> 
> @aureliebaton La "page d'accueil" mentionnée ici serait bien une version retravaillée de https://dialog.beta.gouv.fr ?

Oui effectivement ! Ca fait sans doute partie d'une story plus globale sur un retravail de la page d'accueil...

**Comment by florimondmanca** [comment]
Oui d'ailleurs il me semble qu'on avait parlé du retravail des pages "statiques" (lors de la rétro ?) mais je ne sais pas si on a un ticket à ce sujet ?

**Comment by aureliebaton** [comment]
La maquette de la page d'accueil a été mise à jour pour intégrer la carto ici https://www.figma.com/design/YuT6Uh4wxe90U8LaPLlDzO/Dialog?node-id=6852-27860&t=pkj7hYVCPPzuGsWo-1
![Image](https://github.com/user-attachments/assets/21629111-856a-40bb-9ff5-3129f7036f33)

**Comment by aureliebaton** [comment]
Dernière petite mise à jour ici https://www.figma.com/design/YuT6Uh4wxe90U8LaPLlDzO/Dialog?node-id=6854-27885&t=xIWj0rwT9HhE8Wuw-1

**Comment by mmarchois** [comment]
Est-ce que plus globalement ce ticket ne concernerait pas la refonte de la landing ?
