### ISSUE TITLE
Impossible de supprimer une localisation

### ISSUE THREAD

**Issue by florimondmanca** [MTES-MCT/dialog#768]
## Comportement attendu

Quand je clique sur le bouton "Supprimer" d'une localisation puis que je clique sur "Valider", la localisation est bien supprimée et je suis amené sur la page de détail de l'arrêté

## Comportement réel

L'enregistrement échoue et un bloc "Localisation" vide réapparaît avec le champ "Type de route  ou voie" vide associé à une erreur "Cette valeur ne doit pas être vide."

Je mets ce bug en "critique" parce que c'est vraiment bloquant à l'usage si on a besoin de supprimer une localisation...

## Pour reproduire

- Prendre un arrêté en brouillon avec au moins 2 localisations
- Retirer une localisation en cliquant sur le bouton (il doit rester au moins une autre localisation)
- Cliquer sur Valider
- Constater le problème

## Contexte supplémentaire

![Screenshot 2024-05-14 at 15-59-04 Arrêté temporaire TEST - DiaLog](https://github.com/MTES-MCT/dialog/assets/15911462/746b661d-c399-44fd-8c2f-85bde1dc7681)

## Pistes de résolution

Manifestement c'est un problème de validation

Le problème doit être causé par un changement récent dans la validation...

**Comment by mmarchois** [comment]
![image](https://github.com/MTES-MCT/dialog/assets/2683379/a42b3b9d-d4b5-4c45-b2b9-562829334106)


Exact, le problème vient de la validation du roadType ...
