### ISSUE TITLE
Le début/fin d'une section de RD ne correspond pas aux PR

### ISSUE THREAD

**Issue by florimondmanca** [MTES-MCT/dialog#777]
## Comportement attendu

Quand on saisit une section de départementale grâce à des PR, la localisation résultante commence bien au PR de début et termine bien au PR de fin

## Comportement réel

Le début et la fin de la section ne correspondent pas aux positions réelles dans la BD TOPO, il y a un décalage

## Pour reproduire

Voici un exemple :

* Gestionnaire : Nord
* Numéro : D33
* Entre les PR 17 et 18

On se retrouve avec du décalage

En rouge = la section calculée par DiaLog

```sql
select st_asgeojson(l.geometry) from location l join numbered_road nr on nr.location_uuid = l.uuid ;
```

```json
{"type":"LineString","coordinates":[[3.871036983,50.190581819],[3.871074782,50.190572543],[3.871105459,50.190566938],[3.871173807,50.190555677],[3.871462537,50.190507832],[3.871721114,50.190496121],[3.871820356,50.190491825],[3.872168352,50.190474091],[3.872516148,50.190444683],[3.87268335,50.190406677],[3.872885394,50.190361239],[3.873407327,50.190209357],[3.874268321,50.189927541],[3.874907032,50.189734411],[3.875619972,50.189547034],[3.876049315,50.189461357],[3.876347607,50.189400859],[3.876360148,50.189398076],[3.877004344,50.18928033],[3.877406721,50.189172389],[3.878008565,50.18903249],[3.878663148,50.188868861],[3.878802416,50.188833741],[3.879721337,50.188588292],[3.880230706,50.188440062],[3.880745683,50.188292688],[3.881197971,50.18816013],[3.881213277,50.18815553],[3.881551832,50.188078566],[3.881562974,50.188075792],[3.881988036,50.187986532],[3.882587448,50.187869078],[3.883247558,50.187783515],[3.883620215,50.187750186]]}
```

Les marqueurs noirs = les PR tels que présents dans la BD TOPO

```sql
$ select st_asgeojson(geometrie) from point_de_repere where numero = '17' and gestionnaire = 'Nord' and route = 'D33';
```
```json
{"type":"Point","coordinates":[3.872442113,50.190450596]}
```
```sql
select st_asgeojson(geometrie) from point_de_repere where numero = '18' and gestionnaire = 'Nord' and route = 'D33';
```
```json
{"type":"Point","coordinates":[3.885881859,50.187571488]}
```

<details>
<summary>Voir la source GeoJSON du screenshot</summary>

```json
{
    "type": "FeatureCollection",
    "features": [
        {
            "type": "Feature",
            "properties": {
                "stroke": "red",
                "stroke-width": 10
            },
            "geometry": {"type":"LineString","coordinates":[[3.871036983,50.190581819],[3.871074782,50.190572543],[3.871105459,50.190566938],[3.871173807,50.190555677],[3.871462537,50.190507832],[3.871721114,50.190496121],[3.871820356,50.190491825],[3.872168352,50.190474091],[3.872516148,50.190444683],[3.87268335,50.190406677],[3.872885394,50.190361239],[3.873407327,50.190209357],[3.874268321,50.189927541],[3.874907032,50.189734411],[3.875619972,50.189547034],[3.876049315,50.189461357],[3.876347607,50.189400859],[3.876360148,50.189398076],[3.877004344,50.18928033],[3.877406721,50.189172389],[3.878008565,50.18903249],[3.878663148,50.188868861],[3.878802416,50.188833741],[3.879721337,50.188588292],[3.880230706,50.188440062],[3.880745683,50.188292688],[3.881197971,50.18816013],[3.881213277,50.18815553],[3.881551832,50.188078566],[3.881562974,50.188075792],[3.881988036,50.187986532],[3.882587448,50.187869078],[3.883247558,50.187783515],[3.883620215,50.187750186]]}
        },
        {
            "type": "Feature",
            "properties": {"pr": "17"},
            "geometry": {"type":"Point","coordinates":[3.872442113,50.190450596]}
        },
        {
            "type": "Feature",
            "properties": {"pr": "18"},
            "geometry": {"type":"Point","coordinates":[3.885881859,50.187571488]}
        },
        {
            "type": "Feature",
            "properties": {},
            "geometry":  {"type":"LineString","coordinates":[[3.871036983,50.190581819],[3.871074782,50.190572543],[3.871105459,50.190566938],[3.871173807,50.190555677],[3.871462537,50.190507832],[3.871721114,50.190496121],[3.871820356,50.190491825],[3.872168352,50.190474091],[3.872516148,50.190444683],[3.87268335,50.190406677],[3.872885394,50.190361239],[3.873407327,50.190209357],[3.874268321,50.189927541],[3.874907032,50.189734411],[3.875619972,50.189547034],[3.876049315,50.189461357],[3.876347607,50.189400859],[3.876360148,50.189398076],[3.877004344,50.18928033],[3.877406721,50.189172389],[3.878008565,50.18903249],[3.878663148,50.188868861],[3.878802416,50.188833741],[3.879721337,50.188588292],[3.880230706,50.188440062],[3.880745683,50.188292688],[3.881197971,50.18816013],[3.881213277,50.18815553],[3.881551832,50.188078566],[3.881562974,50.188075792],[3.881988036,50.187986532],[3.882587448,50.187869078],[3.883247558,50.187783515],[3.883620215,50.187750186]]}
        }
    ]
}
```
</details>

![Screenshot 2024-05-16 at 14-51-00 geojson io powered by Mapbox](https://github.com/MTES-MCT/dialog/assets/15911462/7f3b3fa3-7d00-4252-96de-d6c26bff462e)

## Contexte supplémentaire

Signalé par @MathieuFV dans le cadre d'un bug d'ampleur encore plus spectaculaire

D1120 en Corrèze, entre le PR 35 et le PR 37

La section résultante est comme si DiaLog avait calculé une section entre les PR 44 et 53 ! Mais c'est bien 35 et 37 qui ont été demandés à la DB

* En vert = PR tels que présents dans la BD TOPO
* En bleu = les points de début et de fin calculés par DiaLog

<details>
<summary>Voir la source GeoJSON du screenshot</summary>

:warning: Le GeoJSON de la départementale était trop long pour GitHub, l'insérer dans le JSON ci-dessous en utilisant le résultat de cette requête SQL

```sql
select st_asgeojson(geometrie) from route_numerotee_ou_nommee where gestionnaire = 'Corrèze' and numero = 'D1120';
```

```json
{
    "type": "FeatureCollection",
    "features": [
        {
            "type": "Feature",
            "properties": {
                "marker-color": "#00a"
            },
            "geometry": {"type":"Point","coordinates":[1.824741795,45.218936442]}
        },
        {
            "type": "Feature",
            "properties": {
                "marker-color": "#00a"
            },
            "geometry": {"type":"Point","coordinates":[1.773933093,45.269803985]}
        },
        {
            "type": "Feature",
            "geometry": {
                "type": "Point",
                "coordinates": [
                    1.865766509,
                    45.167254809
                ]
            },
            "properties": {
                "marker-color": "#0a0",
                "ogc_fid": 18050,
                "cleabs": "POIN_REP0000002273674771",
                "date_creation": "2021-10-13T16:13:07.732+00:00",
                "date_modification": "2023-08-23T10:39:10.551+00:00",
                "date_d_apparition": null,
                "date_de_confirmation": "2021-07-06",
                "sources": "CD19 2023",
                "identifiants_sources": null,
                "route": "D1120",
                "numero": "35",
                "abscisse": 34332,
                "ordre": 35,
                "cote": "U",
                "statut": "PR valide",
                "type_de_pr": "PR",
                "libelle": "35 - 19 D1120",
                "identifiant_de_section": "19-D1120-U-6",
                "code_insee_du_departement": "19",
                "lien_vers_route_nommee": "ROUTNOMM0000000097430469",
                "gestionnaire": "Corrèze"
            }
        },
        {
            "type": "Feature",
            "geometry": {
                "type": "Point",
                "coordinates": [
                    1.850618581,
                    45.180034768
                ]
            },
            "properties": {
                "marker-color": "#0a0",
                "ogc_fid": 18012,
                "cleabs": "POIN_REP0000002273674773",
                "date_creation": "2021-10-13T16:13:07.732+00:00",
                "date_modification": "2023-08-23T10:39:10.551+00:00",
                "date_d_apparition": null,
                "date_de_confirmation": "2021-07-06",
                "sources": "CD19 2023",
                "identifiants_sources": null,
                "route": "D1120",
                "numero": "37",
                "abscisse": 36255,
                "ordre": 37,
                "cote": "U",
                "statut": "PR valide",
                "type_de_pr": "PR",
                "libelle": "37 - 19 D1120",
                "identifiant_de_section": "19-D1120-U-6",
                "code_insee_du_departement": "19",
                "lien_vers_route_nommee": "ROUTNOMM0000000097430469",
                "gestionnaire": "Corrèze"
            }
        },
        {
            "type": "Feature",
            "properties": {
                "numero": "D1120",
                "gestionnaire": "Corrèze"
            },
            "geometry": "INSÉRER LE LINÉAIRE"
        }
    ]
}
```

</details>

![Screenshot 2024-05-16 at 15-01-47 geojson io powered by Mapbox](https://github.com/MTES-MCT/dialog/assets/15911462/bd43f7c2-7d5a-411c-b32b-86996d989348)

Ce problème spectaculaire n'arrive pas si on demande les PR 35 et 36 : on arrive à valider la localisation et le linéaire semble correct

```json
 {"type":"LineString","coordinates":[[1.824741795,45.218936442],[1.824829133,45.218903739],[1.824884402,45.218880907],[1.82498593,45.21883965],[1.82513784,45.218765604],[1.825248815,45.218699232],[1.825349618,45.218631852],[1.825424773,45.218572307],[1.825499946,45.218511862],[1.825589587,45.218429956],[1.825673312,45.218326375],[1.825758098,45.218172377],[1.825804138,45.218043185],[1.825820158,45.217947898],[1.825829085,45.217826422],[1.825822574,45.217711987],[1.825803286,45.217599219],[1.825775901,45.217507978],[1.825725127,45.217377769],[1.825655152,45.217251861],[1.82557472,45.21713845],[1.825433997,45.216983882],[1.825296964,45.216835656],[1.82522475,45.216755651],[1.825116542,45.21663024],[1.825027518,45.21650143],[1.824955244,45.21636379],[1.824915501,45.216254409],[1.824895932,45.216155146],[1.824887065,45.216031681],[1.824896888,45.215928224],[1.824920037,45.215796991],[1.824934708,45.215705292],[1.824963316,45.215617342],[1.825005644,45.215422374],[1.82503841,45.215257923],[1.825055455,45.215114019],[1.825042899,45.214984212],[1.82503156,45.214857119],[1.825001342,45.214719021],[1.824956847,45.21459338],[1.824892388,45.214447718],[1.824796484,45.214282814],[1.824678752,45.21406545],[1.824605132,45.213931398],[1.824547749,45.213812826],[1.824511565,45.21371609],[1.824458914,45.213554342],[1.824425218,45.213399998],[1.824402569,45.213265582],[1.824390034,45.213134875],[1.824388754,45.213014191],[1.82439907,45.212887326],[1.82441469,45.212750611],[1.824444378,45.212611343],[1.82448876,45.21243981],[1.824580149,45.212153505],[1.824859451,45.211413514],[1.825098411,45.210773956],[1.825269867,45.210496597],[1.825367769,45.210203156],[1.82547789,45.209873823],[1.825491097,45.209791114],[1.825629044,45.209410744],[1.825730793,45.209170492]]}
```

![Screenshot 2024-05-16 at 15-10-37 geojson io powered by Mapbox](https://github.com/MTES-MCT/dialog/assets/15911462/53ff1e98-d9d4-4c2d-8623-7393e80a4ca6)

Idem pour les PR 38 et 39, ça passe

## Pistes de résolution

Pas encore clair pour l'instant...

**Comment by florimondmanca** [comment]
Le problème semble circonscrit à ce PR 37 sur la RD 1120 de la Corrèze

Ailleurs on observe un léger décalage entre les extrémités de la section et les PR, mais il est acceptable, comme sur le cas de la RD 33 du Nord visible en description.

Néanmoins je ne comprends pas d'où provient ce léger décalage.

Pour la RD 1120, j'ai remarqué que l'ordre de numérisation était opposé à l'ordre des PR. Le PR0 correspond au dernier point dans le linéaire. Cela peut peut-être causer des problèmes.

**Comment by johanricher** [comment]
Je ne comprends pas pourquoi les coordonnées des PR utilisées par DiaLog pour ses calculs ne correpondraient pas à celles directement récupérées depuis la BD TOPO. :thinking: Les coordonnées des PR ne sont pas calculées mais sont stockées en base, non ?

**Comment by florimondmanca** [comment]
Moi non plus je ne comprends pas

On récupère les PR dans la BD TOPO et on les utilise immédiatement pour sectionner la RD

Donc les extrémités de la RD devraient correspondre exactement à l'emplacement des PR, surtout dans le cas abscisse = 0... Ce qui n'est pas exactement le cas et ça m'interroge aussi

**Comment by johanricher** [comment]
Je suis en train de faire du contrôle qualité sur [les restrictions de circulations publiées en Datex 2](https://dialog.beta.gouv.fr/api/regulations.xml), par exemple celles contenues dans [cet arrêté](https://dialog.beta.gouv.fr/regulations/018f770c-5307-755d-9123-ccdbdff8e4a1) (regulationId D978 RILHAC-XAINTRIE - IN202405434950#018dad52-46e4-7155-b252-ef6036b85174). Sa localisation est "D978 (Corrèze) du PR 1+0 (côté U) au PR 1+100 (côté U)".

La géométrie visible sur la carte (également exportée le Datex) est la suivante :

![image](https://github.com/MTES-MCT/dialog/assets/10212787/6a120124-192d-402d-808a-98f526ac0195)

Sur [la carte des PR](https://www.geoportail.gouv.fr/carte?c=1.7862264325562247,45.250307314223846&z=17&l0=GEOGRAPHICALGRIDSYSTEMS.PLANIGNV2::GEOPORTAIL:OGC:WMTS(1)&l1=TRANSPORTNETWORK.COMMONTRANSPORTELEMENTS.MARKERPOST_VISU::GEOPORTAIL:OGC:WMTS(1)&permalink=yes), le PR le plus proche est 50+48476 (côté U), donc à près de 50 km de la localisation exacte de la restriction.

Compte tenu du fait que ce bug semble systématique et que notre géocodage de PR ne fonctionne pas du tout pour l'instant je propose, avant toute mesure corrective, de retirer de DiaLog (base, UI, exports...) tous les arrêtés et restrictions qui ont une localisation comprenant du géocodage de PR.

**Comment by florimondmanca** [comment]
^La DB confirme ce qui est affiché dans l'UI, cet arrêté a été créé par le Conseil Départemental de Corrèze

```
-[ RECORD 1 ]-----+----------------------------------------------
description       | Travaux de maintenance sur la D978 à Spontour
name              | Conseil Départemental de la Corrèze
location_uuid     | 018f771a-52f9-7f0d-95a3-495c21859466
administrator     | Corrèze
road_number       | D978
from_point_number | 1
from_side         | U
from_abscissa     | 
to_point_number   | 1
to_side           | U
to_abscissa       | 100
```

Vu que ce bug est en production depuis longtemps, je ne sais pas s'il est urgent de le "cacher", ça impliquerait des changements dans le code par exemple pour désactiver l'affichage de l'option Route départementale, et peut-être induire de la confusion chez les utilisateurs ("pourquoi mes données ont disparu?? pourquoi je ne peux pas les remettre??")

Je pense qu'il faut plutôt simplement travailler à le résoudre, dans l'idéal avec une méthode pour "patcher" les localisations existantes (par exemple relancer un géocodage sur les RD une fois le géocodage corrigé)

**Comment by johanricher** [comment]
Suite à #873 est-ce que les localisations comprenant du géocodage de PR, potentiellement toutes fausses, ont également été réintégrées dans le CIFS ?

**Comment by florimondmanca** [comment]
J'ai repris le cas de la D978 décrit ci-dessus

A priori le problème est lié à la **différence entre l'ordre de _numérisation_** (ordre des points dans le linéaire) **et l'ordre de _numérotation_** (ordre des PR)

**Analyse**

Dans le cas de la D978 ces ordres sont inversés l'un par rapport à l'autre : le "début" du linéaire (premiers points dans la géométrie) est du côté du PR50 (la fin dans l'ordre des PR), et la "fin" du linéaire (derniers points dans la géométrie) est du côté du PR1

Dans notre calcul on ne tient pas compte de cette différence. On part du principe qu'en prenant l'abscisse du PR + l'abscisse demandée "le long de la RD", on obtiendra ce qu'on veut

L'abscisse du PR1 vaut 950m, donc en fait en faisant ce calcul on se retrouve à 950m _à partir du début du linéaire_ (côté PR50)

L'abscisse du PR50 est 48515m pour une longueur totale de la route de 49420m soit une abscisse "en partant de la fin" de 905m

Ce qui explique pourquoi la localisation calculée tombe proche du PR50 mais pas tout à fait (elle tombe à 45m à côté)

**Solution**

Pour trouver l'abscisse cible, il faut parcourir le linéaire dans le sens des PR croissants, et non pas dans le sens de numérisation du linéaire (car ils peuvent être opposés)

Reste à voir concrètement comment faire mais conceptuellement ça serait ça le correctif au cas de la D978

**Comment by florimondmanca** [comment]
Après correction (pull request en perspective) on aurait le résultat suivant, qui correspondrait bien à PR1 -> PR1+100

![Screenshot 2024-10-14 at 15-52-25 geojson io powered by Mapbox](https://github.com/user-attachments/assets/dc11dfae-b4a4-434c-8e17-087dbeda795f)

**Comment by johanricher** [comment]
Ton explication est :exploding_head: bien joué pour avoir diagnostiqué le problème. Tu as vérifié la correspondance entre le nouveau géocodage et [la carte des PR sur le géoportail](https://www.geoportail.gouv.fr/carte?c=1.7890996236030408,45.24881509620178&z=15&l0=GEOGRAPHICALGRIDSYSTEMS.PLANIGNV2::GEOPORTAIL:OGC:WMTS(1)&l1=TRANSPORTNETWORK.COMMONTRANSPORTELEMENTS.MARKERPOST_VISU::GEOPORTAIL:OGC:WMTS(1)&l2=BDGEODESIQUE-SITE-RBF_BDD-POI_WLD::GEOPORTAIL:OGC:WMS(1)&permalink=yes) ?

**Comment by florimondmanca** [comment]
Oui sur ma carte GeoJSON le marqueur est repris du PR1 trouvé sur le Geoportail

Ce fix résout le cas de la D978 mais le cas de la D1120 en description de ce ticket n'est pas encore totalement résolu (même si c'est moins pire)

Je pense que c'est lié au fait que la départementale est en deux morceaux disjoints... le calcul de longueur est peut-être faussé, ou le sens de numérisation n'est pas forcément le même entre les deux morceaux, ce genre de chose... je continue de creuser cette partie

**Comment by johanricher** [comment]
Ca me rappelle nos discussions sur #667 où on avait parlé du service IGN de géocodage de PR avec abscisse ([UI](https://demo-dscr.ign.fr/demonstration/geocode/), [API](https://demo-dscr.ign.fr/api/)) 

Mes questions et remarques à l'époque étaient :

> sait-on comment le service IGN effectue ce calcul "de référence" ? De même pour le géocodage inversé, il doit bien avoir une méthode sur laquelle tout le monde s'est mis d'accord. Sinon les écarts de résultats doivent être assez importants non ?

> il faut calculer le moins de choses nous-mêmes.

Compte tenu de ce bug, il me semble en effet relativement peu probable que notre méthode de calcul arrive systématiquement au même résultat qu'une autre méthode (celle de référence), sans que l'on connaisse celle-ci dans ses détails d'implémentation ! Existe-t-il une spécification technique de référence des PR / absisses ? Est-ce qu'à minima on peut accéder au code du service de l'IGN pour voir les détails d'implémentation ? @MathieuFV

**Comment by florimondmanca** [comment]
@MathieuFV Est-ce que tu sais comment je pourrais entrer en contact avec les devs de l'api "DSCR" citée par Johan pour leur demander un accès au code source du calcul des PR+abs ?

**Comment by MathieuFV** [comment]
Oui, enfin en tout cas on a des contacts à l'IGN que je peux solliciter. Je te mets en copie !

**Comment by florimondmanca** [comment]
Je propose de fermer vu qu'on a résolu le pb de sens de numérisation, ce qui devrait déjà résoudre pas mal de cas, et qu'on a isolé le cas de la D1120 ici #1032  ?
