### ISSUE TITLE
Aucun tronçon partiel ne devrait être envoyé à Waze

### ISSUE THREAD

**Issue by florimondmanca** [MTES-MCT/dialog#807]
## Comportement attendu

Waze ne reçoit via notre CIFS que des tronçons entiers, afin de maximiser les chances de mapping réussi côté Waze

## Comportement réel

Lorsqu'on saisit une localisation dont une extrémité tombe à l'intérieur d'un tronçon, ce tronçon de début ou de fin partiel est envoyé à Waze

## Contexte supplémentaire

* Refs #716 

## Pistes de résolution

On "découpe" ce tronçon dans l'algorithme de calcul de linéaire

Pour Waze, il faudrait pouvoir réobtenir ce tronçon complet et l'utiliser au lieu d'un tronçon de début/fin partiel

On pourrait passer par l'ID du tronçon.

**Comment by mmarchois** [comment]
> Pour Waze, il faudrait pouvoir réobtenir ce tronçon complet et l'utiliser au lieu d'un tronçon de début/fin partiel

Ça soulève une question quand même… Si Waze (et donc Google Map) ne tient pas compte des numéros de début / fin, à quoi bon proposer cette option ? Tout en sachant qu'elle ne pourra pas être exportée ? (à part dans le datex, mais on ne sait pas s'il est utilisé ...).

**Comment by johanricher** [comment]
Un autre exemple pour illustrer le problème.

"Arrêté temporaire ARR U 24-20" de la commune de Phalsbourg ([voir dans l'UI de DiaLog](https://dialog.beta.gouv.fr/regulations/0190497f-233f-7db2-b412-7b9417f594c3). Je n'ai pas pu vérifier l'arrêté d'origine (papier) donc je considère ici que ce qui a été saisi dans Dialog est correct.

> Circulation interdite
> Localisation : Rue De L'Arbre Vert du n° 08 au n° 10 à Phalsbourg (57370) 

La géométrie calculée est conforme à la localisation :

![image](https://github.com/MTES-MCT/dialog/assets/10212787/392b93a5-a435-430e-98e8-23a52bb3950b)

Suite à #873, la restriction est diffusée dans [l'export CIFS](https://dialog.beta.gouv.fr/api/regulations/cifs.xml) en 3 géométries et avec des `incident id` distincts.

![image](https://github.com/MTES-MCT/dialog/assets/10212787/e1d39fb6-8a0e-4b1e-b811-7c22b463cd70)

![image](https://github.com/MTES-MCT/dialog/assets/10212787/570ac9b8-1e96-4752-96d6-27d90ffafb3d)


![image](https://github.com/MTES-MCT/dialog/assets/10212787/d0f89e1d-4ea6-402c-a908-57797b726694)

Dans Waze ça donne :

![image](https://github.com/MTES-MCT/dialog/assets/10212787/84029cb6-1791-427e-b83b-9c965a4e6832)

Le référentiel de voirie de Waze n'a que 2 segments pour la rue de l'arbre vert et fait un calcul (dont la méthode nous échappe encore je pense) qui a pour résultat de rapprocher les 3 géométries diffusées par DiaLog des 2 segments Waze.

![image](https://github.com/MTES-MCT/dialog/assets/10212787/f3c2f971-41df-4688-a023-9263a38de749)

![image](https://github.com/MTES-MCT/dialog/assets/10212787/c2ff28e4-6dfa-4fc6-bf7d-84b63e93f481)

Il me semble néanmoins qu'aucun des 2 segments n'est représentatif de la vraie localisation de la restriction.

Que fait-on de ce problème ?

**Comment by florimondmanca** [comment]
Ah c'est très intéressant comme cas ! J'avais justement regardé cet arrêté juste avant qu'on réactive l'export CIFS pour les données saisies via l'UI.

On voit que notre géométrie semble déborder un peu au sud de l'intersection, ce qui fait que Waze va aller inclure la partie sud de la voie

Or si on regarde les numéros indiqués, seul le segment entre les 2 intersections devrait être concerné

En excluant les segments partiels au sud et à l'ouest, on finirait avec ce segment "entier" du milieu ce qui serait + conforme, on dirait.

**Comment by florimondmanca** [comment]
En fait je ne suis pas sûr que ce soit vraiment un "problème"...

Si une portion d'un tronçon est concernée par une restriction, ça veut en fait dire, d'un point de vue "réseau routier" / graphe, que tout ce tronçon est inaccessible, puisqu'il y a un endroit où on ne peut pas passer

Et donc du point de vue de Waze, c'est cohérent d'indiquer l'ensemble du tronçon comme concerné

Autrement dit, je pense qu'on fait déjà au mieux en envoyant à Waze la localisation la plus précise, et ensuite c'est à eux de décider de l'interprétation. (Cette logique a des limites quand Waze ferme des tronçons complètement autres par différence entre son référentiel et la BDTOPO, mais dans le cadre de ce ticket on ne parle pas de ça)

Donc je serais tenté de clore ce ticket...
