### ISSUE TITLE
Rendre publique la page qui liste les arrêtés

### ISSUE THREAD

**Issue by johanricher** [MTES-MCT/dialog#821]
## Contexte

DiaLog a vocation à rendre publiques, accessibles à tout le monde sans connexion, toutes les informations sur les arrêtés "publiés" sur DiaLog.

DiaLog dispose d'[une page qui liste les arrêtés](https://dialog.beta.gouv.fr/regulations) mais celle-ci n'est accessible qu'aux utilisateurs connectés à DiaLog.

Ce ticket vise à corriger ce problème d'UX.

## Implémentation

* Rendre publique [la page qui liste les arrêtés](https://dialog.beta.gouv.fr/regulations) (accessible sans connexion)
* Seuls les arrêtés dont l'état est "Publié" sont visibles sur cette page (les arrêtés dont l'état est "Brouillon" ne sont  visibles qu'aux utilisateurs membres de l'organisation qui les a créés)
* Les fonctionnalités d'action son retirées, notamment celles d'édition dans la colonne "Actions" sont retirées et ne fonctionnent pas sans connexion et permission (seuls les utilisateurs membres d'une organisations peuvent modifier, supprimer les arrêtés créés par cette organisation)

## Design

[Maquette](https://www.figma.com/design/YuT6Uh4wxe90U8LaPLlDzO/Dialog?node-id=5462-23276&t=oljmvqHyJryN5b8u-4)

**Comment by jjacquelinet** [comment]
J'ai l'impression en lisant le code qu'actuellement la page liste les arrêtés en filtrant par la ou les organisations de l'utilisateur connecté. 
Avec ce projet de rendre publique la page qui liste des arrêtés, il me semble que ça n'a pas de sens de réduire la liste des arrêtés lorsque l'utilisateur se connecte (utilisateur non connecté : tous les arrêtés sauf brouillons, utilisateur connecté : uniquement les arrêtés de sa ou ses organisations + les brouillons). 
Du coup, que faire ? 
 - nouvelle page publique qui liste les arrêtés, qui ne change pas lorsque l'utilisateur se connecte ou se déconnecte, maintenue en parallèle de l'existante
 - reprise de la page existante, qui, en mode utilisateur connecté, liste tous les arrêtés et ne permet les actions que sur les arrêtés dont l'utilisateur a les permissions (c'est-à-dire selon sa ou ses organisations)

**Comment by jjacquelinet** [comment]
Suite à notre point quotidien de ce mardi 18 juin 2024, on affichera sans conditions la colonne "Organisation".

**Comment by johanricher** [comment]
La page [`/regulations`](https://dialog.beta.gouv.fr/regulations/) est désormais publique et les différents critères d'acceptations ont été remplis.
