### ISSUE TITLE
Pouvoir saisir une route départementale avec "RDxxx"

### ISSUE THREAD

**Issue by florimondmanca** [MTES-MCT/dialog#833]
## Comportement attendu

Quand je saisis une localisation "route départementale", si je cherche "RD3", je vois les résultats "D30", "D31", etc.

## Comportement réel

Aucun résultat ne s'affiche car seul le préfix "D blabla" est reconnu

## Pour reproduire

- Essayer de saisir "RD..."
- Voir aucun résultat même quand "D..." avec le même numéro donne des résultats

## Contexte supplémentaire

Signalé par un utilisateur du Conseil Départemental de la Corrèze avec l'exemple "RD70"

## Pistes de résolution

Dans le traitement du terme de recherche, retirer un "R" au début s'il y en a un

**Comment by jjacquelinet** [comment]
Note pour plus tard : il est possible que la même demande soit faite pour "CD"
