### ISSUE TITLE
Intégrer les zones JOP

### ISSUE THREAD

**Issue by johanricher** [MTES-MCT/dialog#839]
## Contexte

La préfecture de police de Paris (PP) nous met à disposition des données sur les [zones JOP](https://carte.anticiperlesjeux.gouv.fr/), c'est à dire des restrictions de circulations définies dans des géométries polygones et liées à des dates de début et de fin.

On souhaite diffuser ces informations via DiaLog, donc les intégrer en base et dans l'UI, et les exporter en Datex II et CIFS.

Dépend de :
* #519

Ce qu'on prend en entrée :
* Fichier avec des événements, chaque événement porte une restriction dans une zone avec période (date de début, date de fin)

## Critères d'acceptation

* Affichage dans l'UI : 1 seul arrêté
* Diffusion en Datex II : voir ["solution envisagée"](https://github.com/MTES-MCT/dialog/issues/839#issuecomment-2175643478) ci-dessous

## Implémentation

* [ ] #847 

Prérequis:

* [ ] #840 
* [ ] #853

**Comment by johanricher** [comment]
Dans un premier temps, @florimondmanca va discuter avec @MathieuFV pour explorer les données existantes et la faisabilité de l'intégration.

Pour pouvoir mettre ce ticket en "Prêt à développer" il faut définir son périmètre (quelles données on prend en entrée) et ses critères d'acceptation (ce qu'on va produire en sortie, visible du point de vue utilisateur dans l'UI et les exports DiaLog).

**Comment by MathieuFV** [comment]
Les données de la préfecture sont ici : https://kdrive.infomaniak.com/app/drive/184671/shared-with-me/184671/54928

**Comment by MathieuFV** [comment]
Et l'exemple d'arrêté : https://dialog.beta.gouv.fr/regulations/01902aa9-2d2d-7619-8e04-134c5400a020

**Comment by florimondmanca** [comment]
## Analyse

Quel périmètre d'export ?

* Pas Waze car la PP s'occupe déjà de les mettre dans Waze via le partenariat
* => Notre rôle est surtout vis à vis de TomTom etc donc DATEX

Donc on peut se permettre de refléter dans nos données les conditions sur les véhicules

Les GPS savent ce que veut dire "Rouge", "Bleu", "Gris" donc on peut se contenter de transmettre la couleur sans inscrire dans DiaLog ce qu'elle veut dire

Les réutilisateurs doivent pouvoir identifier facilement que l'arrêté concerne les JOP, par exemple l'identifiant "JOP2024-blabla"

Un "Evénement" (ex : Village Olympique) et un "Type périmètre" (rouge, bleu, gris) donné correspondent à une même géométrie (= Location)

La géométrie sera activée  sur plusieurs périodes au cours des JOP

Stratégie d'intégration : réutiliser au max les canaux d'export existants, ça implique de créer un arrêté dans la base donc compatible avec affichage UI (pour éviter d'avoir à implémenter des cas spéciaux dans le code)

## Solution envisagée

Un script qui traite le Shapefile (1.5 Mo)

Création d'un unique arrêté "JOP2024-Zones"

* Identifiant : JOP2024-Zones
* Organisation compétente : PP de Paris (UUID : 018dcc69-123f-7d20-8f52-71c4ce9c8a8b)
* Description : Zones pour les JOP ...
* Catégorie : Evénement
* Date de début : MIN(START_DATE)
* Date de fin : MAX(END_DATE)
* Mesures : 1 mesure par couple (`EVENEMTN`, `TYPE_PERIM`)
  * Type: Circulation interdite
  * Véhicules 
    * Véhicules concernés : Tous les véhicules
    * Sauf : Autre : "Véhicules autorisés en zone $TypePerim" (ex : "sauf zone rouge") => peut être récupéré par les GPS
  * Périodes
    * 1 période par ligne en utilisant `DATE_DEBUT` et `DATE_FIN` (attention au fuseau horaire : Europe/Paris)
    * N.B. : les lignes peuvent définir des créneaux horaires qui se répètent, mais en faire des Periods plutôt que des Créneaux horaires car il peut y avoir des subtilités
  * Localisations
    * 1 localisation dont la géométrie vaut celle commune au couple (Evénement, TypePerim)
    * Créer un type "Données brutes" ? Pour ne pas avoir à remplir les champs "Voie nommée" ou "Route départementale", car on veut juste transmettre le GeoJSON

## Next steps

* PR pour ajouter le type de localisation "Données brutes"
* Commencer le script d'intégration

**Comment by florimondmanca** [comment]
@MathieuFV Dans l'UI ça donnerait ce genre de choses (je suis en train d'ajouter le type "données brutes GeoJSON" donc j'ai créé un arrêté qui ressemble à ce qu'on veut faire pour tester l'affichage)

![Screenshot 2024-06-18 at 12-23-27 Arrêté temporaire JOP2024-ZONES - DiaLog](https://github.com/MTES-MCT/dialog/assets/15911462/e011a4d5-5066-40c7-a8eb-1ee9d7007bdf)

**Comment by MathieuFV** [comment]
C'est parfait :)
