### ISSUE TITLE
Améliorer le pop up sur la carte

### ISSUE THREAD

**Issue by johanricher** [MTES-MCT/dialog#843]
## Description

Sur [la carte mise en production](https://dialog.beta.gouv.fr/carte), on souhaite améliorer le design du pop up pour améliorer la lisibilité et compréhension des informations.

Rendu actuel :

![image](https://github.com/user-attachments/assets/353bff07-3437-4b6a-882d-5da8dc1a69f0)

Il s'agit de tendre autant que possible vers la mise en forme visible sur la maquette, en apportant notamment les changements suivants  :

* Type de restriction : heading, pas d'icone
* Supprimer l'information sur la période de l'arrêté
* Supprimer l'information "L'arrêté est : en cours" ou "passé"
* "Voir les détails" : aligné à droite, en gras, bleu, sans soulignage
* Majuscule au début des phrases
* Réduire le whitespace

## Design

![image](https://github.com/user-attachments/assets/a0da0f8a-da75-4561-b293-70b5b9c2c849)

[Maquettes](https://www.figma.com/design/YuT6Uh4wxe90U8LaPLlDzO/Dialog?node-id=5950-30674&t=zu3AAiI0StOklFYf-1)

**Comment by aureliebaton** [comment]
Suite à notre discussion voilà 2 proposition de pop-up entre ce que j'avais proposé à la base et ce qui est en prod. Avez-vous des préférences / commentaires sur l'une ou l'autre ?
<img width="357" alt="Screenshot 2024-06-19 at 16 28 33" src="https://github.com/MTES-MCT/dialog/assets/85348619/158b770d-b38e-444f-aa61-46502a8d91cb">
<img width="648" alt="Screenshot 2024-06-19 at 16 28 41" src="https://github.com/MTES-MCT/dialog/assets/85348619/aba5dddb-e183-4b7e-88fc-ad8424953710">

**Comment by johanricher** [comment]
Sachant que dans DiaLog il y a des informations sur la période (dates et heures de début et fin) qui sont associées tantôt : 1) à l'arrêté ou 2) à la restriction ou 3) aux deux (cette particularité n'est pas prise en compte dans la maquette).

Par exemple : [cet arrêté](https://dialog.incubateur.net/regulations/0190317b-58da-787d-b54f-efc7fe783e2c) 
* Période arrêté : du 06/07/2024 au 27/07/2024 
* Restriction 1 (rue Gabriel Peri) : du 22/06/2024 au 28/06/2024
* Restriction 2 (rue de la République) : du 18/07/2024 au 30/07/2024

([Sur la carto](https://dialog.incubateur.net/carte#mapZoomAndPosition=13.73/48.93764/2.37776)) ça donne ça :

![image](https://github.com/MTES-MCT/dialog/assets/10212787/53d6874a-ea08-41cd-bafd-5696745b6bc9) ![image](https://github.com/MTES-MCT/dialog/assets/10212787/70683666-88d6-470b-97bf-622f85d8fee5)

Pour avancer je propose de continuer à discuter tout ça de façon holistique avant de mettre ce ticket en "prêt à développer". Mon avis personnel serait dans un premier temps de :

* Supprimer dans le pop up carto l'affichage de la période de l'arrêté qui est inutile (et continuer la discussion ici https://github.com/MTES-MCT/dialog/issues/701#issuecomment-2179198142 pour décider si on supprime totalement la notion de période d'arrêté).
* Tendre autant que possible vers la mise en forme visible sur la maquette notamment :
  * Version avec les icones
  * Heading (lequel) sur le type de restriction
  * "Voir les détails" aligné à droite, en gras, bleu sans soulignage
  * Moins de whitespace

De manière générale cela me pose problème que la mise en forme des infos sur la restriction dans le pop up diffère de celle sur la page de l'arrêté, car **le pop up ne doit être qu'une version synthétique de la même information publique** :
* Terminologie : dispositif, mesure... utilisons partout "restriction" qui est le seul compris universellement
* Gras sur certains éléments dans le pop up, pas sur la page
* Julien a introduit le fait que soit explicité que "L'arrêté est : à venir/passé", on a ainsi cette info plus rapidement qu'en regardant la date, c'est donc pas complètement redondant mais je m'en remets in fine à ton avis pour trancher sur le fait de la garder ou pas @aureliebaton

**Comment by aureliebaton** [comment]
> Julien a introduit le fait que soit explicité que "L'arrêté est : à venir/passé", on a ainsi cette info plus rapidement qu'en regardant la période de la restriction, c'est donc pas complètement redondant mais je m'en remets in fine à ton avis pour trancher sur le fait de la garder ou pas @aureliebaton.

Je pense effectivement qu'on peut retirer de la pop-up "L'arrêté est : à venir/passé", on a déjà l'info avec la date et ça ajoute encore une info de plus dans la pop up. D'autant plus que comme ça a été dit la date de l'arrêté n'est pas forcément la même que celle de la mesure : l'arrêté peut par exemple être "en cours" mais la restriction peutêtre déjà terminée.

**Comment by aureliebaton** [comment]
La dernière maquette de la pop-up est ici https://www.figma.com/design/YuT6Uh4wxe90U8LaPLlDzO/Dialog?node-id=5950-30674&t=zu3AAiI0StOklFYf-1


![Image](https://github.com/user-attachments/assets/943df94a-65a9-4c20-bd6d-2f67ccee79f1)

**Comment by johanricher** [comment]
J'ai mis à jour la description du ticket pour refléter l'aboutissement de l'exploration, c'est prêt à développer.
