### ISSUE TITLE
Mettre à jour la barre de navigation

### ISSUE THREAD

**Issue by johanricher** [MTES-MCT/dialog#858]
## Description

Suite à la mise en ligne des pages publiques [`/carte`](https://dialog.beta.gouv.fr/carte) (nouvellement créée) et [`/regulations`](https://dialog.beta.gouv.fr/regulations) ("listing des arrêtés", anciennement privée), quand celles-ci auront répondu à différents critères d'acceptation, on souhaitera rendre ces pages découvrables via [la barre de navigation](https://www.systeme-de-design.gouv.fr/composants-et-modeles/composants/navigation-principale) dans [l'en-tête](https://www.systeme-de-design.gouv.fr/composants-et-modeles/composants/en-tete) du site.

Dans un même temps on met à jour la page d'accueil pour augmenter encore davantage la découvrabilité des informations publiées par DiaLog :
* #763

## UI

* Utilisateur déconnecté ([maquette de référence](https://www.figma.com/design/YuT6Uh4wxe90U8LaPLlDzO/Dialog?node-id=6854-27885&t=lStTZaulGm8NCmhI-4)) :

<img width="664" alt="Screenshot 2024-10-22 at 08 14 21" src="https://github.com/user-attachments/assets/30de8b46-1031-49e7-bfa4-bb19a89bc727">

* Utilisateur connecté ([maquette de référence](https://www.figma.com/design/YuT6Uh4wxe90U8LaPLlDzO/Dialog?node-id=6855-35875&t=lStTZaulGm8NCmhI-4)) :

![image](https://github.com/user-attachments/assets/486f2ea6-52c5-439a-812f-b616ba43deb2)

**Comment by johanricher** [comment]
Pour l'instant on ajoute seulement un lien vers la page /carte dans la barre. Maquette à mettre à jour

**Comment by aureliebaton** [comment]
Au final les onglets de la page d'accueil peuvent rester tels qu'à l'heure actuelle comme dans les dernières maquettes https://www.figma.com/design/YuT6Uh4wxe90U8LaPLlDzO/Dialog?node-id=6854-27885&t=pkj7hYVCPPzuGsWo-1

**Comment by johanricher** [comment]
Suite à la discussion d'aujourd'hui :

En mode déconnecté ajout du bouton "Arrêté de circulation" (le même que dans le même connecté)

**Comment by aureliebaton** [comment]
Une autre précision, quand on se connecte, on arrive directement sur la page arrêtés de circulation.
