### ISSUE TITLE
Arrêtés saisis dans DiaLog pas présents dans le CIFS

### ISSUE THREAD

**Issue by florimondmanca** [MTES-MCT/dialog#873]
## Comportement attendu

Les arrêtés saisis par des collectivités directement via l'interface utilisateur de DiaLog apparaissent dans le flux CIFS (si elles remplissent les conditions CIFS : tous véhicules, etc)

## Comportement réel

Le CIFS est entièrement vide

## Pour reproduire

https://dialog.beta.gouv.fr/api/regulations/cifs.xml

## Contexte supplémentaire

On avait désactivé tout exposition de données dans le CIFS lorsqu'on s'est rendu compte des problèmes d'horaires Eudonet (#812)

## Pistes de résolution

Une variable d'environnement permet de définir dynamiquement (sans modif dans le code) ce qui est exposé ou pas dans le CIFS.

À ce jour en prod elle vaut :

```dotenv
APP_CIFS_FILTERS='{"allowed_sources": ["none"]}'
```

En principe il suffit de mettre à jour la variable d'environnement pour autoriser la source DiaLog :

```dotenv
APP_CIFS_FILTERS='{"allowed_sources": ["dialog"]}'
```

**Comment by florimondmanca** [comment]
J'ai réactivé la source `dialog`

https://dialog.beta.gouv.fr/api/regulations/cifs.xml

Les restrictions correspondantes devraient donc bientôt être traitées par Waze

Par exemple une portion de la Rue de l'Arbre Vert à Phalsbourg (57370), valable du 30 juin au 14 juillet

À surveiller mais je clos déjà ce ticket, les données UI sont de retour dans le CIFS  :+1:

**Comment by johanricher** [comment]
Je ne trouve pas dans le CIFS la restriction correspondant à [l'entrée "Arrêté temporaire 2024-049" de la commune de Noyarey dans DiaLog](https://dialog.beta.gouv.fr/regulations/01902bac-dce1-7d0d-9aea-21c48cb397e8). Tu saurais me dire pourquoi @florimondmanca ? Je suppose que quelque chose d'évident m'échappe, sinon je créerais un ticket dédié.

**Comment by florimondmanca** [comment]
@johanricher C'est le "sauf vélos et piétons"

**Comment by johanricher** [comment]
Je me disais bien qu'un détail m'avait échappé. :) Merci !
