### ISSUE TITLE
Encodage des données JO

### ISSUE THREAD

**Issue by delhomer** [MTES-MCT/dialog#875]
Ticket lié : #839

Hello l'équipe Dialog, je vous contacte comme on est dans la dernière ligne droite de l'implémentation d'une appli de calcul d'itinéraire pour le contexte JO.

Je me pose une question sur le format des données relatives aux arrêtés JO...

## Comportement attendu

Les restrictions apportées par l'ordre de régulation lié aux JO s'appliquent pour la période et la localisation indiquée, et on a une exception pour les véhicules d'urgence.

Donc l'option `negate` dans le modèle ne doit être à `True` que pour les véhicules d'urgence.

## Comportement réel

On a aujourd'hui deux spécifications de véhicules : les véhicules d'urgence et le cas général, et dans les deux cas, l'option `'negate' = True` semble indiquer des exceptions.

## Pour reproduire

Script Python à jouer : 

```python
from pathlib import Path
import urllib.request
import xmlschema


# URL to the XML Schema Definition (XSD) used by DiaLog data
XSD_URL = "https://datex2.eu/schema/3/d2Payload/DATEXII_3_D2Payload.xsd"
SUBSCHEMA_URLS = [
    "http://datex2.eu/schema/3/locationExtension/DATEXII_3_LocationExtension.xsd",  # noqa: E501
    "http://datex2.eu/schema/3/commonExtension/DATEXII_3_CommonExtension.xsd",  # noqa: E501
    "http://datex2.eu/schema/3/parking/DATEXII_3_Parking.xsd",
    "http://datex2.eu/schema/3/vms/DATEXII_3_Vms.xsd",
    "http://datex2.eu/schema/3/trafficRegulation/DATEXII_3_TrafficRegulation.xsd",  # noqa: E501
    "http://datex2.eu/schema/3/situation/DATEXII_3_Situation.xsd",
    "http://datex2.eu/schema/3/roadTrafficData/DATEXII_3_RoadTrafficData.xsd",
    "http://datex2.eu/schema/3/facilities/DATEXII_3_Facilities.xsd",
    "http://datex2.eu/schema/3/energyInfrastructure/DATEXII_3_EnergyInfrastructure.xsd",  # noqa: E501
    "http://datex2.eu/schema/3/locationReferencing/DATEXII_3_LocationReferencing.xsd",  # noqa: E501
    "http://datex2.eu/schema/3/common/DATEXII_3_Common.xsd",
]
XML_DIR = Path.cwd() / "xml"
Path.mkdir(XML_DIR, exist_ok=True)
for url in SUBSCHEMA_URLS:  # load all schema resources
    xsd_filename = url.split("/")[-1]
    urllib.request.urlretrieve(url, XML_DIR / xsd_filename)
schema_xsd = urllib.request.urlopen(XSD_URL).read()
schema = xmlschema.XMLSchema(schema_xsd, base_url=XML_DIR)

# URL to DiaLog XML data
DIALOG_XML_URL = "https://dialog.beta.gouv.fr/api/regulations.xml"
xml_filename = DIALOG_XML_URL.split("/")[-1]
urllib.request.urlretrieve(DIALOG_XML_URL, XML_DIR / xml_filename)
data_dict = schema.to_dict(str(XML_DIR / xml_filename), validation="lax")

arretes_jo = data_dict[0]["trafficRegulationsFromCompetentAuthorities"]["trafficRegulationOrder"][255]["trafficRegulation"]

for measure_idx, measure in enumerate(arretes_jo):
    print(f"............Mesure JO N°{measure_idx=}............")
    condition_set = measure["condition"]["conditions"]
    for condition in condition_set:
        print("CONDITION TYPE:", condition["@xsi:type"])
        if condition["@xsi:type"] == "ConditionSet":
            for subcondition in condition["conditions"]:
                print(subcondition.keys(), subcondition["@xsi:type"])
                if subcondition["@xsi:type"] == "VehicleCondition":
                    print("=== VEHICLE ===>", subcondition)
    break
```

Sortie console :  

```bash
16:36 $ python roles/dialog/files/standalone_import.py 
............Mesure JO N°measure_idx=0............
dict_keys(['@xsi:type', 'validityByOrder']) ValidityCondition
dict_keys(['@xsi:type', 'locationByOrder']) LocationCondition
dict_keys(['@xsi:type', 'negate', 'vehicleCharacteristics']) VehicleCondition
=== VEHICLE ===> {'@xsi:type': 'VehicleCondition', 'negate': True, 'vehicleCharacteristics': {'com:vehicleUsage': 'emergencyServices'}}
dict_keys(['@xsi:type', 'negate', 'vehicleCharacteristics']) VehicleCondition
=== VEHICLE ===> {'@xsi:type': 'VehicleCondition', 'negate': True, 'vehicleCharacteristics': {'com:_vehicleCharacteristicsExtension': {'com:vehicleCharacteristicsExtended': None}}}
```

## Pistes de résolution

Passer le champ `negate` à  `False` pour les véhicules hors-urgence ?

Note : il y a peut-être un aspect que j'ai mal compris là-dedans, si c'est le cas, je suis preneur de vos lumières !

À ce stade du calendrier (à l'approche des JO), on va sûrement opter pour patcher notre code pour traiter l'ordre de régulation JO à part. Est-ce que vous pensez que ce point est susceptible d'évoluer dans le mois qui vient ? (Ce qu'on veut éviter : qu'un changement du modèle de donnée casse notre parser juste avant les JO...).

**Comment by florimondmanca** [comment]
Bonjour @delhomer 

Le `<negate>true</negate>` décrit effectivement une exemption de véhicule concernée, dans le sens "tels véhicules SAUF tels véhicules"

Dans l'arrêté JOP2024-ZONES, il y a certes les exemptions pour véhicules d'urgence, mais nous utilisons également une exemption pour indiquer la zone concernée (rouge / bleue / etc)

```xml
<conditions xsi:type="VehicleCondition">
  <negate>true</negate>
  <vehicleCharacteristics>
    <com:_vehicleCharacteristicsExtension>
      <com:vehicleCharacteristicsExtended>
        <dx:otherVehicleType>Zone Rouge</dx:otherVehicleType>
      </com:vehicleCharacteristicsExtended>
    </com:_vehicleCharacteristicsExtension>
  </vehicleCharacteristics>
</conditions>
```

Dans l'output de votre script vous ne voyez pas la valeur mais je pense que c'est parce que vous utilisez le schéma XML de base de DATEX alors que nous avons produit une "extension" pour pouvoir indiquer quel est le type "autre" de véhicule concerné / exempté

Vous pouvez essayer d'utiliser nos fichiers de schémas stockés dans ce dossier ? https://github.com/MTES-MCT/dialog/tree/main/docs/spec/datex2

**Comment by delhomer** [comment]
Merci @florimondmanca pour la réponse rapide !

Je vais jeter un coup d'oeil à ce schéma, effectivement on a raté cette partie-là, ça devrait permettre d'avoir conscience de cette notion de zone rouge/bleue.

Et donc, si je comprends bien, dans le cas où on n'a qu'une (ou plusieurs) exceptions, il faut déduire que le cas général est une restriction. Je m'attendais (sans doute naïvement) à ce que le cas général soit indiqué explicitement dans la donnée en tant que restriction (avec le `'negate' = False`).

**Comment by florimondmanca** [comment]
Non effectivement, au sein d'une même `trafficRegulation` il peut y avoir une combinaison de conditions avec `negate = false` (ou omis) et `negate = true`.
