### ISSUE TITLE
L'intégration Eudonet devrait renvoyer toutes les erreurs rencontrées

### ISSUE THREAD

**Issue by florimondmanca** [MTES-MCT/dialog#877]
## Comportement attendu

Le log d'Eudonet contient toutes les erreurs rencontrées lors du traitement des données récupérées dans l'API

## Comportement réel

Il ne contient que certaines erreurs car on s'arrête dès qu'on rencontre des erreurs dans le traitement d'une mesure ou d'une localisation

## Contexte supplémentaire

* Participe à #813 

## Pistes de résolution

Modifier le `EudonetParisTransformer` pour accumuler les `$errors` et les loguer toutes à la fin, au lieu de faire un early `return`

**Comment by johanricher** [comment]
Suite à [la réunion du 30/07](https://pad.incubateur.net/#2024-07-30---Point-tech-erreurs-Eudonet), la PR #908 a permis d'améliorer le log existant avec l'ajout de :
* Nombre total d’arrêtés dans la base Eudonet
* Nombre total de mesures dans la base Eudonet

sous la forme suivante :

```
        "numberOfRegulationsInsideEudonet": 33832,
        "numberOfMeasuresInsideEudonet": 62909
```

([source](https://github.com/MTES-MCT/dialog/actions/runs/10355912333))

Pour la suite, on décide de rapprocher le script d'import Eudonet de celui en cours d'écriture pour Littéralis (cf. #658) qui bénéficie des dernières réflexions sur les rapports d'erreur.

Par conséquent, en parallèle des travaux de Florimond sur Littéralis qui proposent une nouvelle structure de log avec une section pretty print (cf. #874), Julien continue les travaux sur l'amélioration du log Eudonet :

* le log ne s'arretera pas à la première erreur rencontrée pour un arrêté
* section pretty print

La mutualisation est en cours du système de log (`Reporter`). Néanmoins à plus long terme il reste à explorer la faisabilité de davantage de mutualisation, car il peut exister des différences entre les sources de données (on parle notamment d' "emprise" côté Littéralis).

**Comment by florimondmanca** [comment]
La partie "reporter" de mon code dans #874 est normalement décorrélée des spécificités Litteralis, les différentes méthodes acceptent un `$context` et c'est côté extractor/transformer/etc qu'on y passe les infos spécifiques Litteralis comme l'ID de l'emprise où l'erreur a été rencontrée.

**Comment by johanricher** [comment]
Après réflexion, on ne juge pas pertinent de continuer à investir du temps sur Eudonet, y compris sur ce sujet d'amélioration du rapport d'erreurs.
