### ISSUE TITLE
La carte ne se charge pas

### ISSUE THREAD

**Issue by johanricher** [MTES-MCT/dialog#881]
## Comportement attendu

Sur [la page `https://dialog.beta.gouv.fr/carte`](https://dialog.beta.gouv.fr/carte), la carte se charge :

![image](https://github.com/user-attachments/assets/726d2eba-daf5-4281-8b92-bc742fdaf508)

## Comportement réel

Sur [la page `https://dialog.beta.gouv.fr/carte`](https://dialog.beta.gouv.fr/carte), la carte ne se charge pas :

![image](https://github.com/user-attachments/assets/9d52b14b-6131-4a30-92ef-73bfe8f8c52d)

## Pour reproduire

Aller sur https://dialog.beta.gouv.fr/carte

## Contexte supplémentaire

Sur staging la page se charge https://dialog.incubateur.net/carte

**Comment by jjacquelinet** [comment]
À noter que le message d'erreur `Refused to apply a stylesheet because its hash, its nonce, or 'unsafe-inline' does not appear in the style-src directive of the Content Security Policy.` dans la console JavaScript s'affiche même lorsque la carte se charge, il n'est donc pas lié à notre bug.

**Comment by jjacquelinet** [comment]
Les logs de Scalingo ne montrent pas de différence entre `staging` et `prod`

**Comment by mmarchois** [comment]
@jjacquelinet regarde peut-être la sortie de l'API voir s'il y a une différence entre celle du staging et celle de la prod

**Comment by jjacquelinet** [comment]
@mmarchois tu parles de `/carte/data.geojson` ? Ça se charge bien côté `prod`, mais il y a évidemment des différences avec `staging` dans le contenu vu que les données ne sont pas les mêmes. 
Peut-être une mauvaise donnée dans le geojson ?

**Comment by jjacquelinet** [comment]
Je viens de faire l'import des données de prod (le `data.geojson`) dans ma carte de dev local, et ça fonctionne, la piste d'une mauvaise donnée dans le geojson de `prod` s'éloigne …

**Comment by mmarchois** [comment]
@jjacquelinet  Intéressant : sur tout nouveau déploiement, la carte ne fonctionne plus et je me demande si ce n'est pas lié à une montée de version d'une dépendance JS.
https://github.com/MTES-MCT/dialog/pull/888
https://dialog-staging-pr888.osc-fr1.scalingo.io/carte#mapZoomAndPosition=5/47.16/2.73

**Comment by mmarchois** [comment]
Nouvelle piste de recherche : je remarque que les hooks de post déploiement échouent ... 

![image](https://github.com/user-attachments/assets/b4ff1e67-8901-4ea2-81a1-ae0feff44aeb)

**Comment by mmarchois** [comment]
Après un déploiement sur staging, la carte s'affiche correctement ...

**Comment by florimondmanca** [comment]
_Réflexion à voix haute_

Différences constatées entre la prod et staging:

* Volume des données sur `/carte/data.geojson` : 5 ko (staging) vs 7 Mo (prod) dézippé
  * Les 2 requêtes à cet endpoint sont en 200 OK, mais maplibre aurait-il un problème de traitement ?
  * Les données GeoJSON sont bel et bien chargées _avant_ qu'on révèle la carte en retirant son attribut `hiden`. D'ailleurs si on retire cet attribut dans le DOM la carte s'affiche (mais elle est vide).
* Il y a 2 requêtes à data.geopf.fr en + faites côté staging
  * GET https://data.geopf.fr/tms/1.0.0/PLAN.IGN/5/17/10.pbf
  * GET https://data.geopf.fr/tms/1.0.0/PLAN.IGN/5/17/11.pbf
  * Ce sont des appels à  [l'API TMS](https://geoservices.ign.fr/documentation/services/services-geoplateforme/diffusion#70064) faits par Maplibre (en tout cas pas explicitement par nous)
* En prod, manipuler les filtres n'a aucun effet, alors que ça devrait déclencher des nouvelles requêtes à `/carte/data.geojson` -> suggère que le JS plante
  * Mais on ne voit pas d'erreur dans la console web
  * Peut-être lié à l'absence de `.catch()` dans l'utilisation de `Promise`

**Comment by florimondmanca** [comment]
La carte est de retour ;-)

https://dialog.beta.gouv.fr/carte
