### ISSUE TITLE
Pouvoir récupérer l'URL publique d'un arrêté dans le flux DATEX

### ISSUE THREAD

**Issue by vparpoil** [MTES-MCT/dialog#884]
Bonjour, 
Les identifiants présents dans le [flux XML](https://dialog.beta.gouv.fr/api/regulations.xml) ne permettent pas de reconstruire l'URL de la page publique de l'arrêté.
Par exemple pour cet arrêté du flux :
```xml
<trafficRegulationOrder id="018fbaef-0b07-75a5-801e-996dc67f86f5" version="1">
    <description>
        <com:values>
            <com:value>modifiant, à titre provisoire, les règles de circulation quai des Orfèvres à Paris Centre</com:value>
        </com:values>
    </description>
    <issuingAuthority>
        <com:values>
            <com:value>Ville de Paris</com:value>
        </com:values>
    </issuingAuthority>
    <regulationId>2023T111410#018b60cd-c261-7619-af21-15913eeac249</regulationId>
```

Nous aimerions pouvoir reconstruire l'URL de l'arrêté qui est la suivante : https://dialog.beta.gouv.fr/regulations/018fbaef-0b07-75a5-801e-996dc76e5905

Mais les identifiants ne correspondent pas (meme si l'`id` de l'url est étonnamment proche de l'`id` de `trafficRegulationOrder`).

Pensez vous qu'il soit possible de permettre cela ? 

Le cas d'usage consiste à renvoyer l'utilisateur sur la donnée officielle source quand l'utilisateur souhaite obtenir plus de détails
Merci,

**Comment by florimondmanca** [comment]
Bonjour @vparpoil, merci pour ce signalement

Ce problème est lié à #636. En bref c'est en fait l'ID dans l'URL /regulations/... qui n'est pas cohérent avec ce que nous utilisons dans `<trafficRegulationOrder id="...">`.

> (meme si l'id de l'url est étonnamment proche de l'id de trafficRegulationOrder)

Pour info c'est lié à notre utilisation d'[UUID v7](https://uuid7.com/), qui génère des UUIDs chronologiques

> Le cas d'usage consiste à renvoyer l'utilisateur sur la donnée officielle source quand l'utilisateur souhaite obtenir plus de détails

Merci bcp pour cette formulation en cas d'usage. Ça me fait dire qu'une autre possibilité serait d'inclure explicitement une `url` dans le flux DATEX. Cela me semblerait encore plus facile / direct / robuste que de devoir reconstruire l'URL côté client. Qu'en pensez-vous ?

**Comment by vparpoil** [comment]
En effet, une URL présente dans le flux Datex répond à mon cas d'usage. 
Merci
