### ISSUE TITLE
[JOP] Les périmètres SILT autour des sites olympiques hors ponts et cérémonies sont manquants

### ISSUE THREAD

**Issue by vparpoil** [MTES-MCT/dialog#887]
## Comportement attendu

On devrait retrouver toute la place de la Concorde dans les linéaires fournis pour la zone grise Concorde. 
Ci joint une copie d'écran de Anticiper les jeux
<img width="989" alt="Capture d’écran 2024-07-18 à 15 51 38" src="https://github.com/user-attachments/assets/4f5f283f-3ab2-4d3b-b493-e46d5ffc3952">

## Comportement réel

La zone grise fournie dans le flux Dialog ne concerne que les voies en bord de seine, il semble donc manquer une partie 

<img width="1012" alt="Capture d’écran 2024-07-18 à 15 53 01" src="https://github.com/user-attachments/assets/eb70d6cb-49f1-4fca-829c-4cf82255a9bf">

**Comment by florimondmanca** [comment]
@vparpoil Dans les données nous avons 4 types de zones : rouge, bleu, gris, et blanc. Il y a 19 périmètres gris et 19 périmètres blancs. Est-ce que ces périmètres blancs (par ex Notre-Dame) correspondent aux périmètres SILT manquants ?

**Comment by florimondmanca** [comment]
Je m'avoue un peu perdu.

Je n'arrive pas à faire la correspondance entre "zone grise/blanche" dans nos données est la carte interactive.

Déjà, il n'est pas clair si on a ou pas les périmètres SILT dans les données de la PP, ceux qui s'affichent en noir sur la carte interactive.

Ensuite la carte interactive affiche les "sites olympiques" en gris, je crois comprendre que ça correspond aux "zones grises" dans les données PP mais je n'en suis pas certain. Car comme vous le signalez sur la Place de la Concorde on n'a que les bords de Seine et pas la place elle-même.

Je dois regarder tout ça à tête reposée, en visualisant le contenu des données sources de la PP pour vérifier ces hypothèses de correspondance.

**Comment by vparpoil** [comment]
Si ca peut aider, voici une autre viz avec toutes les couches superposées (qui ne dépend pas de la date), alimentée par Interlud+ : https://www.joptimiz.green/visualiz

**Comment by florimondmanca** [comment]
Bonjour @vparpoil 

Pour revenir sur ce sujet, (désolé du délai), en regardant notre carte (non répertoriée pour l'instant) qui montre les restrictions à Concorde, il y a bien les restrictions "zone grise" qui couvrent la place de la Concorde

![Screenshot 2024-08-22 at 10-09-00 Carte - DiaLog](https://github.com/user-attachments/assets/e7437f31-6ee4-42dc-8668-5b919cb9c41d)

Cela correspond aux données dans le flux DATEX où `locationDescription` vaut "CEREMONIE D'OUVERTURE a jour"

Peut-être y a-t-il eu un correctif dans nos données entre temps

Est-ce que cela résout ce ticket ?

**Comment by vparpoil** [comment]
La copie d'écran ne correspond qu'a des données liées à la cérémonie d'ouverture (dont les données sont outdated de toute façon).

Ce sont les périmètres SILT autour des sites olympiques qui sont manquants, cf cette zone grise au village olympique
<img width="788" alt="Capture d’écran 2024-08-22 à 10 36 19" src="https://github.com/user-attachments/assets/1fb0f1f5-c52a-4a7b-81ab-b5bd4b641b81">

**Comment by florimondmanca** [comment]
OK merci, en relisant je vois que vous l'aviez déjà signalé, j'ai mis à jour le titre du ticket

**Comment by florimondmanca** [comment]
@vparpoil Si j'en crois la légende de la caret AnticiperLesJeux, la zone représentée en gris sur ce screenshot est un "site de compétition" et non pas un périmètre SILT (qui sont représentés en noir)

Il n'en reste pas moins qu'on devrait constater une "zone grise" dans les données DiaLog à cet endroit

En regardant nos données GeoJSON, côté village olympique on n'a effectivement que les zones bleues/rouges

Donc les zones grises de ce site sont manquantes dans les données que la PP nous a fournies...

@MathieuFV Peut-on leur demander un fichier à jour ?
