### ISSUE TITLE
Certaines autoroutes sont marquées comme fermées car elles traversent les zones bleues/rouges/grises des JOP

### ISSUE THREAD

**Issue by vparpoil** [MTES-MCT/dialog#896]
L'autoroute A1 et le périphérique parisien ne devraient pas faire partie des filaires communiqués dans le flux Dialog comme étant interdits à la circulation.

Les zones à vérifier pour le périphérique sont les suivantes : zones bleues et rouges 
- du parc des princes, 
- de roland garros, 
- de porte de versailles et 
- de porte de la chapelle

Concernant l'autoroute A1, c'est à proximité du village olympique

Ci joint deux copies d'écran des deux zones Roland Garros
<img width="1068" alt="Capture d’écran 2024-07-24 à 13 22 13" src="https://github.com/user-attachments/assets/4c04a979-a0fa-4fa8-8518-b0f21e557e51">
<img width="1035" alt="Capture d’écran 2024-07-24 à 13 23 08" src="https://github.com/user-attachments/assets/5f4214ed-36ee-4e3e-9f13-640fa783a84b">

Je suppose que la projection des zones sur le filaire doit être modifiée pour retirer les axes routiers qui ont une certaine taille

Cela est bloquant car les calculateurs d'itinéraires basés sur Dialog vont envoyer les utilisateurs sur des chemins de traverses alors que ces axes majeurs restent ouverts.

**Comment by florimondmanca** [comment]
Merci @vparpoil pour ce signalement

En effet la logique actuelle est de récupérer tous les tronçons de route que la BD TOPO connaît qui tombent dans les zones JOP

Il faudrait n'inclure que certains types de tronçons en utilisant le champ `nature`.

Valeurs possibles : Bac ou liaison maritime | Bretelle | Chemin | Escalier | Rond-point | Route à 1 chaussée | Route à 2 chaussées | Route empierrée | Sentier | Type autoroutier

Je pense qu'on devrait être le plus explicite possible. On pourrait sélectionner `Route à 1 chaussée, Route à 2 chaussées, Rond-point`. Qu'en penses tu @johanricher ?

**Comment by johanricher** [comment]
Et à l'inverse si on excluait des restrictions seulement les tronçons avec une nature qui correspond à l'emprise du périphérique, des autoroutes ? Est-ce qu'on obtiendrait un résultat fiable, c'est à dire correspondant réellement à la règlementation en vigueur ? 

Quelle est la nature des tronçons de route du boulevard périphérique dans la BD TOPO ?

Est-ce qu'on sait si les bretelles d'accès dans les zones rouges sont aussi restreintes à la circulation ou pas ?

**Comment by florimondmanca** [comment]
> L'autoroute A1 et le périphérique parisien ne devraient pas faire partie des filaires communiqués dans le flux Dialog comme étant interdits à la circulation.

@vparpoil À noter, les données JOP incluses dans notre flux DATEX ne sont pas à interpréter comme "fermetures à la circulation". Nous incluons le type de zone (grise, bleue ou rouge) et la charge est au réutilisateur de déterminer comment l'interpréter. En effet certains réutilisateurs pourraient vouloir interpréter une interdiction de circulation pour une zone rouge, et d'autres non (une zone rouge étant une zone à circulation motorisée interdite sauf laissez-passer).

Par contre on est d'accord, au niveau de Roland Garros par exemple, la [carte interactive officielle](https://anticiperlesjeux.gouv.fr/carte-interactive-impacts-deplacements-ile-france) ne comporte pas de zone bleue/rouge, mais seulement des zones grises (sites de compétition) et des [voies olympiques / itinéraires olympiques](https://anticiperlesjeux.gouv.fr/etapes-cles/voies-olympiques-paralympiques-routes) (le périphérique n'est pas fermé, mais une voie est dédiée à la circulation olympique)

**Comment by vparpoil** [comment]
Bonjour, 
Il existe une zone bleue et une zone rouge mais uniquement à certaines dates/heures
<img width="1018" alt="Capture d’écran 2024-07-29 à 15 21 41" src="https://github.com/user-attachments/assets/0d49c1a0-a89f-4d9c-a645-557cee156b73">

Je ne suis pas d'accord avec votre analyse de laisser cela à la charge du réutilisateur : les données originales fournies par la prefecture sont des polygones et cela a été transcrit en filaire pour l'exposer dans le flux dialog. 
La projection sur les routes que vous en avez faite ne me semble pas fidèle à la réalité du terrain puisque les autoroutes et le périphérique ne sont pas concernées par les restrictions des zones bleues et rouges.
Qu'en pensez vous ?

**Comment by florimondmanca** [comment]
Oui effectivement je n'avais pas pensé à manipuler les filtres temporels.

C'est bien ces deux zones rouge et bleu que nous avons dans nos données source de la PP.

Auriez-vous la source sur le fait qu'autoroutes et périphérique ne sont pas concernés ? Cela semble logique et sur ces voies il semble que ça soit des voies réservées qui ont été mises en place, mais je me demande s'il y a aussi d'autres types de routes concernées par cette spécificité

**Comment by vparpoil** [comment]
Ces sites me semblent montrer que la circulation reste possible sur ces routes (hors des voies réservées bien sur) : 
https://www.dir.ile-de-france.developpement-durable.gouv.fr/les-conditions-de-circulation-pendant-les-jeux-le-a1743.html
https://www.paris.fr/pages/perimetres-de-securite-et-circulation-pendant-les-jeux-comment-ca-marche-25203#acces-au-boulevard-peripherique

**Comment by florimondmanca** [comment]
Merci

Dans le 1er lien je crois comprendre que les autoroutes ne ferment pas, mais certaines bretelles oui

On devrait donc garder les tronçons de nature "bretelle" qui sont présents dans les polygônes

Dans le 2e lien, ça semble très clair qu'il faut exclure le périphérique des zones rouges/bleues
Ligne 1756
> Aucune porte ne sera fermée pendant les Jeux. On pourra accéder librement au boulevard périphérique (y compris à proximité de sites de compétition : Porte de Versailles, Porte de la Chapelle). [Une voie dédiée sur le périphérique sera réservée aux organisateurs](https://anticiperlesjeux.gouv.fr/etapes-cles/voies-olympiques-paralympiques-routes).

@johanricher Dans la BD TOPO les tronçons du périphérique sont de nature "Type autoroutier"

On peut le voir sur Geoportail : le périphérique apparaît en violet ce qui est légendé comme "Autoroute" https://www.geoportail.gouv.fr/carte

**Comment by johanricher** [comment]
Ok donc en excluant seulement les tronçons de nature "Type autoroutier", on devrait correspondre à la règlementation.

En tout cas on n'est pas les premiers à avoir des ambiguités et incohérences dans les informations diffusées par la PP et la DGITM (ministère des transport).

D'après [Le monde](https://www.lemonde.fr/les-decodeurs/article/2024/07/26/jo-2024-le-guide-de-la-circulation-a-paris-avant-et-pendant-les-jeux_6236285_4355771.html) : la PP a "assuré que [ces cartes](https://www.prefecturedepolice.interieur.gouv.fr/mission/des-jeux-securises-pour-tous/les-perimetres-de-securite-autour-des-sites-olympiques-et-paralympiques) ont valeur juridique" (???) et "les cartes diffusées par la PP et celles du ministère sont censées avoir la même source, mais présentent des incohérences."

Idéalement il faudrait reprendre à la source les textes qui sont seuls à avoir une quelconque valeur juridique.

Je n'ai retrouvé que le [décret](https://www.legifrance.gouv.fr/loda/id/LEGIARTI000048497172/) qui définit le périmètre gris ("SILT") mais rien pour le périmètre rouge.

**Comment by florimondmanca** [comment]
@vparpoil Bonjour, je viens de mettre à jour les données JOP, les tronçons autoroutiers (périphérique parisien et autoroutes) sont désormais exclus

Exemple au niveau de Roland Garros :

![Screenshot 2024-08-05 at 16-00-22 Carte - DiaLog](https://github.com/user-attachments/assets/2b5729fe-f504-4639-902f-7a752b2fefc3)
