### ISSUE TITLE
Améliorer les filtres de la vue liste

### ISSUE THREAD

**Issue by johanricher** [MTES-MCT/dialog#902]
## Contexte

La page https://dialog.beta.gouv.fr/regulations, également appelée "vue liste", permet de naviguer dans tous les arrêtés dont l'état est "Publié" dans DiaLog (pour tout le monde, y compris hors connexion), et ceux dont l'état est "Brouillon" (seulement pour les utilisateurs membres de l'organisation qui les a créés).

Le 11/07 les fonctionnalités ["Filtres & barres de recherche" ont été priorisés dans la feuille de route UI/UX.](https://mattermost.incubateur.net/betagouv/pl/axji4jgdjfymfcas8tcmxarbby). En parallèle, l'exploration sur la recherche continue de façon plus globale (cf. #202). A court terme on souhaite résoudre les irritants en continuant à implémenter des améliorations sur la page telle qu'elle est actuellement.

## Description

Le souhait est que les utilisateurs aient plus de possibilités pour filtrer les restrictions affichées sur la vue liste.

Il s'agit de :

* Ajouter filtre "Identifiant"
* Ajouter filtre "Organisation"
* Ajouter filtre "Statut"
* Modifier filtre "Type" (remplace le filtre par onglet actuel)

## Design

![image](https://github.com/user-attachments/assets/21b51a11-26ca-4d04-8a00-6247ccd4614b)

[Maquette de référence](https://www.figma.com/design/YuT6Uh4wxe90U8LaPLlDzO/Dialog?node-id=5950-30008&t=zu3AAiI0StOklFYf-1)

## Critères d'acceptation

Filtre "Organisation" :
* Must have : menu _select_ qui permet de choisir une organisation dans une liste (valeurs possibles : "Toutes les organisations", et liste de toutes les organisations ayant au moins un arrêté dont l'état est "Publié" dans DiaLog)
* Could have : menu _select_ avec recherche plein texte et autocomplétion
* Could have : si l'utilisateur est connecté, son organisation est sélectionnée par défaut (en cas d'appartenance à plusieurs organisations, la première dans l'ordre alphabétique est sélectionné par défaut).

Filtre "Statut" :
* Must have :  menu _select_ qui permet de choisir un statut d'arrêté dans une liste (valeurs possibles : "Tous les status", "Publié", "Brouillon", etc.)

Filtre "Type" :
* Must have : menu _select_ qui permet de choisir un type d'arrêté dans une liste (valeurs possibles : "Tous les statuts, "Temporaires", Permanents")

## Implémentation

* [x] Implémentation initiale #928
* [ ] Améliorations :
  * [x] Intégrer page / pageSize dans le `RegulationListFiltersDTO`
  * [ ] Filtre "Organisation" : champ avec recherche plein texte et autocomplétion (ordre alphabétique)
  * [ ] Présélectionner l'organisation de l'utilisateur connecté
    * Si plusieurs : choisir la 1ère (de façon arbitraire)
* [ ] Vérifier remplissage critères acceptation

**Comment by florimondmanca** [comment]
> pour filtrer les restrictions affichées sur la carte.

Tu voulais écrire ici "sur la liste" ?

**Comment by florimondmanca** [comment]
J'ai bien envie de m'assigner ce ticket pendant que #874 est en review, pour prendre le relais de Mathieu qui avait commencé à travailler dessus

L'absence de fonctions de recherche sur la liste a été un irritant lors de l'analyse des résultats d'intégration de #874, surtout qu'il n'y a même plus de filtre permanent/temporaire depuis #916 (qui était une première étape vers les nouveaux filtres de recherche, mais Mathieu est en congés)

**Comment by florimondmanca** [comment]
Ah et en fait je pense aussi qu'il manque un champ de recherche pour l'**identifiant de l'arrêté**... C'est la fonction de recherche principale dont j'aurais eu besoin pour la review de #874, les filtres proposés dans le présent ticket ne m'auraient pas aidé (ils ne sont pas assez sélectifs)

**Comment by florimondmanca** [comment]
Vu en réunion ce jour, intégration du filtre "Identifiant", @aureliebaton va màj les maquettes

**Comment by johanricher** [comment]
Implémenté par #928
