### ISSUE TITLE
La zone rouge de la cérémonie d'ouverture paralympique est manquante

### ISSUE THREAD

**Issue by vparpoil** [MTES-MCT/dialog#923]
La zone rouge de la cérémonie d'ouverture paralympique est manquante dans le flux
Données issues de visualiz ici :
[Zone rouge cérémonie d'ouverture paralympique.zip](https://github.com/user-attachments/files/16707798/Zone.rouge.ceremonie.d.ouverture.paralympique.zip)

**Comment by florimondmanca** [comment]
Hello,

Même observation que https://github.com/MTES-MCT/dialog/issues/887#issuecomment-2304164741, dans les données de la PP nous n'avions rien concernant la cérémonie d'ouverture paralympique

Merci pour le fichier, je vais voir pour l'intégrer à notre GeoJSON

**Comment by florimondmanca** [comment]
@vparpoil Il manquait les attributs `DATE_DEBUT` et `DATE_FIN`

En manipulant la carte interactive, je pense comprendre que la zone rouge dure du 28/08/2024 à 18h00 au 29/08/2024 à 01h00, je vais utiliser ces valeurs

**Comment by vparpoil** [comment]
@florimondmanca merci beaucoup pour l'intégration. A partir de quand le flux dialog sera-t-il mis à jour ? 
Merci,

**Comment by florimondmanca** [comment]
@vparpoil Pardon j'avais oublié de relancer l'import. C'est chose faite, le flux est à jour https://dialog.beta.gouv.fr/api/regulations.xml
