### ISSUE TITLE
Données Sogelink Ville de Fougères

### ISSUE THREAD

**Issue by MathieuFV** [MTES-MCT/dialog#939]
## User story

La ville de Fougères nous a confié les identifiants afin de récupérer leurs données issues de Litteralis (Sogelink).

Les identifiants sont stockés sur le [Vaultwarden](https://vaultwarden.incubateur.net/#/vault?organizationId=34d00cb3-dcf0-4649-a142-b4e203b4353b).

## Critères d'acceptation

- [ ] _(Must have)_ Les données de la Ville de Fougères sont intégrées à DiaLog
- [ ] _(Nice to have)_ Etablir un comparatif avec les données de la MEL

**Comment by florimondmanca** [comment]
J'ai lancé l'import manuellement, les données de Fougères sont en prod https://dialog.beta.gouv.fr/regulations?identifier=&organizationUuid=019197fb-7055-7c49-a5ba-1fb732d0e45d&regulationOrderType=&status=&pageSize=20

J'ai ouvert #979 pour configurer l'import automatique
