### ISSUE TITLE
Créneaux erronés dans Waze

### ISSUE THREAD

**Issue by MathieuFV** [MTES-MCT/dialog#948]
## Comportement attendu

Lorsqu'un arrêté possède une restriction activée sur des créneaux pendant une période donnée, seules les bornes de la période sont appliquées à la restriction dans Waze. Exemple :

Pour une restriction active du 11/09 à 8h au 12/09 à 17h uniquement entre 8h et 17h, les données intégrées dans Waze ne prennent en compte que la période du 11/09 8h au 12/09 à 17h.

## Comportement réel

La restriction devrait être active uniquement sur les créneaux donnés : le 11/09 de 8h à 17h ET le 12/09 de 8h à 17h.

## Pour reproduire

Cf. arrêté suivant : https://dialog.beta.gouv.fr/regulations/0191b1c7-adbb-7fb0-bb98-563779ef60aa

Qui devient dans Waze : 

![Capture](https://github.com/user-attachments/assets/9642c30c-103c-41cd-b407-d554fb3c35e5)

**Comment by florimondmanca** [comment]
:thinking: Notre CIFS devrait contenir un `<schedule>` pour cette mesure mais ça n'est pas le cas

```xml
<incident id="2024/ST/417:0191b1ca-4e9a-7f17-879d-1c168e242a30:26a7cf901109a2c47e8cc0ba85c3e89e:0191b1ca-4e0f-7d09-afdd-18b144e9938a">
  <creationtime>2024-09-02T08:08:59+00:00</creationtime>
  <type>ROAD_CLOSED</type>
  <description>
    Rue Ambroise De Lore : circulation interdite tous les jours pour tous les véhicles
  </description>
  <street>Rue Ambroise De Lore</street>
  <direction>BOTH_DIRECTIONS</direction>
  <polyline>
    48.308883974 -0.623231133 48.308869002 -0.623161245 48.308802694 -0.623032469
  </polyline>
  <starttime>2024-09-11T06:00:00+00:00</starttime>
  <endtime>2024-09-12T15:00:00+00:00</endtime>
  <source>
    <reference>dialog.beta.gouv.fr</reference>
    <name>DiaLog</name>
    <url>
     https://dialog.beta.gouv.fr/api/regulations/cifs.xml
    </url>
  </source>
</incident>
```

Ça doit être un bug dans le `GetCifsIncidentsQueryHandler`

**Comment by florimondmanca** [comment]
D'ailleurs l'affichage des heures est bizarre

> du 11/09/2024 à 08h00 au 12/09/2024 à 17h00 (**09h00-18h00**)

Soit ils ont mal saisi le créneau 8h/17h, soit on a encore un problème de timezone, à investiguer aussi
