### ISSUE TITLE
Mon compte

### ISSUE THREAD

**Issue by johanricher** [MTES-MCT/dialog#952]
## Description

TODO

## Implémentation

* #934
* #946
* #964

**Comment by florimondmanca** [comment]
"Mon espace" ? Je pense que ce ticket peut s'occuper de ce qui a été préparé avec Aurélie là-dessus (cf Figma). Depuis "Mon espace" on pourra accéder aux orgas (/organizations pour l'instant) et à son compte

Ou alors il faut un autre ticket pour "Mon espace" où on unifierait "Mon compte" et "Mes organisations"
