### ISSUE TITLE
Supprimer la saisie de date d'arrêté

### ISSUE THREAD

**Issue by johanricher** [MTES-MCT/dialog#988]
## Description

Suite au problème identifié et décrit sur #701, [une réunion a eu lieu aujourd'hui](https://pad.incubateur.net/MaOMoW0QS82FIj5oAABVAw?both#2024-10-02---Dates-arr%C3%AAt%C3%A9s) pour se mettre d'accord sur l'implémentation de la solution. Celle-ci reprend la proposition discutée il y a quelques mois : ne plus demander la saisie des dates de début et fin d'un arrêté lors de la création d'un arrêté dans l'UI de DiaLog.

Les dates de début et fin d'un arrêté continueront cependant à être affichées quand le besoin se présente (par exemple valeurs de  "période" sur [la page qui liste les arrêtés](https://dialog.beta.gouv.fr/regulations)) et que cela n'entraine pas de confusion (voir discussion sur #843 pour un exemple). Les valeurs en question seront inférées à partir des dates de début/fin des restrictions ("mesures") qui composent l'arrêté (début d'un arrêté = date la plus tôt de début d'une restriction ; fin d'un arrêté = date la plus tard de fin d'une restriction).

Dans le cadre de cette évolution des adaptations du formulaire sont nécessaire pour simplifier la saisie.

## Implémentation

* Sur la première page du formulaire de création d'un arrêté ("Informations générales") : supprimer la saisie des dates sur l'arrêté
* Enregistrer en base les dates de début et fin d'un arrêté en les inférant à partir de celles des restrictions
* Sur la deuxième page du formulaire de de création d'un arrêté : la saisie des dates de début et de fin d'une restriction est toujours affichée
* Remplacer "plage", "jours et horaires" par "Périodes d'application" + autres reformulation (voir maquette)

## Design

![image](https://github.com/user-attachments/assets/30a00074-11c5-4c5c-a133-ab0b73b337d1)

[Maquette](https://www.figma.com/design/YuT6Uh4wxe90U8LaPLlDzO/Dialog?node-id=6855-34911&t=zqjGc5uwNFkOJ9fB-1)

**Comment by florimondmanca** [comment]
On a un tout petit sujet supplémentaire:

Actuellement pour savoir si un arrêté est "permanent" ou "temporaire", on regarde si une date de fin a été définie

En fonction de ça on affiche ou pas les champs de date de fin dans le formulaire des périodes pour les mesures

Ici on veut inverser la logique, et faire en sorte que les dates de l'arrêté "remontent" des périodes des mesures

Par conséquent, il faut un moyen plus _explicite_ de configurer le fait qu'un arrêté soit permanent ou temporaire, non ?

cc @aureliebaton 

On pourrait dire : si aucune période n'a de date de fin, alors c'est du permanent, sinon c'est du temporaire... Mais est-ce que c'est satisfaisant en termes d'UX ?

**Comment by aureliebaton** [comment]
C'est une bonne question en effet.
Le plus explicite serait peut-être d'ajouter une liste dans le premier formulaire pour sélectionner l'un ou l'autre (temporaire ou permanent). Par exemple à la place de la liste "Nature de l'arrêté" dont on ne se sert pas.

**Comment by florimondmanca** [comment]
@mmarchois Est-ce que tu aurais un avis technique sur le calcul et le stockage des dates globales ? (On peut réutiliser la terminologie datex de la `overallPeriod`)

Au niveau du calcul ces dates sont un `MIN(period.startDate)` et `MAX(period.endDate)`, donc avec double jointure (regulationOrder -> measure -> period)

J'ai envisagé ces options...

* Créer une `VIEW` en relation one-to-one avec `RegulationOrder`
  * La VIEW est exécutée à chaque fois qu'on y accède, potentiellement de façon "incontrôlée" (requêtes inutiles, cache la complexité, source de problèmes de perf ?)
* Créer une `MATERIALIZED VIEW` pour éviter les recalculs
  * Mais il faut gérer son rafraîchissement en appelant `REFRESH MATERIALIZED VIEW`, donc ça ne semble pas appropriées (les vues matérialisées c'est plutôt un cas d'usage d'analytics j'ai l'impression)
* Faire "manuellement" et explicitement le calcul au niveau des repository chaque fois qu'on a besoin de ces dates globales
  * => :heart: C'est l'option vers laquelle je tends pour l'instant...

**Comment by johanricher** [comment]
> Ici on veut inverser la logique, et faire en sorte que les dates de l'arrêté "remontent" des périodes des mesures

> Par conséquent, il faut un moyen plus explicite de configurer le fait qu'un arrêté soit permanent ou temporaire, non ?

Si la définition d'arrêté permanent est "un arrêté avec au moins une mesure sans date de fin", alors on n'a pas besoin de demander au préalable à la personne de choisir "permanent" ou "temporaire", c'est une information dont la saisie est redondante.

Je ne vois pas de cas où le fait que la saisie ne soit pas explicite poserait un problème.

L'information devrait néanmoins restée affichée (comme pour les valeurs de périodes de l'arrêté) : inférée et non pas demandée

A l'inverse, si on veut une UX où la personne doit choisir explicitement entre "permanent" et "temporaire", il risque d'y avoir une confusion.

Par exemple : je choisis "arrêté permanent" sans comprendre exactement ce que ça veut dire, et ensuite le formulaire rend impossible de choisir une date de fin, et je ne comprends pas pourquoi.

Autre exemple : je choisis "arrêté permanent" mais je veux définir 2 restrictions dont seulement une n'a pas de date de fin.

**Comment by mmarchois** [comment]
@florimondmanca je dirais que la solution se jouera entre la 3 et la 4, et cela dépendra également de la fréquence d'utilisation des dates de début/fin.

Si c'est une donnée qui sera souvent requêtée, dans un souci de performance, je préférerais la stocker dans la table `RegulationOrder` pour éviter un recalcul à la volée. Concernant l'implémentation technique de cette option, je n'opterais pas pour des `TRIGGER`, mais plutôt pour des opérations effectuées directement dans les handlers, afin de conserver la logique applicative.
En revanche, si cette donnée est utilisée de manière occasionnelle, la solution 4 me semble la plus adaptée.

**Comment by MathieuFV** [comment]
Merci pour le compte rendu très clair déjà :)

De ma compréhension, l'option que proposait Johan ne me dérange pas. Il s'agit finalement de poser la question à un utilisateur pour nous assurer que cette catégorisation implicite en arrêté permanent ou temporaire leur semble souhaitable. 

D'un autre côté, on peut imaginer que (plus tard) les formulaires pour les arrêtés temporaires et permanents ne soient pas tout à fait les mêmes, ça plaiderait pour l'option d'Aurélie.

Je vais poser la question à la personne de Lambersart qui m'a dit avoir testé l'outil récemment. Au demeurant choisir l'option la moins complexe me semblerait souhaitable ?

Je reviens vers vous quand j'en sais plus !

**Comment by florimondmanca** [comment]
Vu les mails : un utilisateur a confirmé qu'il ne s'attendait pas à devoir indiquer explicitement en amont si un arrêté est temporaire ou permanent, car il considère que l'info est présente dans les périodes d'application

Ça confirme l'intérêt de pousser l'inférence jusqu'à la qualification "temporaire vs permanent"

Par contre pour éviter toute introduction de bug (toucher aux périodes est un peu casse-tête), je vais procéder en deux étapes

1. Supprimer les champs date de début / fin globales sur l'arrêté (l'objet de ce ticket) ; le calcul du critère temporaire / permanent est reporté sur la "catégorie" : un arrêté est permanent si et seulement si sa catégorie vaut "Réglementation permanente"
2. Inférer le type temporaire / permanent en fonction des périodes d'application

**Comment by aureliebaton** [comment]
Suite à la discussion sur Mattermost et à la proposition d'ajouter un bloc spécifique pour les périodes, voici une nouvelle proposition de maquette https://www.figma.com/design/YuT6Uh4wxe90U8LaPLlDzO/Dialog?node-id=7230-24296&t=UoPI31I6VQTOoG2x-1
