### ISSUE TITLE
Dupliquer une mesure

### ISSUE THREAD

**Issue by johanricher** [MTES-MCT/dialog#989]
## Description

Suite à #988 qui a supprimé la saisie de la période d'un arrêté (dates de début et fin) on souhaite simplifier la saisie des dates de début et fin d'une restriction.

La possibilité de dupliquer une mesure déjà saisie permettra dans certains cas de simplifier la saisie de la mesure suivante : pas besoin de saisir à nouveau toutes les valeurs, il suffira de modifier seulement celles qui changent, par exemple la localisation.

## Maquette

Mesure : Ajout d'un bouton "Dupliquer" à côté du bouton "Modifier"

[Maquette](https://www.figma.com/design/YuT6Uh4wxe90U8LaPLlDzO/Dialog?node-id=7230-24296&node-type=frame&t=w5gSgdO29JhDAjV3-0) (attention bug de marge au niveau du bouton)

![image](https://github.com/user-attachments/assets/e3dbfee6-cb91-4428-ba27-153c6d62c0c6)

## Implémentation

* Le bouton dupliquer pointe vers un controller qui prend le uuid de la mesure
* Le controller duplique la mesure via un command handler dédié (s'inspirer de DuplicateRegulationCommandHandler)
* Le controller renvoie un fragment via [Turbo stream](https://turbo.hotwired.dev/reference/streams) contenant la carte de la mesure dupliquée

**Comment by florimondmanca** [comment]
Implémentation pas triviale (manipulation des FormCollection en Symfony)

Design review à faire, avec Léa, MathieuM, et moi

**Comment by florimondmanca** [comment]
Proposition : séparer le ticket en deux

1. Dupliquer une mesure (implémentation + facile)
2. Dupliquer une période d'application

Je vais reformuler ce ticket 989 pour se concentrer sur (1), et en créer un autre pour les périodes d'application

**Comment by florimondmanca** [comment]
Je clos car a priori résolu par #1063 :)

**Comment by johanricher** [comment]
Je confirme après avoir testé ça fonctionne comme attendu ! bravo :clap:
